(function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
'use strict';var f;function aa(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}}function ba(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return b?b.call(a):{next:aa(a)}}function ca(a){a=["object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global,a];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}return globalThis}
var l=ca(this),da="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)};function ea(a,b){if(b){var c=l;a=a.split(".");for(var d=0;d<a.length-1;d++){var e=a[d];e in c||(c[e]={});c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&da(c,a,{configurable:!0,writable:!0,value:b})}}
ea("Promise",function(a){function b(g){this.b=0;this.g=void 0;this.a=[];var k=this.c();try{g(k.resolve,k.reject)}catch(m){k.reject(m)}}function c(){this.a=null}function d(g){return g instanceof b?g:new b(function(k){k(g)})}if(a)return a;c.prototype.b=function(g){if(null==this.a){this.a=[];var k=this;this.c(function(){k.g()})}this.a.push(g)};var e=l.setTimeout;c.prototype.c=function(g){e(g,0)};c.prototype.g=function(){for(;this.a&&this.a.length;){var g=this.a;this.a=[];for(var k=0;k<g.length;++k){var m=
g[k];g[k]=null;try{m()}catch(q){this.f(q)}}}this.a=null};c.prototype.f=function(g){this.c(function(){throw g;})};b.prototype.c=function(){function g(q){return function(B){m||(m=!0,q.call(k,B))}}var k=this,m=!1;return{resolve:g(this.F),reject:g(this.f)}};b.prototype.F=function(g){if(g===this)this.f(new TypeError("A Promise cannot resolve to itself"));else if(g instanceof b)this.G(g);else{a:switch(typeof g){case "object":var k=null!=g;break a;case "function":k=!0;break a;default:k=!1}k?this.o(g):this.h(g)}};
b.prototype.o=function(g){var k=void 0;try{k=g.then}catch(m){this.f(m);return}"function"==typeof k?this.I(k,g):this.h(g)};b.prototype.f=function(g){this.i(2,g)};b.prototype.h=function(g){this.i(1,g)};b.prototype.i=function(g,k){if(0!=this.b)throw Error("Cannot settle("+g+", "+k+"): Promise already settled in state"+this.b);this.b=g;this.g=k;this.j()};b.prototype.j=function(){if(null!=this.a){for(var g=0;g<this.a.length;++g)h.b(this.a[g]);this.a=null}};var h=new c;b.prototype.G=function(g){var k=this.c();
g.w(k.resolve,k.reject)};b.prototype.I=function(g,k){var m=this.c();try{g.call(k,m.resolve,m.reject)}catch(q){m.reject(q)}};b.prototype.then=function(g,k){function m(H,Q){return"function"==typeof H?function(La){try{q(H(La))}catch(Ma){B(Ma)}}:Q}var q,B,Na=new b(function(H,Q){q=H;B=Q});this.w(m(g,q),m(k,B));return Na};b.prototype.catch=function(g){return this.then(void 0,g)};b.prototype.w=function(g,k){function m(){switch(q.b){case 1:g(q.g);break;case 2:k(q.g);break;default:throw Error("Unexpected state: "+
q.b);}}var q=this;null==this.a?h.b(m):this.a.push(m)};b.resolve=d;b.reject=function(g){return new b(function(k,m){m(g)})};b.race=function(g){return new b(function(k,m){for(var q=ba(g),B=q.next();!B.done;B=q.next())d(B.value).w(k,m)})};b.all=function(g){var k=ba(g),m=k.next();return m.done?d([]):new b(function(q,B){function Na(La){return function(Ma){H[La]=Ma;Q--;0==Q&&q(H)}}var H=[],Q=0;do H.push(void 0),Q++,d(m.value).w(Na(H.length-1),B),m=k.next();while(!m.done)})};return b});
function fa(){fa=function(){};l.Symbol||(l.Symbol=ha)}function ia(a,b){this.a=a;da(this,"description",{configurable:!0,writable:!0,value:b})}ia.prototype.toString=function(){return this.a};var ha=function(){function a(c){if(this instanceof a)throw new TypeError("Symbol is not a constructor");return new ia("jscomp_symbol_"+(c||"")+"_"+b++,c)}var b=0;return a}();
function ja(){fa();var a=l.Symbol.iterator;a||(a=l.Symbol.iterator=l.Symbol("Symbol.iterator"));"function"!=typeof Array.prototype[a]&&da(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return ka(aa(this))}});ja=function(){}}function ka(a){ja();a={next:a};a[l.Symbol.iterator]=function(){return this};return a}function la(a){if(!(a instanceof Object))throw new TypeError("Iterator result "+a+" is not an object");}
function ma(){this.h=!1;this.f=null;this.j=void 0;this.a=1;this.g=this.c=0;this.i=this.b=null}function na(a){if(a.h)throw new TypeError("Generator is already running");a.h=!0}f=ma.prototype;f.A=function(a){this.j=a};function oa(a,b){a.b={K:b,L:!0};a.a=a.c||a.g}f.return=function(a){this.b={return:a};this.a=this.g};f.Ma=function(a){this.b={u:a};this.a=this.g};function pa(a,b,c){a.a=c;return{value:b}}
f.Gc=function(a,b){a=ba(a);var c=a.next();la(c);if(c.done)this.j=c.value,this.a=b;else return this.f=a,pa(this,c.value,b)};f.u=function(a){this.a=a};f.Na=function(){this.a=0};f.ab=function(a){this.c=0;this.g=a||0};function qa(a,b){a.a=b;a.c=0}function ra(a){a.c=0;var b=a.b.K;a.b=null;return b}f.Y=function(a,b,c){c?this.i[c]=this.b:this.i=[this.b];this.c=a||0;this.g=b||0};
f.Oa=function(a,b){b=this.i.splice(b||0)[0];(b=this.b=this.b||b)?b.L?this.a=this.c||this.g:void 0!=b.u&&this.g<b.u?(this.a=b.u,this.b=null):this.a=this.g:this.a=a};f.aa=function(a){return new sa(a)};function sa(a){this.b=a;this.a=[];for(var b in a)this.a.push(b);this.a.reverse()}sa.prototype.c=function(){for(;0<this.a.length;){var a=this.a.pop();if(a in this.b)return a}return null};function ta(a){this.a=new ma;this.b=a}
function ua(a,b){na(a.a);var c=a.a.f;if(c)return va(a,"return"in c?c["return"]:function(d){return{value:d,done:!0}},b,a.a.return);a.a.return(b);return wa(a)}function va(a,b,c,d){try{var e=b.call(a.a.f,c);la(e);if(!e.done)return a.a.h=!1,e;var h=e.value}catch(g){return a.a.f=null,oa(a.a,g),wa(a)}a.a.f=null;d.call(a.a,h);return wa(a)}
function wa(a){for(;a.a.a;)try{var b=a.b(a.a);if(b)return a.a.h=!1,{value:b.value,done:!1}}catch(c){a.a.j=void 0,oa(a.a,c)}a.a.h=!1;if(a.a.b){b=a.a.b;a.a.b=null;if(b.L)throw b.K;return{value:b.return,done:!0}}return{value:void 0,done:!0}}
function xa(a){this.next=function(b){na(a.a);a.a.f?b=va(a,a.a.f.next,b,a.a.A):(a.a.A(b),b=wa(a));return b};this.throw=function(b){na(a.a);a.a.f?b=va(a,a.a.f["throw"],b,a.a.A):(oa(a.a,b),b=wa(a));return b};this.return=function(b){return ua(a,b)};ja();this[Symbol.iterator]=function(){return this}}function ya(a){function b(d){return a.next(d)}function c(d){return a.throw(d)}return new Promise(function(d,e){function h(g){g.done?d(g.value):Promise.resolve(g.value).then(b,c).then(h,e)}h(a.next())})}
ea("globalThis",function(a){return a||l});var n=this||self;function za(a){a=a.split(".");for(var b=n,c=0;c<a.length;c++)if(b=b[a[c]],null==b)return null;return b}function Aa(){}
function Ba(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b}function p(a){return"array"==Ba(a)}function Ca(a){var b=Ba(a);return"array"==b||"object"==b&&"number"==typeof a.length}function Da(a){var b=typeof a;return"object"==b&&null!=a||"function"==b}function Ea(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var d=c.slice();d.push.apply(d,arguments);return a.apply(this,d)}}var Fa=Date.now||function(){return+new Date};
function Ga(a,b){a=a.split(".");var c=n;a[0]in c||"undefined"==typeof c.execScript||c.execScript("var "+a[0]);for(var d;a.length&&(d=a.shift());)a.length||void 0===b?c[d]&&c[d]!==Object.prototype[d]?c=c[d]:c=c[d]={}:c[d]=b}function Ha(a,b){function c(){}c.prototype=b.prototype;a.J=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.S=function(d,e,h){for(var g=Array(arguments.length-2),k=2;k<arguments.length;k++)g[k-2]=arguments[k];return b.prototype[e].apply(d,g)}};var Ia=Array.prototype.indexOf?function(a,b){return Array.prototype.indexOf.call(a,b,void 0)}:function(a,b){if("string"===typeof a)return"string"!==typeof b||1!=b.length?-1:a.indexOf(b,0);for(var c=0;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},Ja=Array.prototype.forEach?function(a,b,c){Array.prototype.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,e="string"===typeof a?a.split(""):a,h=0;h<d;h++)h in e&&b.call(c,e[h],h,a)},Ka=Array.prototype.map?function(a,b){return Array.prototype.map.call(a,
b,void 0)}:function(a,b){for(var c=a.length,d=Array(c),e="string"===typeof a?a.split(""):a,h=0;h<c;h++)h in e&&(d[h]=b.call(void 0,e[h],h,a));return d};function Oa(a){return Array.prototype.concat.apply([],arguments)}function Pa(a){var b=a.length;if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]}function Qa(a,b,c){return 2>=arguments.length?Array.prototype.slice.call(a,b):Array.prototype.slice.call(a,b,c)};var Ra=String.prototype.trim?function(a){return a.trim()}:function(a){return/^[\s\xa0]*([\s\S]*?)[\s\xa0]*$/.exec(a)[1]};function r(a,b){return-1!=a.indexOf(b)}function Sa(a,b){return a<b?-1:a>b?1:0};var t;a:{var Ta=n.navigator;if(Ta){var Ua=Ta.userAgent;if(Ua){t=Ua;break a}}t=""};function Va(a,b,c){for(var d in a)b.call(c,a[d],d,a)}function Wa(a,b){for(var c in a)if(b.call(void 0,a[c],c,a))return!0;return!1};function Xa(a){Xa[" "](a);return a}Xa[" "]=Aa;var Ya=r(t,"Opera"),u=r(t,"Trident")||r(t,"MSIE"),Za=r(t,"Edge"),$a=r(t,"Gecko")&&!(r(t.toLowerCase(),"webkit")&&!r(t,"Edge"))&&!(r(t,"Trident")||r(t,"MSIE"))&&!r(t,"Edge"),ab=r(t.toLowerCase(),"webkit")&&!r(t,"Edge"),bb=r(t,"Macintosh");function cb(){var a=n.document;return a?a.documentMode:void 0}var db;
a:{var eb="",fb=function(){var a=t;if($a)return/rv:([^\);]+)(\)|;)/.exec(a);if(Za)return/Edge\/([\d\.]+)/.exec(a);if(u)return/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/.exec(a);if(ab)return/WebKit\/(\S+)/.exec(a);if(Ya)return/(?:Version)[ \/]?(\S+)/.exec(a)}();fb&&(eb=fb?fb[1]:"");if(u){var gb=cb();if(null!=gb&&gb>parseFloat(eb)){db=String(gb);break a}}db=eb}var hb=db,ib={},jb;jb=n.document&&u?cb():void 0;function kb(a){if(8192>=a.length)return String.fromCharCode.apply(null,a);for(var b="",c=0;c<a.length;c+=8192)b+=String.fromCharCode.apply(null,Qa(a,c,c+8192));return b};var lb={},mb=null;function nb(a,b){void 0===b&&(b=0);ob();b=lb[b];for(var c=[],d=0;d<a.length;d+=3){var e=a[d],h=d+1<a.length,g=h?a[d+1]:0,k=d+2<a.length,m=k?a[d+2]:0,q=e>>2;e=(e&3)<<4|g>>4;g=(g&15)<<2|m>>6;m&=63;k||(m=64,h||(g=64));c.push(b[q],b[e],b[g]||"",b[m]||"")}return c.join("")}function pb(a){var b=a.length,c=3*b/4;c%3?c=Math.floor(c):r("=.",a[b-1])&&(c=r("=.",a[b-2])?c-2:c-1);var d=new Uint8Array(c),e=0;qb(a,function(h){d[e++]=h});return d.subarray(0,e)}
function qb(a,b){function c(m){for(;d<a.length;){var q=a.charAt(d++),B=mb[q];if(null!=B)return B;if(!/^[\s\xa0]*$/.test(q))throw Error("Unknown base64 encoding at char: "+q);}return m}ob();for(var d=0;;){var e=c(-1),h=c(0),g=c(64),k=c(64);if(64===k&&-1===e)break;b(e<<2|h>>4);64!=g&&(b(h<<4&240|g>>2),64!=k&&b(g<<6&192|k))}}
function ob(){if(!mb){mb={};for(var a="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789".split(""),b=["+/=","+/","-_=","-_.","-_"],c=0;5>c;c++){var d=a.concat(b[c].split(""));lb[c]=d;for(var e=0;e<d.length;e++){var h=d[e];void 0===mb[h]&&(mb[h]=e)}}}};var v=0,w=0;function rb(a){var b=a>>>0;a=Math.floor((a-b)/4294967296)>>>0;v=b;w=a}function x(a){var b=0>a;a=Math.abs(a);var c=a>>>0;a=Math.floor((a-c)/4294967296);a>>>=0;b&&(a=~a>>>0,c=(~c>>>0)+1,4294967295<c&&(c=0,a++,4294967295<a&&(a=0)));v=c;w=a}function sb(a){var b=0>a;a=2*Math.abs(a);rb(a);a=v;var c=w;b&&(0==a?0==c?c=a=4294967295:(c--,a=4294967295):a--);v=a;w=c}
function tb(a){var b=0>a?1:0;a=b?-a:a;if(0===a)0<1/a?v=w=0:(w=0,v=2147483648);else if(isNaN(a))w=0,v=2147483647;else if(3.4028234663852886E38<a)w=0,v=(b<<31|2139095040)>>>0;else if(1.1754943508222875E-38>a)a=Math.round(a/Math.pow(2,-149)),w=0,v=(b<<31|a)>>>0;else{var c=Math.floor(Math.log(a)/Math.LN2);a*=Math.pow(2,-c);a=Math.round(8388608*a)&8388607;w=0;v=(b<<31|c+127<<23|a)>>>0}}
function y(a){var b=a.charCodeAt(4),c=a.charCodeAt(5),d=a.charCodeAt(6),e=a.charCodeAt(7);v=a.charCodeAt(0)+(a.charCodeAt(1)<<8)+(a.charCodeAt(2)<<16)+(a.charCodeAt(3)<<24)>>>0;w=b+(c<<8)+(d<<16)+(e<<24)>>>0}function ub(a,b,c){var d=b>>31;c(a<<1^d,(b<<1|a>>>31)^d)}
function vb(a){function b(g,k){for(var m=0;8>m&&(1!==g||0<k);m++)k=g*e[m]+k,e[m]=k&255,k>>>=8}function c(){for(var g=0;8>g;g++)e[g]=~e[g]&255}var d=!1;"-"===a[0]&&(d=!0,a=a.slice(1));for(var e=[0,0,0,0,0,0,0,0],h=0;h<a.length;h++)b(10,a.charCodeAt(h)-48);d&&(c(),b(1,1));return kb(e)};function z(a,b){this.a=a;this.b=b}function wb(a){return new z((a.a>>>1|(a.b&1)<<31)>>>0,a.b>>>1>>>0)}function xb(a){return new z(a.a<<1>>>0,(a.b<<1|a.a>>>31)>>>0)}f=z.prototype;f.Ta=function(){return!!(this.a&1)};f.add=function(a){return new z((this.a+a.a&4294967295)>>>0>>>0,((this.b+a.b&4294967295)>>>0)+(4294967296<=this.a+a.a?1:0)>>>0)};f.sub=function(a){return new z((this.a-a.a&4294967295)>>>0>>>0,((this.b-a.b&4294967295)>>>0)-(0>this.a-a.a?1:0)>>>0)};
function yb(a){var b=a&65535,c=a>>>16;a=10*b+65536*(0*b&65535)+65536*(10*c&65535);for(b=0*c+(0*b>>>16)+(10*c>>>16);4294967296<=a;)a-=4294967296,b+=1;return new z(a>>>0,b>>>0)}f.toString=function(){for(var a="",b=this;0!=b.a||0!=b.b;){var c=new z(0,0);b=new z(b.a,b.b);for(var d=new z(10,0),e=new z(1,0);!(d.b&2147483648);)d=xb(d),e=xb(e);for(;0!=e.a||0!=e.b;)0>=(d.b<b.b||d.b==b.b&&d.a<b.a?-1:d.b==b.b&&d.a==b.a?0:1)&&(c=c.add(e),b=b.sub(d)),d=wb(d),e=wb(e);c=[c,b];b=c[0];a=c[1].a+a}""==a&&(a="0");return a};
function zb(a){for(var b=new z(0,0),c=new z(0,0),d=0;d<a.length;d++){if("0">a[d]||"9"<a[d])return null;c.a=parseInt(a[d],10);var e=yb(b.a);b=yb(b.b);b.b=b.a;b.a=0;b=e.add(b).add(c)}return b}f.La=function(){return new z(this.a,this.b)};function A(a,b){this.a=a;this.b=b}A.prototype.add=function(a){return new A((this.a+a.a&4294967295)>>>0>>>0,((this.b+a.b&4294967295)>>>0)+(4294967296<=this.a+a.a?1:0)>>>0)};
A.prototype.sub=function(a){return new A((this.a-a.a&4294967295)>>>0>>>0,((this.b-a.b&4294967295)>>>0)-(0>this.a-a.a?1:0)>>>0)};A.prototype.c=function(){return new A(this.a,this.b)};A.prototype.toString=function(){var a=0!=(this.b&2147483648),b=new z(this.a,this.b);a&&(b=(new z(0,0)).sub(b));return(a?"-":"")+b.toString()};function Ab(a){var b=0<a.length&&"-"==a[0];b&&(a=a.substring(1));a=zb(a);if(null===a)return null;b&&(a=(new z(0,0)).sub(a));return new A(a.a,a.b)};function Bb(){this.a=[]}f=Bb.prototype;f.length=function(){return this.a.length};function Cb(a){var b=a.a;a.a=[];return b}function C(a,b,c){for(;0<c||127<b;)a.a.push(b&127|128),b=(b>>>7|c<<25)>>>0,c>>>=7;a.a.push(b)}function D(a,b,c){E(a,b);E(a,c)}function F(a,b){for(;127<b;)a.a.push(b&127|128),b>>>=7;a.a.push(b)}function G(a,b){if(0<=b)F(a,b);else{for(var c=0;9>c;c++)a.a.push(b&127|128),b>>=7;a.a.push(1)}}function Db(a,b){F(a,(b<<1^b>>31)>>>0)}
function I(a,b){y(b);ub(v,w,function(c,d){C(a,c>>>0,d>>>0)})}f.Fc=function(a){this.a.push(a>>>0&255)};f.Ec=function(a){this.a.push(a>>>0&255);this.a.push(a>>>8&255)};function E(a,b){a.a.push(b>>>0&255);a.a.push(b>>>8&255);a.a.push(b>>>16&255);a.a.push(b>>>24&255)}function Eb(a,b){rb(b);E(a,v);E(a,w)}f.ub=function(a){this.a.push(a>>>0&255)};f.tb=function(a){this.a.push(a>>>0&255);this.a.push(a>>>8&255)};
function Fb(a,b){a.a.push(b>>>0&255);a.a.push(b>>>8&255);a.a.push(b>>>16&255);a.a.push(b>>>24&255)}
function Gb(a,b){var c=b;c=(b=0>c?1:0)?-c:c;if(0===c)w=0<1/c?0:2147483648,v=0;else if(isNaN(c))w=2147483647,v=4294967295;else if(1.7976931348623157E308<c)w=(b<<31|2146435072)>>>0,v=0;else if(2.2250738585072014E-308>c)c/=Math.pow(2,-1074),w=(b<<31|c/4294967296)>>>0,v=c>>>0;else{var d=c,e=0;if(2<=d)for(;2<=d&&1023>e;)e++,d/=2;else for(;1>d&&-1022<e;)d*=2,e--;c*=Math.pow(2,-e);w=(b<<31|e+1023<<20|1048576*c&1048575)>>>0;v=4503599627370496*c>>>0}E(a,v);E(a,w)}
f.Ha=function(a){this.a.push.apply(this.a,a)};function Hb(a,b){y(b);E(a,v);E(a,w)};function Ib(){this.c=[];this.b=0;this.a=new Bb;this.f=[]}function Jb(a,b){var c=Cb(a.a);a.c.push(c);a.c.push(b);a.b+=c.length+b.length}function J(a,b){K(a,b,2);b=Cb(a.a);a.c.push(b);a.b+=b.length;b.push(a.b);return b}function L(a,b){var c=b.pop();for(c=a.b+a.a.length()-c;127<c;)b.push(c&127|128),c>>>=7,a.b++;b.push(c);a.b++}f=Ib.prototype;f.Va=function(a,b,c){null!=a&&null!=b&&null!=c&&Jb(this,a.subarray(b,c))};f.Ia=function(){this.c=[];Cb(this.a);this.b=0;this.f=[]};
function Kb(a){for(var b=new Uint8Array(a.b+a.a.length()),c=a.c,d=c.length,e=0,h=0;h<d;h++){var g=c[h];b.set(g,e);e+=g.length}c=Cb(a.a);b.set(c,e);a.c=[b];return b}f.ha=function(a){return nb(Kb(this),a)};f.T=function(a){this.f.push(J(this,a))};f.X=function(){L(this,this.f.pop())};function K(a,b,c){F(a.a,8*b+c)}
f.rb=function(a,b,c){switch(a){case 1:null!=c&&(K(this,b,1),Gb(this.a,c));break;case 2:null!=c&&(K(this,b,5),a=this.a,tb(c),E(a,v));break;case 3:null!=c&&null!=c&&(K(this,b,0),a=this.a,x(c),C(a,v,w));break;case 4:null!=c&&null!=c&&(K(this,b,0),a=this.a,x(c),C(a,v,w));break;case 5:null!=c&&Lb(this,b,c);break;case 6:null!=c&&(K(this,b,1),Eb(this.a,c));break;case 7:null!=c&&(K(this,b,5),E(this.a,c));break;case 8:Mb(this,b,c);break;case 9:M(this,b,c);break;case 12:Nb(this,b,c);break;case 13:null!=c&&
Ob(this,b,c);break;case 14:Pb(this,b,c);break;case 15:null!=c&&(K(this,b,5),Fb(this.a,c));break;case 16:null!=c&&(K(this,b,1),a=this.a,x(c),D(a,v,w));break;case 17:null!=c&&null!=c&&(K(this,b,0),Db(this.a,c));break;case 18:null!=c&&null!=c&&(K(this,b,0),a=this.a,sb(c),C(a,v,w));break;case 30:null!=c&&(K(this,b,1),Hb(this.a,c));break;case 31:null!=c&&(K(this,b,0),a=this.a,y(c),C(a,v,w))}};function Ob(a,b,c){null!=c&&(K(a,b,0),F(a.a,c))}function Lb(a,b,c){null!=c&&(K(a,b,0),G(a.a,c))}
f.Dc=function(a,b){null!=b&&null!=b&&(K(this,a,0),I(this.a,b))};f.Cc=function(a,b){null!=b&&null!=b&&(K(this,a,0),I(this.a,vb(b)))};function Mb(a,b,c){null!=c&&(K(a,b,0),a.a.a.push(c?1:0))}function Pb(a,b,c){null!=c&&(K(a,b,0),G(a.a,c))}
function M(a,b,c){if(null!=c){b=J(a,b);for(var d=a.a,e=0;e<c.length;e++){var h=c.charCodeAt(e);if(128>h)d.a.push(h);else if(2048>h)d.a.push(h>>6|192),d.a.push(h&63|128);else if(65536>h)if(55296<=h&&56319>=h&&e+1<c.length){var g=c.charCodeAt(e+1);56320<=g&&57343>=g&&(h=1024*(h-55296)+g-56320+65536,d.a.push(h>>18|240),d.a.push(h>>12&63|128),d.a.push(h>>6&63|128),d.a.push(h&63|128),e++)}else d.a.push(h>>12|224),d.a.push(h>>6&63|128),d.a.push(h&63|128)}L(a,b)}}
function Nb(a,b,c){null!=c&&(c=c.constructor===Uint8Array?c:c.constructor===ArrayBuffer?new Uint8Array(c):c.constructor===Array?new Uint8Array(c):c.constructor===String?pb(c):new Uint8Array(0),K(a,b,2),F(a.a,c.length),Jb(a,c))}f.vb=function(a,b,c){null!=b&&(a=J(this,a),c(b,this),L(this,a))};f.wb=function(a,b,c){null!=b&&(K(this,1,3),K(this,2,0),G(this.a,a),a=J(this,3),c(b,this),L(this,a),K(this,1,4))};f.sb=function(a,b,c){null!=b&&(K(this,a,3),c(b,this),K(this,a,4))};
function Qb(a,b,c,d){K(a,b,0);var e=a.a;ub(c,d,function(h,g){C(e,h>>>0,g>>>0)})}f.ic=function(a,b){if(null!=b)for(var c=0;c<b.length;c++)Lb(this,a,b[c])};f.jc=function(a,b){if(null!=b)for(var c=0;c<b.length;c++){var d=b[c];null!=d&&Lb(this,a,parseInt(d,10))}};f.kc=function(a,b){if(null!=b)for(var c=0;c<b.length;c++){var d=b[c];if(null!=d){K(this,a,0);var e=this.a;x(d);C(e,v,w)}}};f.uc=function(a,b,c,d){if(null!=b)for(var e=0;e<b.length;e++){var h=c(b[e]),g=d(b[e]);K(this,a,1);D(this.a,h,g)}};
f.vc=function(a,b,c,d){if(null!=b)for(var e=0;e<b.length;e++){var h=c(b[e]),g=d(b[e]);K(this,a,0);C(this.a,h,g)}};f.wc=function(a,b,c,d){if(null!=b)for(var e=0;e<b.length;e++)Qb(this,a,c(b[e]),d(b[e]))};f.lc=function(a,b){if(null!=b)for(var c=0;c<b.length;c++){var d=a,e=b[c];null!=e&&(e=Ab(e),K(this,d,0),C(this.a,e.a,e.b))}};f.xc=function(a,b){if(null!=b)for(var c=0;c<b.length;c++)Ob(this,a,b[c])};f.yc=function(a,b){if(null!=b)for(var c=0;c<b.length;c++){var d=b[c];null!=d&&Ob(this,a,parseInt(d,10))}};
f.zc=function(a,b){if(null!=b)for(var c=0;c<b.length;c++){var d=b[c];if(null!=d){K(this,a,0);var e=this.a;x(d);C(e,v,w)}}};f.Ac=function(a,b){if(null!=b)for(var c=0;c<b.length;c++){var d=a,e=b[c];null!=e&&(e=zb(e),K(this,d,0),C(this.a,e.a,e.b))}};f.qc=function(a,b){if(null!=b)for(var c=0;c<b.length;c++){var d=b[c];null!=d&&(K(this,a,0),Db(this.a,d))}};f.rc=function(a,b){if(null!=b)for(var c=0;c<b.length;c++){var d=b[c];if(null!=d){K(this,a,0);var e=this.a;sb(d);C(e,v,w)}}};
f.sc=function(a,b){if(null!=b)for(var c=0;c<b.length;c++){var d=b[c];null!=d&&(K(this,a,0),I(this.a,vb(d)))}};f.tc=function(a,b){if(null!=b)for(var c=0;c<b.length;c++){var d=b[c];null!=d&&(K(this,a,0),I(this.a,d))}};f.bc=function(a,b){if(null!=b)for(var c=0;c<b.length;c++){var d=b[c];null!=d&&(K(this,a,5),E(this.a,d))}};f.cc=function(a,b){if(null!=b)for(var c=0;c<b.length;c++){var d=b[c];null!=d&&(K(this,a,1),Eb(this.a,d))}};
f.dc=function(a,b){if(null!=b)for(var c=0;c<b.length;c++){var d=a,e=b[c];null!=e&&(e=zb(e),K(this,d,1),D(this.a,e.a,e.b))}};f.nc=function(a,b){if(null!=b)for(var c=0;c<b.length;c++){var d=b[c];null!=d&&(K(this,a,5),Fb(this.a,d))}};f.oc=function(a,b){if(null!=b)for(var c=0;c<b.length;c++){var d=b[c];if(null!=d){K(this,a,1);var e=this.a;x(d);D(e,v,w)}}};f.pc=function(a,b){if(null!=b)for(var c=0;c<b.length;c++){var d=a,e=b[c];null!=e&&(e=Ab(e),K(this,d,1),D(this.a,e.a,e.b))}};
f.fc=function(a,b){if(null!=b)for(var c=0;c<b.length;c++){var d=b[c];if(null!=d){K(this,a,5);var e=this.a;tb(d);E(e,v)}}};f.$b=function(a,b){if(null!=b)for(var c=0;c<b.length;c++){var d=b[c];null!=d&&(K(this,a,1),Gb(this.a,d))}};f.Yb=function(a,b){if(null!=b)for(var c=0;c<b.length;c++)Mb(this,a,b[c])};f.ac=function(a,b){if(null!=b)for(var c=0;c<b.length;c++)Pb(this,a,b[c])};f.Zb=function(a,b){if(null!=b)for(var c=0;c<b.length;c++)Nb(this,a,b[c])};
f.mc=function(a,b,c){if(null!=b)for(var d=0;d<b.length;d++){var e=J(this,a);c(b[d],this);L(this,e)}};f.hc=function(a,b,c){if(null!=b)for(var d=0;d<b.length;d++)K(this,a,3),c(b[d],this),K(this,a,4)};f.ec=function(a,b){if(null!=b)for(var c=0;c<b.length;c++){var d=b[c];null!=d&&(K(this,a,1),Hb(this.a,d))}};f.Bc=function(a,b){if(null!=b)for(var c=0;c<b.length;c++){var d=b[c];if(null!=d){K(this,a,0);var e=this.a;y(d);C(e,v,w)}}};
f.Fb=function(a,b){if(null!=b&&b.length){a=J(this,a);for(var c=0;c<b.length;c++)G(this.a,b[c]);L(this,a)}};f.Gb=function(a,b){if(null!=b&&b.length){a=J(this,a);for(var c=0;c<b.length;c++)G(this.a,parseInt(b[c],10));L(this,a)}};f.Hb=function(a,b){if(null!=b&&b.length){a=J(this,a);for(var c=0;c<b.length;c++){var d=this.a;x(b[c]);C(d,v,w)}L(this,a)}};f.Qb=function(a,b,c,d){if(null!=b){a=J(this,a);for(var e=0;e<b.length;e++)D(this.a,c(b[e]),d(b[e]));L(this,a)}};
f.Rb=function(a,b,c,d){if(null!=b){a=J(this,a);for(var e=0;e<b.length;e++)C(this.a,c(b[e]),d(b[e]));L(this,a)}};f.Sb=function(a,b,c,d){if(null!=b){a=J(this,a);for(var e=this.a,h=0;h<b.length;h++)ub(c(b[h]),d(b[h]),function(g,k){C(e,g>>>0,k>>>0)});L(this,a)}};f.Ib=function(a,b){if(null!=b&&b.length){a=J(this,a);for(var c=0;c<b.length;c++){var d=Ab(b[c]);C(this.a,d.a,d.b)}L(this,a)}};f.Tb=function(a,b){if(null!=b&&b.length){a=J(this,a);for(var c=0;c<b.length;c++)F(this.a,b[c]);L(this,a)}};
f.Ub=function(a,b){if(null!=b&&b.length){a=J(this,a);for(var c=0;c<b.length;c++)F(this.a,parseInt(b[c],10));L(this,a)}};f.Vb=function(a,b){if(null!=b&&b.length){a=J(this,a);for(var c=0;c<b.length;c++){var d=this.a;x(b[c]);C(d,v,w)}L(this,a)}};f.Wb=function(a,b){if(null!=b&&b.length){a=J(this,a);for(var c=0;c<b.length;c++){var d=zb(b[c]);C(this.a,d.a,d.b)}L(this,a)}};f.Mb=function(a,b){if(null!=b&&b.length){a=J(this,a);for(var c=0;c<b.length;c++)Db(this.a,b[c]);L(this,a)}};
f.Nb=function(a,b){if(null!=b&&b.length){a=J(this,a);for(var c=0;c<b.length;c++){var d=this.a;sb(b[c]);C(d,v,w)}L(this,a)}};f.Ob=function(a,b){if(null!=b&&b.length){a=J(this,a);for(var c=0;c<b.length;c++)I(this.a,vb(b[c]));L(this,a)}};f.Pb=function(a,b){if(null!=b&&b.length){a=J(this,a);for(var c=0;c<b.length;c++)I(this.a,b[c]);L(this,a)}};f.Ab=function(a,b){if(null!=b&&b.length)for(K(this,a,2),F(this.a,4*b.length),a=0;a<b.length;a++)E(this.a,b[a])};
f.Bb=function(a,b){if(null!=b&&b.length)for(K(this,a,2),F(this.a,8*b.length),a=0;a<b.length;a++)Eb(this.a,b[a])};f.Cb=function(a,b){if(null!=b&&b.length)for(K(this,a,2),F(this.a,8*b.length),a=0;a<b.length;a++){var c=zb(b[a]);D(this.a,c.a,c.b)}};f.Jb=function(a,b){if(null!=b&&b.length)for(K(this,a,2),F(this.a,4*b.length),a=0;a<b.length;a++)Fb(this.a,b[a])};f.Kb=function(a,b){if(null!=b&&b.length)for(K(this,a,2),F(this.a,8*b.length),a=0;a<b.length;a++){var c=this.a;x(b[a]);D(c,v,w)}};
f.Lb=function(a,b){if(null!=b&&b.length)for(K(this,a,2),F(this.a,8*b.length),a=0;a<b.length;a++){var c=this.a;y(vb(b[a]));D(c,v,w)}};f.Eb=function(a,b){if(null!=b&&b.length)for(K(this,a,2),F(this.a,4*b.length),a=0;a<b.length;a++){var c=this.a;tb(b[a]);E(c,v)}};f.yb=function(a,b){if(null!=b&&b.length)for(K(this,a,2),F(this.a,8*b.length),a=0;a<b.length;a++)Gb(this.a,b[a])};f.xb=function(a,b){if(null!=b&&b.length)for(K(this,a,2),F(this.a,b.length),a=0;a<b.length;a++)this.a.a.push(b[a]?1:0)};
f.zb=function(a,b){if(null!=b&&b.length){a=J(this,a);for(var c=0;c<b.length;c++)G(this.a,b[c]);L(this,a)}};f.Db=function(a,b){if(null!=b&&b.length)for(K(this,a,2),F(this.a,8*b.length),a=0;a<b.length;a++)Hb(this.a,b[a])};f.Xb=function(a,b){if(null!=b&&b.length){a=J(this,a);for(var c=0;c<b.length;c++){var d=this.a;y(b[c]);C(d,v,w)}L(this,a)}};function Rb(){}var Sb="function"==typeof Uint8Array;Rb.prototype.j=function(){return this.h};var Tb=[];function Ub(a){var b=a.f+a.g;a.c[b]||(a.a=a.c[b]={})}function Vb(a,b){if(b<a.f){b+=a.g;var c=a.c[b];return c===Tb?a.c[b]=[]:c}if(a.a)return c=a.a[b],c===Tb?a.a[b]=[]:c}function N(a,b,c){a=Vb(a,b);return null==a?c:a}function O(a,b){a=Vb(a,b);a=null==a?a:!!a;return null==a?!1:a}function Wb(a,b,c){b<a.f?a.c[b+a.g]=c:(Ub(a),a.a[b]=c);return a}
function P(a,b,c,d){c!==d?Wb(a,b,c):a.c[b+a.g]=null;return a}function Xb(a){if(a.b)for(var b in a.b){var c=a.b[b];if(p(c))for(var d=0;d<c.length;d++)c[d]&&R(c[d]);else c&&R(c)}}function R(a){Xb(a);return a.c}f=Rb.prototype;f.M=Sb?function(){var a=Uint8Array.prototype.toJSON;Uint8Array.prototype.toJSON=function(){return nb(this)};try{return JSON.stringify(this.c&&R(this),Yb)}finally{Uint8Array.prototype.toJSON=a}}:function(){return JSON.stringify(this.c&&R(this),Yb)};
function Yb(a,b){return"number"!==typeof b||!isNaN(b)&&Infinity!==b&&-Infinity!==b?b:String(b)}f.toString=function(){Xb(this);return this.c.toString()};f.Ka=function(a){if(this.a){this.b||(this.b={});var b=a.c;if(a.f){if(a.a())return this.b[b]||(this.b[b]=Ka(this.a[b]||[],function(c){return new a.b(c)})),this.b[b]}else if(a.a())return!this.b[b]&&this.a[b]&&(this.b[b]=new a.b(this.a[b])),this.b[b];return this.a[b]}};
f.$a=function(a,b){this.b||(this.b={});Ub(this);var c=a.c;a.f?(b=b||[],a.a()?(this.b[c]=b,this.a[c]=Ka(b,function(d){return R(d)})):this.a[c]=b):a.a()?(this.b[c]=b,this.a[c]=b?R(b):b):this.a[c]=b;return this};f.W=function(){return new this.constructor(Zb(R(this)))};f.Ja=function(){return new this.constructor(Zb(R(this)))};
function Zb(a){if(p(a)){for(var b=Array(a.length),c=0;c<a.length;c++){var d=a[c];null!=d&&(b[c]="object"==typeof d?Zb(d):d)}return b}if(Sb&&a instanceof Uint8Array)return new Uint8Array(a);b={};for(c in a)d=a[c],null!=d&&(b[c]="object"==typeof d?Zb(d):d);return b};function $b(a){var b=a;a=ac;this.b=null;b||(b=[]);this.h=void 0;this.g=-1;this.c=b;a:{if(b=this.c.length){--b;var c=this.c[b];if(!(null===c||"object"!=typeof c||p(c)||Sb&&c instanceof Uint8Array)){this.f=b- -1;this.a=c;break a}}this.f=Number.MAX_VALUE}this.i={};if(a)for(b=0;b<a.length;b++)c=a[b],c<this.f?(c+=-1,this.c[c]=this.c[c]||Tb):(Ub(this),this.a[c]=this.a[c]||Tb)}Ha($b,Rb);var ac=[10];f=$b.prototype;
f.Wa=function(a){var b,c={mb:N(this,1,0),locale:N(this,2,""),R:N(this,4,""),ja:N(this,5,""),nb:N(this,6,""),Ca:N(this,7,""),Ea:O(this,8),Da:O(this,9),U:null==(b=Vb(this,10))?void 0:b,Fa:O(this,11)};a&&(c.O=this);return c};
f.Ya=function(){var a=new Ib;var b=this.getTenantId();0!==b&&Pb(a,1,b);b=this.getLocale();0<b.length&&M(a,2,b);b=N(this,4,"");0<b.length&&M(a,4,b);b=N(this,5,"");0<b.length&&M(a,5,b);b=N(this,6,"");0<b.length&&M(a,6,b);b=this.getInsecureHost();0<b.length&&M(a,7,b);(b=O(this,8))&&Mb(a,8,b);(b=O(this,9))&&Mb(a,9,b);b=Vb(this,10);if(0<b.length&&null!=b)for(var c=0;c<b.length;c++)M(a,10,b[c]);(b=O(this,11))&&Mb(a,11,b);return Kb(a)};f.getTenantId=function(){return N(this,1,0)};
f.kb=function(a){return P(this,1,a,0)};f.getLocale=function(){return N(this,2,"")};f.Za=function(a){return P(this,4,a,"")};f.bb=function(a){return P(this,5,a,"")};f.lb=function(a){return P(this,6,a,"")};f.getInsecureHost=function(){return N(this,7,"")};f.cb=function(a){return P(this,7,a,"")};f.fb=function(a){return P(this,8,a,!1)};f.eb=function(a){return P(this,9,a,!1)};f.P=function(a,b){var c=Vb(this,10);void 0!=b?c.splice(b,0,a):c.push(a);return this};f.V=function(){return Wb(this,10,[])};
f.gb=function(a){return P(this,11,a,!1)};function bc(){var a=GoogleDevelopersObject;return new $b(a?JSON.parse(a):null)};var cc="StopIteration"in n?n.StopIteration:{message:"StopIteration",stack:""};function dc(){}dc.prototype.next=function(){throw cc;};dc.prototype.a=function(){return this};function ec(a,b){this.b={};this.a=[];this.f=this.c=0;var c=arguments.length;if(1<c){if(c%2)throw Error("Uneven number of arguments");for(var d=0;d<c;d+=2)this.set(arguments[d],arguments[d+1])}else if(a)if(a instanceof ec)for(c=a.m(),d=0;d<c.length;d++)this.set(c[d],a.get(c[d]));else for(d in a)this.set(d,a[d])}f=ec.prototype;f.l=function(){S(this);for(var a=[],b=0;b<this.a.length;b++)a.push(this.b[this.a[b]]);return a};f.m=function(){S(this);return this.a.concat()};
f.ya=function(a){for(var b=0;b<this.a.length;b++){var c=this.a[b];if(T(this.b,c)&&this.b[c]==a)return!0}return!1};f.Z=function(a,b){if(this===a)return!0;if(this.c!=a.c)return!1;b=b||fc;S(this);for(var c,d=0;c=this.a[d];d++)if(!b(this.get(c),a.get(c)))return!1;return!0};function fc(a,b){return a===b}f.za=function(){return 0==this.c};f.xa=function(){this.b={};this.f=this.c=this.a.length=0};
function S(a){if(a.c!=a.a.length){for(var b=0,c=0;b<a.a.length;){var d=a.a[b];T(a.b,d)&&(a.a[c++]=d);b++}a.a.length=c}if(a.c!=a.a.length){var e={};for(c=b=0;b<a.a.length;)d=a.a[b],T(e,d)||(a.a[c++]=d,e[d]=1),b++;a.a.length=c}}f.get=function(a,b){return T(this.b,a)?this.b[a]:b};f.set=function(a,b){T(this.b,a)||(this.c++,this.a.push(a),this.f++);this.b[a]=b};f.forEach=function(a,b){for(var c=this.m(),d=0;d<c.length;d++){var e=c[d],h=this.get(e);a.call(b,h,e,this)}};
f.ob=function(){for(var a=new ec,b=0;b<this.a.length;b++){var c=this.a[b];a.set(this.b[c],c)}return a};f.Aa=function(){S(this);for(var a={},b=0;b<this.a.length;b++){var c=this.a[b];a[c]=this.b[c]}return a};f.da=function(){return gc(this,!0)};f.ia=function(){return gc(this,!1)};function gc(a,b){S(a);var c=0,d=a.f,e=new dc;e.next=function(){if(d!=a.f)throw Error("The map has changed since the iterator was created");if(c>=a.a.length)throw cc;var h=a.a[c++];return b?h:a.b[h]};return e}
function T(a,b){return Object.prototype.hasOwnProperty.call(a,b)};function hc(a){if(a.l&&"function"==typeof a.l)return a.l();if("string"===typeof a)return a.split("");if(Ca(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}b=[];c=0;for(d in a)b[c++]=a[d];return b}
function ic(a,b,c){if(a.forEach&&"function"==typeof a.forEach)a.forEach(b,c);else if(Ca(a)||"string"===typeof a)Ja(a,b,c);else{if(a.m&&"function"==typeof a.m)var d=a.m();else if(a.l&&"function"==typeof a.l)d=void 0;else if(Ca(a)||"string"===typeof a){d=[];for(var e=a.length,h=0;h<e;h++)d.push(h)}else for(h in d=[],e=0,a)d[e++]=h;e=hc(a);h=e.length;for(var g=0;g<h;g++)b.call(c,e[g],d&&d[g],a)}};var jc=/^(?:([^:/?#.]+):)?(?:\/\/(?:([^/?#]*)@)?([^/#?]*?)(?::([0-9]+))?(?=[/\\#?]|$))?([^?#]+)?(?:\?([^#]*))?(?:#([\s\S]*))?$/;function kc(a,b){if(a){a=a.split("&");for(var c=0;c<a.length;c++){var d=a[c].indexOf("="),e=null;if(0<=d){var h=a[c].substring(0,d);e=a[c].substring(d+1)}else h=a[c];b(h,e?decodeURIComponent(e.replace(/\+/g," ")):"")}}};function U(a,b){this.b=this.j=this.h="";this.f=null;this.i=this.c="";this.g=this.o=!1;if(a instanceof U){this.g=void 0!==b?b:a.g;lc(this,a.h);var c=a.j;V(this);this.j=c;c=a.b;V(this);this.b=c;mc(this,a.f);c=a.c;V(this);this.c=c;nc(this,oc(a.a));a=a.i;V(this);this.i=a}else a&&(c=String(a).match(jc))?(this.g=!!b,lc(this,c[1]||"",!0),a=c[2]||"",V(this),this.j=W(a),a=c[3]||"",V(this),this.b=W(a,!0),mc(this,c[4]),a=c[5]||"",V(this),this.c=W(a,!0),nc(this,c[6]||"",!0),a=c[7]||"",V(this),this.i=W(a)):(this.g=
!!b,this.a=new pc(null,this.g))}f=U.prototype;f.toString=function(){var a=[],b=this.h;b&&a.push(qc(b,rc,!0),":");var c=this.b;if(c||"file"==b)a.push("//"),(b=this.j)&&a.push(qc(b,rc,!0),"@"),a.push(encodeURIComponent(String(c)).replace(/%25([0-9a-fA-F]{2})/g,"%$1")),c=this.f,null!=c&&a.push(":",String(c));if(c=this.c)this.b&&"/"!=c.charAt(0)&&a.push("/"),a.push(qc(c,"/"==c.charAt(0)?sc:tc,!0));(c=this.a.toString())&&a.push("?",c);(c=this.i)&&a.push("#",qc(c,uc));return a.join("")};
f.resolve=function(a){var b=new U(this),c=!!a.h;c?lc(b,a.h):c=!!a.j;if(c){var d=a.j;V(b);b.j=d}else c=!!a.b;c?(d=a.b,V(b),b.b=d):c=null!=a.f;d=a.c;if(c)mc(b,a.f);else if(c=!!a.c){if("/"!=d.charAt(0))if(this.b&&!this.c)d="/"+d;else{var e=b.c.lastIndexOf("/");-1!=e&&(d=b.c.substr(0,e+1)+d)}e=d;if(".."==e||"."==e)d="";else if(r(e,"./")||r(e,"/.")){d=0==e.lastIndexOf("/",0);e=e.split("/");for(var h=[],g=0;g<e.length;){var k=e[g++];"."==k?d&&g==e.length&&h.push(""):".."==k?((1<h.length||1==h.length&&""!=
h[0])&&h.pop(),d&&g==e.length&&h.push("")):(h.push(k),d=!0)}d=h.join("/")}else d=e}c?(V(b),b.c=d):c=""!==a.a.toString();c?nc(b,oc(a.a)):c=!!a.i;c&&(a=a.i,V(b),b.i=a);return b};function lc(a,b,c){V(a);a.h=c?W(b,!0):b;a.h&&(a.h=a.h.replace(/:$/,""))}function mc(a,b){V(a);if(b){b=Number(b);if(isNaN(b)||0>b)throw Error("Bad port number "+b);a.f=b}else a.f=null}function nc(a,b,c){V(a);b instanceof pc?(a.a=b,vc(a.a,a.g)):(c||(b=qc(b,wc)),a.a=new pc(b,a.g));return a}f.ib=function(a,b){return nc(this,a,b)};
f.ba=function(){return W(this.a.toString())};f.pa=function(){return this.a.toString()};f.hb=function(a,b){V(this);p(b)||(b=[String(b)]);xc(this.a,a,b);return this};f.ga=function(a){return this.a.l(a)};f.fa=function(a){return this.a.get(a)};f.Ba=function(a){return(!this.b&&!a.b||this.b==a.b)&&(null==this.f&&null==a.f||this.f==a.f)};
f.Ua=function(){V(this);var a=Math.floor(2147483648*Math.random()).toString(36)+Math.abs(Math.floor(2147483648*Math.random())^Fa()).toString(36);V(this);this.a.set("zx",a);return this};f.qa=function(a){V(this);yc(this.a,a);return this};f.jb=function(a){this.o=a;return this};f.Ga=function(){return this.o};function V(a){if(a.o)throw Error("Tried to modify a read-only Uri");}f.ra=function(a){this.g=a;this.a&&vc(this.a,a);return this};
function W(a,b){return a?b?decodeURI(a.replace(/%25/g,"%2525")):decodeURIComponent(a):""}function qc(a,b,c){return"string"===typeof a?(a=encodeURI(a).replace(b,zc),c&&(a=a.replace(/%25([0-9a-fA-F]{2})/g,"%$1")),a):null}function zc(a){a=a.charCodeAt(0);return"%"+(a>>4&15).toString(16)+(a&15).toString(16)}var rc=/[#\/\?@]/g,tc=/[#\?:]/g,sc=/[#\?]/g,wc=/[#\?@]/g,uc=/#/g;function pc(a,b){this.b=this.a=null;this.c=a||null;this.f=!!b}
function X(a){a.a||(a.a=new ec,a.b=0,a.c&&kc(a.c,function(b,c){a.add(decodeURIComponent(b.replace(/\+/g," ")),c)}))}f=pc.prototype;f.na=function(){X(this);return this.b};f.add=function(a,b){X(this);this.c=null;a=Ac(this,a);var c=this.a.get(a);c||this.a.set(a,c=[]);c.push(b);this.b+=1;return this};function yc(a,b){X(a);b=Ac(a,b);T(a.a.b,b)&&(a.c=null,a.b-=a.a.get(b).length,a=a.a,T(a.b,b)&&(delete a.b[b],a.c--,a.f++,a.a.length>2*a.c&&S(a)))}f.ka=function(){this.a=this.c=null;this.b=0};
f.oa=function(){X(this);return 0==this.b};function Bc(a,b){X(a);b=Ac(a,b);return T(a.a.b,b)}f.la=function(a){var b=this.l();return 0<=Ia(b,a)};f.forEach=function(a,b){X(this);this.a.forEach(function(c,d){Ja(c,function(e){a.call(b,e,d,this)},this)},this)};f.m=function(){X(this);for(var a=this.a.l(),b=this.a.m(),c=[],d=0;d<b.length;d++)for(var e=a[d],h=0;h<e.length;h++)c.push(b[d]);return c};
f.l=function(a){X(this);var b=[];if("string"===typeof a)Bc(this,a)&&(b=Oa(b,this.a.get(Ac(this,a))));else{a=this.a.l();for(var c=0;c<a.length;c++)b=Oa(b,a[c])}return b};f.set=function(a,b){X(this);this.c=null;a=Ac(this,a);Bc(this,a)&&(this.b-=this.a.get(a).length);this.a.set(a,[b]);this.b+=1;return this};f.get=function(a,b){if(!a)return b;a=this.l(a);return 0<a.length?String(a[0]):b};function xc(a,b,c){yc(a,b);0<c.length&&(a.c=null,a.a.set(Ac(a,b),Pa(c)),a.b+=c.length)}
f.toString=function(){if(this.c)return this.c;if(!this.a)return"";for(var a=[],b=this.a.m(),c=0;c<b.length;c++){var d=b[c],e=encodeURIComponent(String(d));d=this.l(d);for(var h=0;h<d.length;h++){var g=e;""!==d[h]&&(g+="="+encodeURIComponent(String(d[h])));a.push(g)}}return this.c=a.join("&")};f.$=function(a){X(this);this.a.forEach(function(b,c){0<=Ia(a,c)||yc(this,c)},this);return this};function oc(a){var b=new pc;b.c=a.c;a.a&&(b.a=new ec(a.a),b.b=a.b);return b}
function Ac(a,b){b=String(b);a.f&&(b=b.toLowerCase());return b}function vc(a,b){b&&!a.f&&(X(a),a.c=null,a.a.forEach(function(c,d){var e=d.toLowerCase();d!=e&&(yc(this,d),xc(this,e,c))},a));a.f=b}f.ma=function(a){for(var b=0;b<arguments.length;b++)ic(arguments[b],function(c,d){this.add(d,c)},this)};var Cc={};function Dc(a,b){var c=Cc[a];if(void 0!==c&&(!c.H||Date.now()<=c.H+3E5))return c.p;c=new Promise(function(e,h){b.onload=function(){return e(b)};b.onerror=function(g){b.parentNode&&b.parentNode.removeChild(b);h(g)};document.head.appendChild(b)});var d={H:0,p:c};c.catch(function(){return d.H=+new Date});Cc[a]=d;return c}
function Ec(a){var b=void 0===b?null:b;a=a instanceof U?new U(a):new U(a,void 0);var c=document.createElement("script");c.src=a.toString();b&&(c.type=b);return Dc(a.toString(),c)};var Fc=!u||9<=Number(jb),Gc=!u||9<=Number(jb),Hc;
if(Hc=u){var Ic;if(Object.prototype.hasOwnProperty.call(ib,"9"))Ic=ib["9"];else{for(var Jc=0,Kc=Ra(String(hb)).split("."),Lc=Ra("9").split("."),Mc=Math.max(Kc.length,Lc.length),Nc=0;0==Jc&&Nc<Mc;Nc++){var Oc=Kc[Nc]||"",Pc=Lc[Nc]||"";do{var Qc=/(\d*)(\D*)(.*)/.exec(Oc)||["","","",""],Rc=/(\d*)(\D*)(.*)/.exec(Pc)||["","","",""];if(0==Qc[0].length&&0==Rc[0].length)break;Jc=Sa(0==Qc[1].length?0:parseInt(Qc[1],10),0==Rc[1].length?0:parseInt(Rc[1],10))||Sa(0==Qc[2].length,0==Rc[2].length)||Sa(Qc[2],Rc[2]);
Oc=Qc[3];Pc=Rc[3]}while(0==Jc)}Ic=ib["9"]=0<=Jc}Hc=!Ic}var Sc=Hc,Tc=function(){if(!n.addEventListener||!Object.defineProperty)return!1;var a=!1,b=Object.defineProperty({},"passive",{get:function(){a=!0}});try{n.addEventListener("test",Aa,b),n.removeEventListener("test",Aa,b)}catch(c){}return a}();function Uc(){this.s=this.s;this.b=this.b}f=Uc.prototype;f.s=!1;f.N=function(){return this.s};f.ca=Uc.prototype.N;f.C=function(){this.s||(this.s=!0,this.D())};f.Xa=function(a){a=Ea(Vc,a);this.s?a():(this.b||(this.b=[]),this.b.push(a))};f.D=function(){if(this.b)for(;this.b.length;)this.b.shift()()};function Vc(a){a&&"function"==typeof a.C&&a.C()};function Wc(a,b){this.type=a;this.b=this.target=b;this.G=this.f=!1}Wc.prototype.g=function(){this.f=!0};Wc.prototype.c=function(){this.G=!0};function Y(a,b){Wc.call(this,a?a.type:"");this.relatedTarget=this.b=this.target=null;this.button=this.screenY=this.screenX=this.clientY=this.clientX=this.o=this.j=0;this.key="";this.h=this.i=0;this.metaKey=this.shiftKey=this.altKey=this.ctrlKey=!1;this.F=null;this.I=!1;this.pointerId=0;this.pointerType="";this.a=null;if(a){var c=this.type=a.type,d=a.changedTouches&&a.changedTouches.length?a.changedTouches[0]:null;this.target=a.target||a.srcElement;this.b=b;if(b=a.relatedTarget){if($a){a:{try{Xa(b.nodeName);
var e=!0;break a}catch(h){}e=!1}e||(b=null)}}else"mouseover"==c?b=a.fromElement:"mouseout"==c&&(b=a.toElement);this.relatedTarget=b;d?(this.clientX=void 0!==d.clientX?d.clientX:d.pageX,this.clientY=void 0!==d.clientY?d.clientY:d.pageY,this.screenX=d.screenX||0,this.screenY=d.screenY||0):(this.j=ab||void 0!==a.offsetX?a.offsetX:a.layerX,this.o=ab||void 0!==a.offsetY?a.offsetY:a.layerY,this.clientX=void 0!==a.clientX?a.clientX:a.pageX,this.clientY=void 0!==a.clientY?a.clientY:a.pageY,this.screenX=a.screenX||
0,this.screenY=a.screenY||0);this.button=a.button;this.i=a.keyCode||0;this.key=a.key||"";this.h=a.charCode||("keypress"==c?a.keyCode:0);this.ctrlKey=a.ctrlKey;this.altKey=a.altKey;this.shiftKey=a.shiftKey;this.metaKey=a.metaKey;this.I=bb?a.metaKey:a.ctrlKey;this.pointerId=a.pointerId||0;this.pointerType="string"===typeof a.pointerType?a.pointerType:Xc[a.pointerType]||"";this.F=a.state;this.a=a;a.defaultPrevented&&this.c()}}Ha(Y,Wc);var Yc=[1,4,2],Xc={2:"touch",3:"pen",4:"mouse"};
Y.prototype.pb=function(){return(Fc?0==this.a.button:"click"==this.type?!0:!!(this.a.button&Yc[0]))&&!(ab&&bb&&this.ctrlKey)};Y.prototype.g=function(){Y.J.g.call(this);this.a.stopPropagation?this.a.stopPropagation():this.a.cancelBubble=!0};Y.prototype.c=function(){Y.J.c.call(this);var a=this.a;if(a.preventDefault)a.preventDefault();else if(a.returnValue=!1,Sc)try{if(a.ctrlKey||112<=a.keyCode&&123>=a.keyCode)a.keyCode=-1}catch(b){}};var Zc="closure_listenable_"+(1E6*Math.random()|0),$c=0;function ad(a,b,c,d,e){this.listener=a;this.a=null;this.src=b;this.type=c;this.capture=!!d;this.b=e;this.key=++$c;this.v=this.B=!1}function bd(a){a.v=!0;a.listener=null;a.a=null;a.src=null;a.b=null};function cd(a){this.src=a;this.a={};this.b=0}f=cd.prototype;f.ta=function(){var a=0,b;for(b in this.a)a+=this.a[b].length;return a};f.add=function(a,b,c,d,e){var h=a.toString();a=this.a[h];a||(a=this.a[h]=[],this.b++);var g=dd(a,b,d,e);-1<g?(b=a[g],c||(b.B=!1)):(b=new ad(b,this.src,h,!!d,e),b.B=c,a.push(b));return b};
f.va=function(a,b,c,d){a=a.toString();if(!(a in this.a))return!1;var e=this.a[a];b=dd(e,b,c,d);return-1<b?(bd(e[b]),Array.prototype.splice.call(e,b,1),0==e.length&&(delete this.a[a],this.b--),!0):!1};f.wa=function(a){a=a&&a.toString();var b=0,c;for(c in this.a)if(!a||c==a){for(var d=this.a[c],e=0;e<d.length;e++)++b,bd(d[e]);delete this.a[c];this.b--}return b};f.ea=function(a,b){a=this.a[a.toString()];var c=[];if(a)for(var d=0;d<a.length;++d){var e=a[d];e.capture==b&&c.push(e)}return c};
f.ua=function(a,b){var c=void 0!==a,d=c?a.toString():"",e=void 0!==b;return Wa(this.a,function(h){for(var g=0;g<h.length;++g)if(!(c&&h[g].type!=d||e&&h[g].capture!=b))return!0;return!1})};function dd(a,b,c,d){for(var e=0;e<a.length;++e){var h=a[e];if(!h.v&&h.listener==b&&h.capture==!!c&&h.b==d)return e}return-1};var ed="closure_lm_"+(1E6*Math.random()|0),fd={},gd=0;function hd(a,b,c,d,e){if(d&&d.once)return id(a,b,c,d,e);if(p(b)){for(var h=0;h<b.length;h++)hd(a,b[h],c,d,e);return null}c=jd(c);return a&&a[Zc]?kd(a,b,c,Da(d)?!!d.capture:!!d,e):ld(a,b,c,!1,d,e)}
function ld(a,b,c,d,e,h){if(!b)throw Error("Invalid event type");var g=Da(e)?!!e.capture:!!e,k=md(a);k||(a[ed]=k=new cd(a));c=k.add(b,c,d,g,h);if(c.a)return c;d=nd();c.a=d;d.src=a;d.listener=c;if(a.addEventListener)Tc||(e=g),void 0===e&&(e=!1),a.addEventListener(b.toString(),d,e);else if(a.attachEvent)a.attachEvent(od(b.toString()),d);else if(a.addListener&&a.removeListener)a.addListener(d);else throw Error("addEventListener and attachEvent are unavailable.");gd++;return c}
function nd(){var a=pd,b=Gc?function(c){return a.call(b.src,b.listener,c)}:function(c){c=a.call(b.src,b.listener,c);if(!c)return c};return b}function id(a,b,c,d,e){if(p(b)){for(var h=0;h<b.length;h++)id(a,b[h],c,d,e);return null}c=jd(c);return a&&a[Zc]?a.b(b,c,Da(d)?!!d.capture:!!d,e):ld(a,b,c,!0,d,e)}
function qd(a){if("number"!==typeof a&&a&&!a.v){var b=a.src;if(b&&b[Zc])b.c(a);else{var c=a.type,d=a.a;b.removeEventListener?b.removeEventListener(c,d,a.capture):b.detachEvent?b.detachEvent(od(c),d):b.addListener&&b.removeListener&&b.removeListener(d);gd--;if(c=md(b)){d=a.type;if(d in c.a){var e=c.a[d],h=Ia(e,a),g;(g=0<=h)&&Array.prototype.splice.call(e,h,1);g&&(bd(a),0==c.a[d].length&&(delete c.a[d],c.b--))}0==c.b&&(c.src=null,b[ed]=null)}else bd(a)}}}
function od(a){return a in fd?fd[a]:fd[a]="on"+a}function rd(a,b,c,d){var e=!0;if(a=md(a))if(b=a.a[b.toString()])for(b=b.concat(),a=0;a<b.length;a++){var h=b[a];h&&h.capture==c&&!h.v&&(h=sd(h,d),e=e&&!1!==h)}return e}function sd(a,b){var c=a.listener,d=a.b||a.src;a.B&&qd(a);return c.call(d,b)}
function pd(a,b){if(a.v)return!0;if(!Gc){var c=b||za("window.event");b=new Y(c,this);var d=!0;if(!(0>c.keyCode||void 0!=c.returnValue)){a:{var e=!1;if(0==c.keyCode)try{c.keyCode=-1;break a}catch(g){e=!0}if(e||void 0==c.returnValue)c.returnValue=!0}c=[];for(e=b.b;e;e=e.parentNode)c.push(e);a=a.type;for(e=c.length-1;!b.f&&0<=e;e--){b.b=c[e];var h=rd(c[e],a,!0,b);d=d&&h}for(e=0;!b.f&&e<c.length;e++)b.b=c[e],h=rd(c[e],a,!1,b),d=d&&h}return d}return sd(a,new Y(b,this))}
function md(a){a=a[ed];return a instanceof cd?a:null}var td="__closure_events_fn_"+(1E9*Math.random()>>>0);function jd(a){if("function"==Ba(a))return a;a[td]||(a[td]=function(b){return a.handleEvent(b)});return a[td]};function ud(a){Uc.call(this);this.c=a;this.a={}}Ha(ud,Uc);var vd=[];f=ud.prototype;f.Qa=function(a,b,c,d,e){return kd(this,a,b,c,d,e)};function kd(a,b,c,d,e,h){p(c)||(c&&(vd[0]=c.toString()),c=vd);for(var g=0;g<c.length;g++){var k=hd(b,c[g],d||a.handleEvent,e||!1,h||a.c||a);if(!k)break;a.a[k.key]=k}return a}function wd(a,b){xd(Z.b,a,"devsite-content-updated",b,void 0)}f.Pa=function(a,b,c,d,e){return xd(this,a,b,c,d,e)};
function xd(a,b,c,d,e,h){if(p(c))for(var g=0;g<c.length;g++)xd(a,b,c[g],d,e,h);else{b=id(b,c,d||a.handleEvent,e,h||a.c||a);if(!b)return a;a.a[b.key]=b}return a}f.Ra=function(a,b,c,d){kd(b,a,c,d,this.c||this);return this};f.Sa=function(a,b,c,d,e){kd(b,a,c,d,e||this.c||this);return this};f.sa=function(){var a=0,b;for(b in this.a)Object.prototype.hasOwnProperty.call(this.a,b)&&a++;return a};
function yd(a,b,c,d,e,h){if(p(c))for(var g=0;g<c.length;g++)yd(a,b,c[g],d,e,h);else d=d||a.handleEvent,e=Da(e)?!!e.capture:!!e,h=h||a.c||a,d=jd(d),e=!!e,b&&b[Zc]?c=b.a(c,d,e,h):b?(b=md(b))?(c=b.a[c.toString()],b=-1,c&&(b=dd(c,d,e,h)),c=-1<b?c[b]:null):c=null:c=null,c&&(qd(c),delete a.a[c.key])}f.qb=function(a,b,c,d,e){yd(b,a,c,d,e||this.c||this,this);return this};function zd(a){Va(a.a,function(b,c){this.a.hasOwnProperty(c)&&qd(b)},a);a.a={}}f.D=function(){ud.J.D.call(this);zd(this)};
f.handleEvent=function(){throw Error("EventHandler.handleEvent not implemented");};function Ad(){var a=this;if(za("__globalAppLoader"))return za("__globalAppLoader");this.c=null;this.h=!1;this.b=new ud;this.f=[];this.g=function(b){a.f.push(b)};try{this.a=bc()}catch(b){Bd("GoogleDevelopersObject missing or invalid")}GoogleDevelopersObject=null;Ga("__globalAppLoader",this)}Ad.prototype.C=function(){zd(this.b)};
function Cd(a){var b=[];b.push(Ec(N(a.a,5,"")+"/js/webcomponents-lite.js"));"fetch"in window&&"URL"in window||b.push(Ec(N(a.a,5,"")+"/js/polyfills.js"));return Promise.all(b)}
function Dd(){var a=Ed,b,c,d,e,h;return ya(new xa(new ta(function(g){switch(g.a){case 1:return u&&document.body.setAttribute("ie-"+parseInt(hb,10),""),g.c=2,pa(g,Cd(a),4);case 4:qa(g,3);break;case 2:b=ra(g),Bd("Failed to load Devsite App dependencies: "+b.message);case 3:return c=new Promise(function(k){Ga("__devsiteAppReadyResolver",k)}),Ga("__devsiteAppReadyPromise",c),Ga("DevsiteApp.whenReady",function(){return c}),g.c=5,pa(g,Ec(N(a.a,6,"")+(a.a.getLocale()&&"en"!=a.a.getLocale()?N(a.a,4,"").replace(/\.js$/,
"__"+a.a.getLocale().toLowerCase().replace("-","_")+".js"):N(a.a,4,""))),7);case 7:qa(g,6);break;case 5:d=ra(g);if("en"===a.a.getLocale()){Bd("Failed to load Devsite App binary: "+d.message);g.u(6);break}P(a.a,2,"en","");g.c=9;return pa(g,Ec(N(a.a,6,"")+N(a.a,4,"")),11);case 11:qa(g,6);break;case 9:e=ra(g),Bd("Failed to load Devsite App binary: "+e.message);case 6:if(h=document,"complete"===h.readyState)g.u(0);else return pa(g,new Promise(function(k){h.addEventListener("readystatechange",function(){"complete"===
h.readyState&&k()})}),0)}})))}function Bd(a){throw new function(b){this.message=b;this.name="DevsiteAppLoaderException"}(void 0===a?"Devsite has failed to load.":a);};var Z=new Ad;(function(){var a=document.querySelector("devsite-content");a&&(kd(Z.b,window,"message",Z.g,void 0),wd(a,function(){yd(Z.b,window,"message",Z.g);for(var b=ba(Z.f),c=b.next();!c.done;c=b.next())window.dispatchEvent(c.value.a);Z.f=[]}))})();var Fd;var Ed=Z;"WeakMap"in window&&"performance"in window&&"now"in window.performance?(Ed.c||(Ed.c=Dd()),Fd=Ed.c):Fd=Promise.resolve();
Fd.then(function(){za("DevsiteAppInit")||Bd("Failed to load Devsite App binary");O(Z.a,9)?DevsiteAppFrameboxInit(Z.a.M(),DevsiteAppAuthorizedElements):DevsiteAppInit(Z.a.M(),DevsiteAppAuthorizedElements,DevsiteAppCoreElements)});}).call(this);
