(function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
'use strict';var g,aa="function"==typeof Object.create?Object.create:function(a){function b(){}b.prototype=a;return new b},ba;if("function"==typeof Object.setPrototypeOf)ba=Object.setPrototypeOf;else{var ca;a:{var da={I:!0},ea={};try{ea.__proto__=da;ca=ea.I;break a}catch(a){}ca=!1}ba=ca?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var fa=ba;
function ha(a,b){a.prototype=aa(b.prototype);a.prototype.constructor=a;if(fa)fa(a,b);else for(var c in b)if("prototype"!=c)if(Object.defineProperties){var d=Object.getOwnPropertyDescriptor(b,c);d&&Object.defineProperty(a,c,d)}else a[c]=b[c];a.j=b.prototype}function ia(a){a=["object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global,a];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}return globalThis}
var ja=ia(this),ka="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)};function l(a,b){if(b){var c=ja;a=a.split(".");for(var d=0;d<a.length-1;d++){var e=a[d];e in c||(c[e]={});c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&ka(c,a,{configurable:!0,writable:!0,value:b})}}l("globalThis",function(a){return a||ja});
var la=function(){function a(){function c(){}new c;Reflect.construct(c,[],function(){});return new c instanceof c}if("undefined"!=typeof Reflect&&Reflect.construct){if(a())return Reflect.construct;var b=Reflect.construct;return function(c,d,e){c=b(c,d);e&&Reflect.setPrototypeOf(c,e.prototype);return c}}return function(c,d,e){void 0===e&&(e=c);e=aa(e.prototype||Object.prototype);return Function.prototype.apply.call(c,e,d)||e}}();l("Reflect.construct",function(){return la});
l("Object.setPrototypeOf",function(a){return a||fa});l("Array.from",function(a){return a?a:function(b,c,d){c=null!=c?c:function(k){return k};var e=[],f="undefined"!=typeof Symbol&&Symbol.iterator&&b[Symbol.iterator];if("function"==typeof f){b=f.call(b);for(var h=0;!(f=b.next()).done;)e.push(c.call(d,f.value,h++))}else for(f=b.length,h=0;h<f;h++)e.push(c.call(d,b[h],h));return e}});var m=this||self;function n(){}
function p(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b}function q(a){return"array"==p(a)}function ma(a){var b=p(a);return"array"==b||"object"==b&&"number"==typeof a.length}function r(a){var b=typeof a;return"object"==b&&null!=a||"function"==b}function na(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var d=c.slice();d.push.apply(d,arguments);return a.apply(this,d)}}
function oa(a,b){function c(){}c.prototype=b.prototype;a.j=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.U=function(d,e,f){for(var h=Array(arguments.length-2),k=2;k<arguments.length;k++)h[k-2]=arguments[k];return b.prototype[e].apply(d,h)}};var pa;var qa=Array.prototype.indexOf?function(a,b){return Array.prototype.indexOf.call(a,b,void 0)}:function(a,b){if("string"===typeof a)return"string"!==typeof b||1!=b.length?-1:a.indexOf(b,0);for(var c=0;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},ra=Array.prototype.forEach?function(a,b){Array.prototype.forEach.call(a,b,void 0)}:function(a,b){for(var c=a.length,d="string"===typeof a?a.split(""):a,e=0;e<c;e++)e in d&&b.call(void 0,d[e],e,a)},sa=Array.prototype.filter?function(a,b){return Array.prototype.filter.call(a,
b,void 0)}:function(a,b){for(var c=a.length,d=[],e=0,f="string"===typeof a?a.split(""):a,h=0;h<c;h++)if(h in f){var k=f[h];b.call(void 0,k,h,a)&&(d[e++]=k)}return d};function ta(a){var b=a.length;if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]};var ua=String.prototype.trim?function(a){return a.trim()}:function(a){return/^[\s\xa0]*([\s\S]*?)[\s\xa0]*$/.exec(a)[1]};
function va(a,b){if(b)a=a.replace(wa,"&amp;").replace(xa,"&lt;").replace(ya,"&gt;").replace(za,"&quot;").replace(Aa,"&#39;").replace(Ba,"&#0;");else{if(!Ca.test(a))return a;-1!=a.indexOf("&")&&(a=a.replace(wa,"&amp;"));-1!=a.indexOf("<")&&(a=a.replace(xa,"&lt;"));-1!=a.indexOf(">")&&(a=a.replace(ya,"&gt;"));-1!=a.indexOf('"')&&(a=a.replace(za,"&quot;"));-1!=a.indexOf("'")&&(a=a.replace(Aa,"&#39;"));-1!=a.indexOf("\x00")&&(a=a.replace(Ba,"&#0;"))}return a}
var wa=/&/g,xa=/</g,ya=/>/g,za=/"/g,Aa=/'/g,Ba=/\x00/g,Ca=/[\x00&<>"']/;function Da(a,b){return a<b?-1:a>b?1:0};var t;a:{var Ea=m.navigator;if(Ea){var Fa=Ea.userAgent;if(Fa){t=Fa;break a}}t=""};function Ga(a,b,c){for(var d in a)b.call(c,a[d],d,a)}function Ha(a,b){for(var c in a)if(b.call(void 0,a[c],c,a))return!0;return!1}var Ia="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" ");function Ja(a,b){for(var c,d,e=1;e<arguments.length;e++){d=arguments[e];for(c in d)a[c]=d[c];for(var f=0;f<Ia.length;f++)c=Ia[f],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}};function u(a){this.b=Ka===Ka&&a||"";this.c=La}u.prototype.u=!0;u.prototype.o=function(){return this.b.toString()};u.prototype.C=!0;u.prototype.a=function(){return 1};var La={},Ka={};function v(){this.b="";this.f=Ma;this.c=null}v.prototype.C=!0;v.prototype.a=function(){return this.c};v.prototype.u=!0;v.prototype.o=function(){return this.b.toString()};function w(a){return a instanceof v&&a.constructor===v&&a.f===Ma?a.b:"type_error:SafeHtml"}function x(a){if(a instanceof v)return a;var b="object"==typeof a,c=null;b&&a.C&&(c=a.a());a=va(b&&a.u?a.o():String(a));return y(a,c)}
function Na(a){function b(f){q(f)?ra(f,b):(f=x(f),e.push(w(f).toString()),f=f.a(),0==d?d=f:0!=f&&d!=f&&(d=null))}var c=x(Oa),d=c.a(),e=[];ra(a,b);return y(e.join(w(c).toString()),d)}function Pa(a){return Na(Array.prototype.slice.call(arguments))}var Ma={};function y(a,b){var c=new v;c.b=a;c.c=b;return c}y("<!DOCTYPE html>",0);var Oa=y("",0),Qa=y("<br>",0);var Ra=function(a){var b=!1,c;return function(){b||(c=a(),b=!0);return c}}(function(){var a=document.createElement("div"),b=document.createElement("div");b.appendChild(document.createElement("div"));a.appendChild(b);b=a.firstChild.firstChild;a.innerHTML=w(Oa);return!b.parentElement});function z(a,b){if(Ra())for(;a.lastChild;)a.removeChild(a.lastChild);a.innerHTML=w(b)};function Sa(a){return a=va(a,void 0)};function Ta(a){Ta[" "](a);return a}Ta[" "]=n;function Ua(a,b){var c=Va;return Object.prototype.hasOwnProperty.call(c,a)?c[a]:c[a]=b(a)};var Wa=-1!=t.indexOf("Opera"),A=-1!=t.indexOf("Trident")||-1!=t.indexOf("MSIE"),Xa=-1!=t.indexOf("Edge"),B=-1!=t.indexOf("Gecko")&&!(-1!=t.toLowerCase().indexOf("webkit")&&-1==t.indexOf("Edge"))&&!(-1!=t.indexOf("Trident")||-1!=t.indexOf("MSIE"))&&-1==t.indexOf("Edge"),C=-1!=t.toLowerCase().indexOf("webkit")&&-1==t.indexOf("Edge"),Ya=-1!=t.indexOf("Macintosh");function Za(){var a=m.document;return a?a.documentMode:void 0}var $a;
a:{var ab="",bb=function(){var a=t;if(B)return/rv:([^\);]+)(\)|;)/.exec(a);if(Xa)return/Edge\/([\d\.]+)/.exec(a);if(A)return/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/.exec(a);if(C)return/WebKit\/(\S+)/.exec(a);if(Wa)return/(?:Version)[ \/]?(\S+)/.exec(a)}();bb&&(ab=bb?bb[1]:"");if(A){var cb=Za();if(null!=cb&&cb>parseFloat(ab)){$a=String(cb);break a}}$a=ab}var db=$a,Va={};
function D(a){return Ua(a,function(){for(var b=0,c=ua(String(db)).split("."),d=ua(String(a)).split("."),e=Math.max(c.length,d.length),f=0;0==b&&f<e;f++){var h=c[f]||"",k=d[f]||"";do{h=/(\d*)(\D*)(.*)/.exec(h)||["","","",""];k=/(\d*)(\D*)(.*)/.exec(k)||["","","",""];if(0==h[0].length&&0==k[0].length)break;b=Da(0==h[1].length?0:parseInt(h[1],10),0==k[1].length?0:parseInt(k[1],10))||Da(0==h[2].length,0==k[2].length)||Da(h[2],k[2]);h=h[3];k=k[3]}while(0==b)}return 0<=b})}var E;E=m.document&&A?Za():void 0;var eb=!A||9<=Number(E),fb=!A||9<=Number(E),gb=A&&!D("9"),hb=function(){if(!m.addEventListener||!Object.defineProperty)return!1;var a=!1,b=Object.defineProperty({},"passive",{get:function(){a=!0}});try{m.addEventListener("test",n,b),m.removeEventListener("test",n,b)}catch(c){}return a}();function F(){this.g=this.g;this.b=this.b}g=F.prototype;g.g=!1;g.M=function(){return this.g};g.ia=F.prototype.M;g.w=function(){this.g||(this.g=!0,this.m())};g.vb=function(a){a=na(ib,a);this.g?a():(this.b||(this.b=[]),this.b.push(a))};g.m=function(){if(this.b)for(;this.b.length;)this.b.shift()()};function ib(a){a&&"function"==typeof a.w&&a.w()};function G(a,b){this.type=a;this.b=this.target=b;this.O=this.f=!1}G.prototype.s=function(){this.f=!0};G.prototype.c=function(){this.O=!0};function H(a,b){G.call(this,a?a.type:"");this.relatedTarget=this.b=this.target=null;this.button=this.screenY=this.screenX=this.clientY=this.clientX=this.G=this.F=0;this.key="";this.B=this.D=0;this.metaKey=this.shiftKey=this.altKey=this.ctrlKey=!1;this.H=null;this.P=!1;this.pointerId=0;this.pointerType="";this.a=null;if(a){var c=this.type=a.type,d=a.changedTouches&&a.changedTouches.length?a.changedTouches[0]:null;this.target=a.target||a.srcElement;this.b=b;if(b=a.relatedTarget){if(B){a:{try{Ta(b.nodeName);
var e=!0;break a}catch(f){}e=!1}e||(b=null)}}else"mouseover"==c?b=a.fromElement:"mouseout"==c&&(b=a.toElement);this.relatedTarget=b;d?(this.clientX=void 0!==d.clientX?d.clientX:d.pageX,this.clientY=void 0!==d.clientY?d.clientY:d.pageY,this.screenX=d.screenX||0,this.screenY=d.screenY||0):(this.F=C||void 0!==a.offsetX?a.offsetX:a.layerX,this.G=C||void 0!==a.offsetY?a.offsetY:a.layerY,this.clientX=void 0!==a.clientX?a.clientX:a.pageX,this.clientY=void 0!==a.clientY?a.clientY:a.pageY,this.screenX=a.screenX||
0,this.screenY=a.screenY||0);this.button=a.button;this.D=a.keyCode||0;this.key=a.key||"";this.B=a.charCode||("keypress"==c?a.keyCode:0);this.ctrlKey=a.ctrlKey;this.altKey=a.altKey;this.shiftKey=a.shiftKey;this.metaKey=a.metaKey;this.P=Ya?a.metaKey:a.ctrlKey;this.pointerId=a.pointerId||0;this.pointerType="string"===typeof a.pointerType?a.pointerType:jb[a.pointerType]||"";this.H=a.state;this.a=a;a.defaultPrevented&&this.c()}}oa(H,G);var kb=[1,4,2],jb={2:"touch",3:"pen",4:"mouse"};
H.prototype.Pb=function(){return(eb?0==this.a.button:"click"==this.type?!0:!!(this.a.button&kb[0]))&&!(C&&Ya&&this.ctrlKey)};H.prototype.s=function(){H.j.s.call(this);this.a.stopPropagation?this.a.stopPropagation():this.a.cancelBubble=!0};H.prototype.c=function(){H.j.c.call(this);var a=this.a;if(a.preventDefault)a.preventDefault();else if(a.returnValue=!1,gb)try{if(a.ctrlKey||112<=a.keyCode&&123>=a.keyCode)a.keyCode=-1}catch(b){}};H.prototype.Ob=function(){return this.a};var I="closure_listenable_"+(1E6*Math.random()|0),lb=0;function mb(a,b,c,d,e){this.listener=a;this.a=null;this.src=b;this.type=c;this.capture=!!d;this.b=e;this.key=++lb;this.i=this.l=!1}function J(a){a.i=!0;a.listener=null;a.a=null;a.src=null;a.b=null};function nb(a){this.src=a;this.a={};this.b=0}g=nb.prototype;g.Wa=function(){var a=0,b;for(b in this.a)a+=this.a[b].length;return a};g.add=function(a,b,c,d,e){var f=a.toString();a=this.a[f];a||(a=this.a[f]=[],this.b++);var h=ob(a,b,d,e);-1<h?(b=a[h],c||(b.l=!1)):(b=new mb(b,this.src,f,!!d,e),b.l=c,a.push(b));return b};
g.Ya=function(a,b,c,d){a=a.toString();if(!(a in this.a))return!1;var e=this.a[a];b=ob(e,b,c,d);return-1<b?(J(e[b]),Array.prototype.splice.call(e,b,1),0==e.length&&(delete this.a[a],this.b--),!0):!1};g.Za=function(a){a=a&&a.toString();var b=0,c;for(c in this.a)if(!a||c==a){for(var d=this.a[c],e=0;e<d.length;e++)++b,J(d[e]);delete this.a[c];this.b--}return b};g.wa=function(a,b){a=this.a[a.toString()];var c=[];if(a)for(var d=0;d<a.length;++d){var e=a[d];e.capture==b&&c.push(e)}return c};
g.Xa=function(a,b){var c=void 0!==a,d=c?a.toString():"",e=void 0!==b;return Ha(this.a,function(f){for(var h=0;h<f.length;++h)if(!(c&&f[h].type!=d||e&&f[h].capture!=b))return!0;return!1})};function ob(a,b,c,d){for(var e=0;e<a.length;++e){var f=a[e];if(!f.i&&f.listener==b&&f.capture==!!c&&f.b==d)return e}return-1};var pb="closure_lm_"+(1E6*Math.random()|0),qb={},rb=0;function sb(a,b,c,d,e){if(d&&d.once)return tb(a,b,c,d,e);if(q(b)){for(var f=0;f<b.length;f++)sb(a,b[f],c,d,e);return null}c=ub(c);return a&&a[I]?K(a,b,c,r(d)?!!d.capture:!!d,e):vb(a,b,c,!1,d,e)}
function vb(a,b,c,d,e,f){if(!b)throw Error("Invalid event type");var h=r(e)?!!e.capture:!!e,k=L(a);k||(a[pb]=k=new nb(a));c=k.add(b,c,d,h,f);if(c.a)return c;d=wb();c.a=d;d.src=a;d.listener=c;if(a.addEventListener)hb||(e=h),void 0===e&&(e=!1),a.addEventListener(b.toString(),d,e);else if(a.attachEvent)a.attachEvent(xb(b.toString()),d);else if(a.addListener&&a.removeListener)a.addListener(d);else throw Error("addEventListener and attachEvent are unavailable.");rb++;return c}
function wb(){var a=yb,b=fb?function(c){return a.call(b.src,b.listener,c)}:function(c){c=a.call(b.src,b.listener,c);if(!c)return c};return b}function tb(a,b,c,d,e){if(q(b)){for(var f=0;f<b.length;f++)tb(a,b[f],c,d,e);return null}c=ub(c);return a&&a[I]?a.D(b,c,r(d)?!!d.capture:!!d,e):vb(a,b,c,!0,d,e)}
function zb(a){if("number"!==typeof a&&a&&!a.i){var b=a.src;if(b&&b[I])b.a(a);else{var c=a.type,d=a.a;b.removeEventListener?b.removeEventListener(c,d,a.capture):b.detachEvent?b.detachEvent(xb(c),d):b.addListener&&b.removeListener&&b.removeListener(d);rb--;if(c=L(b)){d=a.type;if(d in c.a){var e=c.a[d],f=qa(e,a),h;(h=0<=f)&&Array.prototype.splice.call(e,f,1);h&&(J(a),0==c.a[d].length&&(delete c.a[d],c.b--))}0==c.b&&(c.src=null,b[pb]=null)}else J(a)}}}
function xb(a){return a in qb?qb[a]:qb[a]="on"+a}function Ab(a,b,c,d){var e=!0;if(a=L(a))if(b=a.a[b.toString()])for(b=b.concat(),a=0;a<b.length;a++){var f=b[a];f&&f.capture==c&&!f.i&&(f=Bb(f,d),e=e&&!1!==f)}return e}function Bb(a,b){var c=a.listener,d=a.b||a.src;a.l&&zb(a);return c.call(d,b)}
function yb(a,b){if(a.i)return!0;if(!fb){if(!b)a:{b=["window","event"];for(var c=m,d=0;d<b.length;d++)if(c=c[b[d]],null==c){b=null;break a}b=c}d=b;b=new H(d,this);c=!0;if(!(0>d.keyCode||void 0!=d.returnValue)){a:{var e=!1;if(0==d.keyCode)try{d.keyCode=-1;break a}catch(h){e=!0}if(e||void 0==d.returnValue)d.returnValue=!0}d=[];for(e=b.b;e;e=e.parentNode)d.push(e);a=a.type;for(e=d.length-1;!b.f&&0<=e;e--){b.b=d[e];var f=Ab(d[e],a,!0,b);c=c&&f}for(e=0;!b.f&&e<d.length;e++)b.b=d[e],f=Ab(d[e],a,!1,b),c=
c&&f}return c}return Bb(a,new H(b,this))}function L(a){a=a[pb];return a instanceof nb?a:null}var Cb="__closure_events_fn_"+(1E9*Math.random()>>>0);function ub(a){if("function"==p(a))return a;a[Cb]||(a[Cb]=function(b){return a.handleEvent(b)});return a[Cb]};var Db={},Eb={};function M(){throw Error("Do not instantiate directly");}M.prototype.a=null;M.prototype.toString=function(){return this.A};function Fb(a){if(a.h!==Db)throw Error("Sanitized content was not of kind HTML.");return y(a.toString(),a.a||null)}M.prototype.b=function(){if(this.h!==Eb)throw Error("Sanitized content was not of kind URI.");return new u(this.toString())};function Gb(){M.call(this)}oa(Gb,M);Gb.prototype.h=Db;var Hb=function(a){function b(c){this.A=c}b.prototype=a.prototype;return function(c,d){c=new b(String(c));void 0!==d&&(c.a=d);return c}}(Gb);function Ib(a){null!=a&&a.h===Db?(a=String(a.A).replace(Jb,"").replace(Kb,"&lt;"),a=String(a).replace(Lb,Mb)):a=Sa(String(a));return a}
var Pb={"\x00":"&#0;","\t":"&#9;","\n":"&#10;","\x0B":"&#11;","\f":"&#12;","\r":"&#13;"," ":"&#32;",'"':"&quot;","&":"&amp;","'":"&#39;","-":"&#45;","/":"&#47;","<":"&lt;","=":"&#61;",">":"&gt;","`":"&#96;","\u0085":"&#133;","\u00a0":"&#160;","\u2028":"&#8232;","\u2029":"&#8233;"};function Mb(a){return Pb[a]}var Lb=/[\x00\x22\x27\x3c\x3e]/g,Jb=/<(?:!|\/?([a-zA-Z][a-zA-Z0-9:\-]*))(?:[^>'"]|"[^"]*"|'[^']*')*>/g,Kb=/</g;function Qb(){return"Unusable documentation"}function Rb(){return"Poor documentation"}function Sb(){return"OK documentation"}function Tb(){return"Good documentation"}function Ub(){return"Excellent documentation"}function Vb(a){return'You rated "'+(a.v+'"')}function Wb(a){return a.v};var Xb=!A||9<=Number(E),Yb=!B&&!A||A&&9<=Number(E)||B&&D("1.9.1"),Zb=A&&!D("9"),$b=A||Wa||C;function N(a,b){this.a=void 0!==a?a:0;this.b=void 0!==b?b:0}g=N.prototype;g.$a=function(){return new N(this.a,this.b)};g.X=function(a){return a instanceof N&&(this==a?!0:this&&a?this.a==a.a&&this.b==a.b:!1)};g.ceil=function(){this.a=Math.ceil(this.a);this.b=Math.ceil(this.b);return this};g.floor=function(){this.a=Math.floor(this.a);this.b=Math.floor(this.b);return this};g.round=function(){this.a=Math.round(this.a);this.b=Math.round(this.b);return this};
g.bb=function(a,b){a instanceof N?(this.a+=a.a,this.b+=a.b):(this.a+=Number(a),"number"===typeof b&&(this.b+=b));return this};g.ab=function(a,b){this.a*=a;this.b*="number"===typeof b?b:a;return this};g.Fb=function(a,b){a=a*Math.PI/180;b=b||new N(0,0);var c=this.a,d=this.b,e=Math.cos(a);a=Math.sin(a);this.a=(c-b.a)*e-(d-b.b)*a+b.a;this.b=(c-b.a)*a+(d-b.b)*e+b.b};function ac(a,b){this.width=a;this.height=b}g=ac.prototype;g.cb=function(){return new ac(this.width,this.height)};g.xa=function(){return Math.max(this.width,this.height)};g.Ka=function(){return Math.min(this.width,this.height)};g.ub=function(){return 2*(this.width+this.height)};g.aspectRatio=function(){return this.width/this.height};g.kb=function(){return!(this.width*this.height)};g.ceil=function(){this.width=Math.ceil(this.width);this.height=Math.ceil(this.height);return this};
g.aa=function(a){return this.width<=a.width&&this.height<=a.height};g.floor=function(){this.width=Math.floor(this.width);this.height=Math.floor(this.height);return this};g.round=function(){this.width=Math.round(this.width);this.height=Math.round(this.height);return this};function bc(a,b){a.width*=b;a.height*=b;return a}g.Gb=function(a){a=this.aspectRatio()<=a.aspectRatio()?a.width/this.width:a.height/this.height;return bc(this,a)};
g.Hb=function(a){a=this.aspectRatio()>a.aspectRatio()?a.width/this.width:a.height/this.height;return bc(this,a)};function O(a){return a?new P(Q(a)):pa||(pa=new P)}function cc(a,b){var c=b||document,d=null;c.getElementsByClassName?d=c.getElementsByClassName(a)[0]:d=dc(document,"*",a,b);return d||null}
function ec(a,b,c,d){a=d||a;var e=b&&"*"!=b?String(b).toUpperCase():"";if(a.querySelectorAll&&a.querySelector&&(e||c))return a.querySelectorAll(e+(c?"."+c:""));if(c&&a.getElementsByClassName){b=a.getElementsByClassName(c);if(e){a={};for(var f=d=0,h;h=b[f];f++)e==h.nodeName&&(a[d++]=h);a.length=d;return a}return b}b=a.getElementsByTagName(e||"*");if(c){a={};for(f=d=0;h=b[f];f++){e=h.className;var k;if(k="function"==typeof e.split)k=0<=qa(e.split(/\s+/),c);k&&(a[d++]=h)}a.length=d;return a}return b}
function dc(a,b,c,d){var e=d||a,f=b&&"*"!=b?String(b).toUpperCase():"";return e.querySelectorAll&&e.querySelector&&(f||c)?e.querySelector(f+(c?"."+c:"")):ec(a,b,c,d)[0]||null}function fc(a,b){Ga(b,function(c,d){c&&"object"==typeof c&&c.u&&(c=c.o());"style"==d?a.style.cssText=c:"class"==d?a.className=c:"for"==d?a.htmlFor=c:gc.hasOwnProperty(d)?a.setAttribute(gc[d],c):0==d.lastIndexOf("aria-",0)||0==d.lastIndexOf("data-",0)?a.setAttribute(d,c):a[d]=c})}
var gc={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",frameborder:"frameBorder",height:"height",maxlength:"maxLength",nonce:"nonce",role:"role",rowspan:"rowSpan",type:"type",usemap:"useMap",valign:"vAlign",width:"width"};function hc(a){a=a.document;a=R(a)?a.documentElement:a.body;return new ac(a.clientWidth,a.clientHeight)}function ic(a){return a.scrollingElement?a.scrollingElement:!C&&R(a)?a.documentElement:a.body||a.documentElement}
function S(a){return a.parentWindow||a.defaultView}function jc(a,b,c,d){function e(h){h&&b.appendChild("string"===typeof h?a.createTextNode(h):h)}for(;d<c.length;d++){var f=c[d];ma(f)&&!kc(f)?ra(lc(f)?ta(f):f,e):e(f)}}function T(a,b){b=String(b);"application/xhtml+xml"===a.contentType&&(b=b.toLowerCase());return a.createElement(b)}function R(a){return"CSS1Compat"==a.compatMode}function mc(a){for(var b;b=a.firstChild;)a.removeChild(b)}
function nc(a){return a&&a.parentNode?a.parentNode.removeChild(a):null}function U(a,b){for(;a&&1!=a.nodeType;)a=b?a.nextSibling:a.previousSibling;return a}function kc(a){return r(a)&&0<a.nodeType}function oc(a){return r(a)&&1==a.nodeType}function pc(a,b){if(!a||!b)return!1;if(a.contains&&1==b.nodeType)return a==b||a.contains(b);if("undefined"!=typeof a.compareDocumentPosition)return a==b||!!(a.compareDocumentPosition(b)&16);for(;b&&a!=b;)b=b.parentNode;return b==a}
function qc(a,b){var c=a.parentNode;if(c==b)return-1;for(;b.parentNode!=c;)b=b.parentNode;return rc(b,a)}function rc(a,b){for(;b=b.previousSibling;)if(b==a)return-1;return 1}function Q(a){return 9==a.nodeType?a:a.ownerDocument||a.document}
function sc(a,b){if("textContent"in a)a.textContent=b;else if(3==a.nodeType)a.data=String(b);else if(a.firstChild&&3==a.firstChild.nodeType){for(;a.lastChild!=a.firstChild;)a.removeChild(a.lastChild);a.firstChild.data=String(b)}else mc(a),a.appendChild(Q(a).createTextNode(String(b)))}function tc(a,b,c,d){if(null!=a)for(a=a.firstChild;a;){if(b(a)&&(c.push(a),d)||tc(a,b,c,d))return!0;a=a.nextSibling}return!1}var uc={SCRIPT:1,STYLE:1,HEAD:1,IFRAME:1,OBJECT:1},V={IMG:" ",BR:"\n"};
function vc(a){return wc(a)&&xc(a)}function wc(a){return A&&!D("9")?(a=a.getAttributeNode("tabindex"),null!=a&&a.specified):a.hasAttribute("tabindex")}function xc(a){a=a.tabIndex;return"number"===typeof a&&0<=a&&32768>a}function yc(a){if(Zb&&null!==a&&"innerText"in a)a=a.innerText.replace(/(\r\n|\r|\n)/g,"\n");else{var b=[];zc(a,b,!0);a=b.join("")}a=a.replace(/ \xAD /g," ").replace(/\xAD/g,"");a=a.replace(/\u200B/g,"");Zb||(a=a.replace(/ +/g," "));" "!=a&&(a=a.replace(/^\s*/,""));return a}
function zc(a,b,c){if(!(a.nodeName in uc))if(3==a.nodeType)c?b.push(String(a.nodeValue).replace(/(\r\n|\r|\n)/g,"")):b.push(a.nodeValue);else if(a.nodeName in V)b.push(V[a.nodeName]);else for(a=a.firstChild;a;)zc(a,b,c),a=a.nextSibling}function lc(a){if(a&&"number"==typeof a.length){if(r(a))return"function"==typeof a.item||"string"==typeof a.item;if("function"==p(a))return"function"==typeof a.item}return!1}
function Ac(a,b,c,d){if(!b&&!c)return null;var e=b?String(b).toUpperCase():null;return Bc(a,function(f){var h;(h=!e||f.nodeName==e)&&!(h=!c)&&(h="string"===typeof f.className)&&(h=0<=qa(f.className.split(/\s+/),c));return h},!0,d)}function Bc(a,b,c,d){a&&!c&&(a=a.parentNode);for(c=0;a&&(null==d||c<=d);){if(b(a))return a;a=a.parentNode;c++}return null}function P(a){this.a=a||m.document||document}g=P.prototype;g.oa=O;g.Ib=function(a){this.a=a};g.ja=function(){return this.a};
g.K=function(a){return"string"===typeof a?this.a.getElementById(a):a};g.Ia=function(a){return"string"===typeof a?this.a.getElementById(a):a};g.R=P.prototype.K;g.Ra=function(a,b){return(b||this.a).getElementsByTagName(String(a))};g.L=function(a,b,c){return ec(this.a,a,b,c)};g.qa=function(a,b,c){return dc(this.a,a,b,c)};g.ra=function(a,b){var c=(b=b||this.a)||document;return c.querySelectorAll&&c.querySelector?c.querySelectorAll("."+a):ec(document,"*",a,b)};g.pa=function(a,b){return cc(a,b||this.a)};
g.Ja=function(a,b){return cc(a,b||this.a)};g.S=P.prototype.L;g.Kb=fc;g.Ma=function(a){return hc(a||S(this.a)||window)};g.ka=function(){var a=S(this.a),b=a.document;var c=0;if(b){c=b.body;var d=b.documentElement;if(d&&c)if(a=hc(a).height,R(b)&&d.scrollHeight)c=d.scrollHeight!=a?d.scrollHeight:d.offsetHeight;else{b=d.scrollHeight;var e=d.offsetHeight;d.clientHeight!=e&&(b=c.scrollHeight,e=c.offsetHeight);c=b>a?b>e?b:e:b<e?b:e}else c=0}return c};
g.J=function(a,b,c){var d=this.a,e=arguments,f=String(e[0]),h=e[1];if(!Xb&&h&&(h.name||h.type)){f=["<",f];h.name&&f.push(' name="',Sa(h.name),'"');if(h.type){f.push(' type="',Sa(h.type),'"');var k={};Ja(k,h);delete k.type;h=k}f.push(">");f=f.join("")}f=T(d,f);h&&("string"===typeof h?f.className=h:q(h)?f.className=h.join(" "):fc(f,h));2<e.length&&jc(d,f,e,2);return f};g.T=P.prototype.J;g.Qa=function(a){return this.a.createTextNode(String(a))};
g.W=function(a,b,c){var d=this.a;c=!!c;for(var e=T(d,"TABLE"),f=e.appendChild(T(d,"TBODY")),h=0;h<a;h++){for(var k=T(d,"TR"),Nb=0;Nb<b;Nb++){var Ob=T(d,"TD");c&&sc(Ob,"\u00a0");k.appendChild(Ob)}f.appendChild(k)}return e};g.ib=function(){return R(this.a)};g.ma=function(){return ic(this.a)};g.la=function(){var a=this.a,b=ic(a);a=S(a);return A&&D("10")&&a.pageYOffset!=b.scrollTop?new N(b.scrollLeft,b.scrollTop):new N(a.pageXOffset||b.scrollLeft,a.pageYOffset||b.scrollTop)};
g.ca=function(a){a=a||this.a;try{var b=a&&a.activeElement;var c=b&&b.nodeName?b:null}catch(d){c=null}return c};g.Oa=function(a,b){a.appendChild(b)};g.Na=function(a,b){jc(Q(a),a,arguments,1)};g.Pa=function(a){if(1!=a.nodeType)return!1;switch(a.tagName){case "APPLET":case "AREA":case "BASE":case "BR":case "COL":case "COMMAND":case "EMBED":case "FRAME":case "HR":case "IMG":case "INPUT":case "IFRAME":case "ISINDEX":case "KEYGEN":case "LINK":case "NOFRAMES":case "NOSCRIPT":case "META":case "OBJECT":case "PARAM":case "SCRIPT":case "SOURCE":case "STYLE":case "TRACK":case "WBR":return!1}return!0};
g.xb=mc;g.hb=function(a,b){b.parentNode&&b.parentNode.insertBefore(a,b)};g.gb=function(a,b){b.parentNode&&b.parentNode.insertBefore(a,b.nextSibling)};g.fb=function(a,b,c){a.insertBefore(b,a.childNodes[c]||null)};g.Sa=nc;g.Ta=function(a,b){var c=b.parentNode;c&&c.replaceChild(a,b)};g.ba=function(a){var b,c=a.parentNode;if(c&&11!=c.nodeType){if(a.removeNode)return a.removeNode(!1);for(;b=a.firstChild;)c.insertBefore(b,a);return nc(a)}};
g.ha=function(a){return Yb&&void 0!=a.children?a.children:sa(a.childNodes,function(b){return 1==b.nodeType})};g.sa=function(a){return void 0!==a.firstElementChild?a.firstElementChild:U(a.firstChild,!0)};g.va=function(a){return void 0!==a.lastElementChild?a.lastElementChild:U(a.lastChild,!1)};g.ya=function(a){return void 0!==a.nextElementSibling?a.nextElementSibling:U(a.nextSibling,!0)};g.Ga=function(a){return void 0!==a.previousElementSibling?a.previousElementSibling:U(a.previousSibling,!1)};
g.za=function(a){if(!a)return null;if(a.firstChild)return a.firstChild;for(;a&&!a.nextSibling;)a=a.parentNode;return a?a.nextSibling:null};g.Ha=function(a){if(!a)return null;if(!a.previousSibling)return a.parentNode;for(a=a.previousSibling;a&&a.lastChild;)a=a.lastChild;return a};g.nb=kc;g.jb=oc;g.pb=function(a){return r(a)&&a.window==a};g.Fa=function(a){var b;if($b&&!(A&&D("9")&&!D("10")&&m.SVGElement&&a instanceof m.SVGElement)&&(b=a.parentElement))return b;b=a.parentNode;return oc(b)?b:null};
g.contains=pc;
g.V=function(a,b){if(a==b)return 0;if(a.compareDocumentPosition)return a.compareDocumentPosition(b)&2?1:-1;if(A&&!(9<=Number(E))){if(9==a.nodeType)return-1;if(9==b.nodeType)return 1}if("sourceIndex"in a||a.parentNode&&"sourceIndex"in a.parentNode){var c=1==a.nodeType,d=1==b.nodeType;if(c&&d)return a.sourceIndex-b.sourceIndex;var e=a.parentNode,f=b.parentNode;return e==f?rc(a,b):!c&&pc(e,b)?-1*qc(a,b):!d&&pc(f,a)?qc(b,a):(c?a.sourceIndex:e.sourceIndex)-(d?b.sourceIndex:f.sourceIndex)}d=Q(a);c=d.createRange();
c.selectNode(a);c.collapse(!0);a=d.createRange();a.selectNode(b);a.collapse(!0);return c.compareBoundaryPoints(m.Range.START_TO_END,a)};g.Y=function(a){var b,c=arguments.length;if(!c)return null;if(1==c)return arguments[0];var d=[],e=Infinity;for(b=0;b<c;b++){for(var f=[],h=arguments[b];h;)f.unshift(h),h=h.parentNode;d.push(f);e=Math.min(e,f.length)}f=null;for(b=0;b<e;b++){h=d[0][b];for(var k=1;k<c;k++)if(h!=d[k][b])return f;f=h}return f};g.Ea=Q;g.ta=function(a){return a.contentDocument||a.contentWindow.document};
g.ua=function(a){try{var b;if(!(b=a.contentWindow)){if(a.contentDocument){var c=a.contentDocument;var d=c?S(c):window}else d=null;b=d}return b}catch(e){}return null};g.Lb=sc;g.Da=function(a){if("outerHTML"in a)return a.outerHTML;var b=T(Q(a),"DIV");b.appendChild(a.cloneNode(!0));return b.innerHTML};g.Z=function(a,b){var c=[];return tc(a,b,c,!0)?c[0]:void 0};g.$=function(a,b){var c=[];tc(a,b,c,!1);return c};g.mb=vc;g.Jb=function(a,b){b?a.tabIndex=0:(a.tabIndex=-1,a.removeAttribute("tabIndex"))};
g.lb=function(a){var b;if((b="A"==a.tagName&&a.hasAttribute("href")||"INPUT"==a.tagName||"TEXTAREA"==a.tagName||"SELECT"==a.tagName||"BUTTON"==a.tagName?!a.disabled&&(!wc(a)||xc(a)):vc(a))&&A){var c;"function"!=p(a.getBoundingClientRect)||A&&null==a.parentElement?c={height:a.offsetHeight,width:a.offsetWidth}:c=a.getBoundingClientRect();a=null!=c&&0<c.height&&0<c.width}else a=b;return a};g.La=yc;g.Ba=function(a){return yc(a).length};
g.Ca=function(a,b){b=b||Q(a).body;for(var c=[];a&&a!=b;){for(var d=a;d=d.previousSibling;)c.unshift(yc(d));a=a.parentNode}return c.join("").replace(/^[\s\xa0]+/,"").replace(/ +/g," ").length};
g.Aa=function(a,b,c){a=[a];for(var d=0,e=null;0<a.length&&d<b;)if(e=a.pop(),!(e.nodeName in uc))if(3==e.nodeType){var f=e.nodeValue.replace(/(\r\n|\r|\n)/g,"").replace(/ +/g," ");d+=f.length}else if(e.nodeName in V)d+=V[e.nodeName].length;else for(f=e.childNodes.length-1;0<=f;f--)a.push(e.childNodes[f]);r(c)&&(c.wb=e?e.nodeValue.length+b-d-1:0,c.node=e);return e};g.ob=lc;g.fa=Ac;g.ea=function(a,b,c){return Ac(a,null,b,c)};g.da=Bc;g.ga=function(a){return a.getContext("2d")};var Cc=!/^\s*class\s*\{\s*\}\s*$/.test(function(){}.toString());/*

 Copyright (c) 2016 The Polymer Project Authors. All rights reserved.
 This code may only be used under the BSD style license found at http://polymer.github.io/LICENSE.txt
 The complete set of authors may be found at http://polymer.github.io/AUTHORS.txt
 The complete set of contributors may be found at http://polymer.github.io/CONTRIBUTORS.txt
 Code distributed by Google as part of the polymer project is also
 subject to an additional IP rights grant found at http://polymer.github.io/PATENTS.txt
*/
(function(){if(Cc&&!HTMLElement.es5Shimmed&&void 0!==window.Reflect&&void 0!==window.customElements&&!window.customElements.polyfillWrapFlushCallback){var a=HTMLElement;window.HTMLElement=function(){return Reflect.construct(a,[],this.constructor)};HTMLElement.prototype=a.prototype;HTMLElement.prototype.constructor=HTMLElement;HTMLElement.es5Shimmed=!0;Object.setPrototypeOf(HTMLElement,a)}})();function W(a){var b=HTMLElement.call(this)||this;a&&("string"===typeof a&&(a=[a]),document.body.dispatchEvent(new CustomEvent("devsite-load-custom-elements",{bubbles:!0,detail:a})));return b}ha(W,HTMLElement);W.prototype.H=function(){console.warn(this.tagName,"has not implemented update")};W.prototype.s=function(a){a=void 0===a?"":a;return document.createRange().createContextualFragment(a||"")};
W.prototype.F=function(a,b,c){a&&b?a.parentNode.replaceChild(document.importNode(b,!0),a):!b&&a?a.parentNode.removeChild(a):!a&&b&&(c?(a=document.importNode(b,!0),c.parentElement.insertBefore(a,c.nextSibling)):this.appendChild(document.importNode(b,!0)))};function X(a){F.call(this);this.c=a;this.a={}}oa(X,F);var Dc=[];function Ec(a,b,c,d){K(a,b,c,d,void 0)}g=X.prototype;g.rb=function(a,b,c,d,e){return K(this,a,b,c,d,e)};function K(a,b,c,d,e,f){q(c)||(c&&(Dc[0]=c.toString()),c=Dc);for(var h=0;h<c.length;h++){var k=sb(b,c[h],d||a.handleEvent,e||!1,f||a.c||a);if(!k)break;a.a[k.key]=k}return a}g.Va=function(a,b,c,d){return Fc(this,a,b,c,d)};g.qb=function(a,b,c,d,e){return Fc(this,a,b,c,d,e)};
function Fc(a,b,c,d,e,f){if(q(c))for(var h=0;h<c.length;h++)Fc(a,b,c[h],d,e,f);else{b=tb(b,c,d||a.handleEvent,e,f||a.c||a);if(!b)return a;a.a[b.key]=b}return a}g.sb=function(a,b,c,d){K(b,a,c,d,this.c||this);return this};g.tb=function(a,b,c,d,e){K(b,a,c,d,e||this.c||this);return this};g.Ua=function(){var a=0,b;for(b in this.a)Object.prototype.hasOwnProperty.call(this.a,b)&&a++;return a};
function Gc(a,b,c,d,e,f){if(q(c))for(var h=0;h<c.length;h++)Gc(a,b,c[h],d,e,f);else d=d||a.handleEvent,e=r(e)?!!e.capture:!!e,f=f||a.c||a,d=ub(d),e=!!e,b&&b[I]?c=b.B(c,d,e,f):b?(b=L(b))?(c=b.a[c.toString()],b=-1,c&&(b=ob(c,d,e,f)),c=-1<b?c[b]:null):c=null:c=null,c&&(zb(c),delete a.a[c.key])}g.Nb=function(a,b,c,d,e){Gc(b,a,c,d,e||this.c||this,this);return this};function Hc(a){Ga(a.a,function(b,c){this.a.hasOwnProperty(c)&&zb(b)},a);a.a={}}g.m=function(){X.j.m.call(this);Hc(this)};
g.handleEvent=function(){throw Error("EventHandler.handleEvent not implemented");};function Ic(a,b){b=b||O();b=T(b.a,"DIV");a=Jc(a);z(b,a);return 1==b.childNodes.length&&(a=b.firstChild,1==a.nodeType)?a:b}function Jc(a){return r(a)?a instanceof M?Fb(a):x("zSoyz"):x(String(a))}var Kc={};function Lc(){this.a=O();this.b=null}g=Lc.prototype;g.Ab=function(a,b){var c=this.a||O();a=a(b||Kc,void 0,{});a=Jc(a);b=c.a;c=T(b,"DIV");A?(a=Pa(Qa,a),z(c,a),c.removeChild(c.firstChild)):z(c,a);if(1==c.childNodes.length)c=c.removeChild(c.firstChild);else{for(a=b.createDocumentFragment();c.firstChild;)a.appendChild(c.firstChild);c=a}return c};g.zb=function(a,b){var c=this.a;return Ic(a(b||Kc,void 0,{}),c)};g.Bb=function(a,b,c){b=Jc(b(c||Kc,void 0,{}));z(a,b)};g.yb=function(a,b){a=a(b||{},{});return String(a)};
function Y(a,b){a=a(b||{},{});return String(a)}g.Eb=function(a,b){return a(b||{},{},{})};g.Cb=function(a,b){return Fb(a(b||{},{},{}))};g.Db=function(a,b){return a(b||{},{},{}).Mb()};g.na=function(){return this.a};g.eb=n;function Z(){var a=W.call(this)||this;a.G=new Lc;a.a=new X;a.b=0;var b=[Y(Qb),Y(Rb),Y(Sb),Y(Tb),Y(Ub)];a.f=b;a.c=[];return a}ha(Z,W);
Z.prototype.connectedCallback=function(){var a=this.getAttribute("position")||"";var b=this.f;var c="";(a&&a.N&&"footer".N?a.h!=="footer".h?0:a.toString()==="footer".toString():"footer"==a)&&(c+='<div class="devsite-rating-caption">Was this page helpful?</div>');c+='<div class="devsite-rating-stars">';a=Math.max(0,Math.ceil(b.length));for(var d=0;d<a;d++){var e=d;c+='<div class="devsite-rating-star devsite-rating-star-outline gc-analytics-event material-icons" data-rating-val="'+Ib(e+1)+'" role="button" data-title="'+
Ib(b[e])+'" aria-label="';e="Site content star ratings, rating "+(Ib(e+1)+" out of 5");c+=String(e).replace(Lb,Mb);c+='"></div>'}b=Hb(c+'</div><div class="devsite-rating-internal"><span class="devsite-rating-stats"></span></div>');b=Ic(b,void 0);this.c=Array.from(b.querySelectorAll(".devsite-rating-star"));this.hasAttribute("selected-rating")||this.setAttribute("selected-rating","0");this.hasAttribute("hover-rating-star")||this.setAttribute("hover-rating-star","0");this.appendChild(b);Mc(this)};
function Mc(a){Ec(a.a,a,"click",function(b){if(b.target.classList.contains("devsite-rating-star")){b=Number(b.target.getAttribute("data-rating-val"));if(b!=a.b){Nc("selected-rating",b);var c={nonInteraction:!0,page:(new URL(document.location.toString())).pathname,referrer:(new URL(document.location.toString())).pathname,ratings_value:b,ratings_count:1};a.dispatchEvent(new CustomEvent("devsite-analytics-pageview",{detail:c,bubbles:!0}))}3>=b&&(b=document.querySelector("devsite-feedback"))&&b.dispatchEvent(new Event("click"))}});
Ec(a.a,a,"onpointerover"in window?"pointerover":"mouseover",function(b){b.target.classList.contains("devsite-rating-star")&&(b=Number(b.target.getAttribute("data-rating-val")),Nc("hover-rating-star",b))});Ec(a.a,a,"onpointerout"in window?"pointerout":"mouseout",function(b){b.target.classList.contains("devsite-rating-star")&&Nc("hover-rating-star",a.b)})}
Z.prototype.attributeChangedCallback=function(a,b,c){if("selected-rating"===a&&null!=b){var d=this.b=Number(c)||0;b=Number(b)||0;var e=d-1,f=b-1;0<b&&5>=b&&this.c[f].setAttribute("data-title",Y(Wb,{v:this.f[f]}));0<d&&5>=d&&this.c[e].setAttribute("data-title",Y(Vb,{v:this.f[e]}))}"hover-rating-star"===a&&Oc(this,Number(c)||0)};Z.prototype.disconnectedCallback=function(){Hc(this.a)};
function Nc(a,b){Array.from(document.getElementsByTagName("devsite-page-rating")).forEach(function(c){return c.setAttribute(a,b)})}function Oc(a,b){a.c.forEach(function(c){Number(c.getAttribute("data-rating-val"))<=b?c.classList.add("devsite-rating-star-full"):c.classList.remove("devsite-rating-star-full")})}ja.Object.defineProperties(Z,{observedAttributes:{configurable:!0,enumerable:!0,get:function(){return["selected-rating","hover-rating-star"]}}});Z.prototype.disconnectedCallback=Z.prototype.disconnectedCallback;
Z.prototype.attributeChangedCallback=Z.prototype.attributeChangedCallback;Z.prototype.connectedCallback=Z.prototype.connectedCallback;try{window.customElements.define("devsite-page-rating",Z)}catch(a){console.warn("devsite.app.customElement.DevsitePageRating",a)};}).call(this);
