(function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
'use strict';var g;function aa(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}}function ba(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return b?b.call(a):{next:aa(a)}}var ca="function"==typeof Object.create?Object.create:function(a){function b(){}b.prototype=a;return new b},da;
if("function"==typeof Object.setPrototypeOf)da=Object.setPrototypeOf;else{var ea;a:{var fa={L:!0},ha={};try{ha.__proto__=fa;ea=ha.L;break a}catch(a){}ea=!1}da=ea?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var ia=da;
function ja(a,b){a.prototype=ca(b.prototype);a.prototype.constructor=a;if(ia)ia(a,b);else for(var c in b)if("prototype"!=c)if(Object.defineProperties){var d=Object.getOwnPropertyDescriptor(b,c);d&&Object.defineProperty(a,c,d)}else a[c]=b[c];a.w=b.prototype}var p="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)};
function ka(a){a=["object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global,a];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}return globalThis}var q=ka(this);function r(a,b){if(b){var c=q;a=a.split(".");for(var d=0;d<a.length-1;d++){var e=a[d];e in c||(c[e]={});c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&p(c,a,{configurable:!0,writable:!0,value:b})}}function la(){la=function(){};q.Symbol||(q.Symbol=ma)}
function na(a,b){this.a=a;p(this,"description",{configurable:!0,writable:!0,value:b})}na.prototype.toString=function(){return this.a};var ma=function(){function a(c){if(this instanceof a)throw new TypeError("Symbol is not a constructor");return new na("jscomp_symbol_"+(c||"")+"_"+b++,c)}var b=0;return a}();
function oa(){la();var a=q.Symbol.iterator;a||(a=q.Symbol.iterator=q.Symbol("Symbol.iterator"));"function"!=typeof Array.prototype[a]&&p(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return pa(aa(this))}});oa=function(){}}function pa(a){oa();a={next:a};a[q.Symbol.iterator]=function(){return this};return a}
var qa=function(){function a(){function c(){}new c;Reflect.construct(c,[],function(){});return new c instanceof c}if("undefined"!=typeof Reflect&&Reflect.construct){if(a())return Reflect.construct;var b=Reflect.construct;return function(c,d,e){c=b(c,d);e&&Reflect.setPrototypeOf(c,e.prototype);return c}}return function(c,d,e){void 0===e&&(e=c);e=ca(e.prototype||Object.prototype);return Function.prototype.apply.call(c,e,d)||e}}();r("Reflect.construct",function(){return qa});
r("Object.setPrototypeOf",function(a){return a||ia});function t(a,b){return Object.prototype.hasOwnProperty.call(a,b)}
r("WeakMap",function(a){function b(l){this.a=(h+=Math.random()+1).toString();if(l){l=ba(l);for(var m;!(m=l.next()).done;)m=m.value,this.set(m[0],m[1])}}function c(){}function d(l){var m=typeof l;return"object"===m&&null!==l||"function"===m}function e(l){if(!t(l,k)){var m=new c;p(l,k,{value:m})}}function f(l){var m=Object[l];m&&(Object[l]=function(n){if(n instanceof c)return n;e(n);return m(n)})}if(function(){if(!a||!Object.seal)return!1;try{var l=Object.seal({}),m=Object.seal({}),n=new a([[l,2],[m,
3]]);if(2!=n.get(l)||3!=n.get(m))return!1;n.delete(l);n.set(m,4);return!n.has(l)&&4==n.get(m)}catch(I){return!1}}())return a;var k="$jscomp_hidden_"+Math.random();f("freeze");f("preventExtensions");f("seal");var h=0;b.prototype.set=function(l,m){if(!d(l))throw Error("Invalid WeakMap key");e(l);if(!t(l,k))throw Error("WeakMap key fail: "+l);l[k][this.a]=m;return this};b.prototype.get=function(l){return d(l)&&t(l,k)?l[k][this.a]:void 0};b.prototype.has=function(l){return d(l)&&t(l,k)&&t(l[k],this.a)};
b.prototype.delete=function(l){return d(l)&&t(l,k)&&t(l[k],this.a)?delete l[k][this.a]:!1};return b});
r("Map",function(a){function b(){var h={};return h.i=h.next=h.head=h}function c(h,l){var m=h.a;return pa(function(){if(m){for(;m.head!=h.a;)m=m.i;for(;m.next!=m.head;)return m=m.next,{done:!1,value:l(m)};m=null}return{done:!0,value:void 0}})}function d(h,l){var m=l&&typeof l;"object"==m||"function"==m?f.has(l)?m=f.get(l):(m=""+ ++k,f.set(l,m)):m="p_"+l;var n=h.b[m];if(n&&t(h.b,m))for(h=0;h<n.length;h++){var I=n[h];if(l!==l&&I.key!==I.key||l===I.key)return{id:m,list:n,index:h,f:I}}return{id:m,list:n,
index:-1,f:void 0}}function e(h){this.b={};this.a=b();this.size=0;if(h){h=ba(h);for(var l;!(l=h.next()).done;)l=l.value,this.set(l[0],l[1])}}if(function(){if(!a||"function"!=typeof a||!a.prototype.entries||"function"!=typeof Object.seal)return!1;try{var h=Object.seal({x:4}),l=new a(ba([[h,"s"]]));if("s"!=l.get(h)||1!=l.size||l.get({x:4})||l.set({x:4},"t")!=l||2!=l.size)return!1;var m=l.entries(),n=m.next();if(n.done||n.value[0]!=h||"s"!=n.value[1])return!1;n=m.next();return n.done||4!=n.value[0].x||
"t"!=n.value[1]||!m.next().done?!1:!0}catch(I){return!1}}())return a;oa();var f=new WeakMap;e.prototype.set=function(h,l){h=0===h?0:h;var m=d(this,h);m.list||(m.list=this.b[m.id]=[]);m.f?m.f.value=l:(m.f={next:this.a,i:this.a.i,head:this.a,key:h,value:l},m.list.push(m.f),this.a.i.next=m.f,this.a.i=m.f,this.size++);return this};e.prototype.delete=function(h){h=d(this,h);return h.f&&h.list?(h.list.splice(h.index,1),h.list.length||delete this.b[h.id],h.f.i.next=h.f.next,h.f.next.i=h.f.i,h.f.head=null,
this.size--,!0):!1};e.prototype.clear=function(){this.b={};this.a=this.a.i=b();this.size=0};e.prototype.has=function(h){return!!d(this,h).f};e.prototype.get=function(h){return(h=d(this,h).f)&&h.value};e.prototype.entries=function(){return c(this,function(h){return[h.key,h.value]})};e.prototype.keys=function(){return c(this,function(h){return h.key})};e.prototype.values=function(){return c(this,function(h){return h.value})};e.prototype.forEach=function(h,l){for(var m=this.entries(),n;!(n=m.next()).done;)n=
n.value,h.call(l,n[1],n[0],this)};e.prototype[Symbol.iterator]=e.prototype.entries;var k=0;return e});r("Array.from",function(a){return a?a:function(b,c,d){c=null!=c?c:function(h){return h};var e=[],f="undefined"!=typeof Symbol&&Symbol.iterator&&b[Symbol.iterator];if("function"==typeof f){b=f.call(b);for(var k=0;!(f=b.next()).done;)e.push(c.call(d,f.value,k++))}else for(f=b.length,k=0;k<f;k++)e.push(c.call(d,b[k],k));return e}});var u=this||self;function ra(){}
function sa(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b}function v(a){return"array"==sa(a)}function ta(a){var b=sa(a);return"array"==b||"object"==b&&"number"==typeof a.length}function w(a){return"function"==sa(a)}function x(a){var b=typeof a;return"object"==b&&null!=a||"function"==b}function ua(a,b,c){return a.call.apply(a.bind,arguments)}
function va(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var e=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(e,d);return a.apply(b,e)}}return function(){return a.apply(b,arguments)}}function y(a,b,c){Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?y=ua:y=va;return y.apply(null,arguments)}
function wa(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var d=c.slice();d.push.apply(d,arguments);return a.apply(this,d)}}var xa=Date.now||function(){return+new Date};function z(a,b){function c(){}c.prototype=b.prototype;a.w=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.Y=function(d,e,f){for(var k=Array(arguments.length-2),h=2;h<arguments.length;h++)k[h-2]=arguments[h];return b.prototype[e].apply(d,k)}};var ya;var za=Array.prototype.indexOf?function(a,b){return Array.prototype.indexOf.call(a,b,void 0)}:function(a,b){if("string"===typeof a)return"string"!==typeof b||1!=b.length?-1:a.indexOf(b,0);for(var c=0;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},Aa=Array.prototype.forEach?function(a,b){Array.prototype.forEach.call(a,b,void 0)}:function(a,b){for(var c=a.length,d="string"===typeof a?a.split(""):a,e=0;e<c;e++)e in d&&b.call(void 0,d[e],e,a)},Ba=Array.prototype.filter?function(a,b){return Array.prototype.filter.call(a,
b,void 0)}:function(a,b){for(var c=a.length,d=[],e=0,f="string"===typeof a?a.split(""):a,k=0;k<c;k++)if(k in f){var h=f[k];b.call(void 0,h,k,a)&&(d[e++]=h)}return d};function Ca(a){var b=a.length;if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]};function Da(a,b,c){for(var d in a)b.call(c,a[d],d,a)}var Ea="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" ");function Fa(a,b){for(var c,d,e=1;e<arguments.length;e++){d=arguments[e];for(c in d)a[c]=d[c];for(var f=0;f<Ea.length;f++)c=Ea[f],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}};var Ga=String.prototype.trim?function(a){return a.trim()}:function(a){return/^[\s\xa0]*([\s\S]*?)[\s\xa0]*$/.exec(a)[1]};
function Ha(a,b){if(b)a=a.replace(Ia,"&amp;").replace(Ja,"&lt;").replace(Ka,"&gt;").replace(La,"&quot;").replace(Ma,"&#39;").replace(Na,"&#0;");else{if(!Oa.test(a))return a;-1!=a.indexOf("&")&&(a=a.replace(Ia,"&amp;"));-1!=a.indexOf("<")&&(a=a.replace(Ja,"&lt;"));-1!=a.indexOf(">")&&(a=a.replace(Ka,"&gt;"));-1!=a.indexOf('"')&&(a=a.replace(La,"&quot;"));-1!=a.indexOf("'")&&(a=a.replace(Ma,"&#39;"));-1!=a.indexOf("\x00")&&(a=a.replace(Na,"&#0;"))}return a}
var Ia=/&/g,Ja=/</g,Ka=/>/g,La=/"/g,Ma=/'/g,Na=/\x00/g,Oa=/[\x00&<>"']/;function Pa(a,b){return a<b?-1:a>b?1:0};var A;a:{var Qa=u.navigator;if(Qa){var Ra=Qa.userAgent;if(Ra){A=Ra;break a}}A=""};function B(a){this.b=Sa===Sa&&a||"";this.c=Ta}B.prototype.G=!0;B.prototype.F=function(){return this.b.toString()};B.prototype.J=!0;B.prototype.a=function(){return 1};var Ta={},Sa={};function C(){this.b="";this.g=Ua;this.c=null}C.prototype.J=!0;C.prototype.a=function(){return this.c};C.prototype.G=!0;C.prototype.F=function(){return this.b.toString()};function D(a){return a instanceof C&&a.constructor===C&&a.g===Ua?a.b:"type_error:SafeHtml"}function E(a){if(a instanceof C)return a;var b="object"==typeof a,c=null;b&&a.J&&(c=a.a());a=Ha(b&&a.G?a.F():String(a));return F(a,c)}
function Va(a){function b(f){v(f)?Aa(f,b):(f=E(f),e.push(D(f).toString()),f=f.a(),0==d?d=f:0!=f&&d!=f&&(d=null))}var c=E(Wa),d=c.a(),e=[];Aa(a,b);return F(e.join(D(c).toString()),d)}function Xa(a){return Va(Array.prototype.slice.call(arguments))}var Ua={};function F(a,b){var c=new C;c.b=a;c.c=b;return c}F("<!DOCTYPE html>",0);var Wa=F("",0),Ya=F("<br>",0);var Za=function(a){var b=!1,c;return function(){b||(c=a(),b=!0);return c}}(function(){var a=document.createElement("div"),b=document.createElement("div");b.appendChild(document.createElement("div"));a.appendChild(b);b=a.firstChild.firstChild;a.innerHTML=D(Wa);return!b.parentElement});function $a(a,b){if(Za())for(;a.lastChild;)a.removeChild(a.lastChild);a.innerHTML=D(b)};function ab(a){return a=Ha(a,void 0)};var bb={},cb={};function G(){throw Error("Do not instantiate directly");}G.prototype.C=null;G.prototype.b=function(){return this.a};G.prototype.toString=function(){return this.a};G.prototype.c=function(){if(this.D!==cb)throw Error("Sanitized content was not of kind URI.");return new B(this.toString())};function db(){G.call(this)}z(db,G);db.prototype.D=bb;function eb(a){eb[" "](a);return a}eb[" "]=ra;function fb(a,b){var c=gb;return Object.prototype.hasOwnProperty.call(c,a)?c[a]:c[a]=b(a)};var hb=-1!=A.indexOf("Opera"),H=-1!=A.indexOf("Trident")||-1!=A.indexOf("MSIE"),ib=-1!=A.indexOf("Edge"),J=-1!=A.indexOf("Gecko")&&!(-1!=A.toLowerCase().indexOf("webkit")&&-1==A.indexOf("Edge"))&&!(-1!=A.indexOf("Trident")||-1!=A.indexOf("MSIE"))&&-1==A.indexOf("Edge"),K=-1!=A.toLowerCase().indexOf("webkit")&&-1==A.indexOf("Edge"),jb=-1!=A.indexOf("Macintosh");function kb(){var a=u.document;return a?a.documentMode:void 0}var lb;
a:{var mb="",nb=function(){var a=A;if(J)return/rv:([^\);]+)(\)|;)/.exec(a);if(ib)return/Edge\/([\d\.]+)/.exec(a);if(H)return/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/.exec(a);if(K)return/WebKit\/(\S+)/.exec(a);if(hb)return/(?:Version)[ \/]?(\S+)/.exec(a)}();nb&&(mb=nb?nb[1]:"");if(H){var ob=kb();if(null!=ob&&ob>parseFloat(mb)){lb=String(ob);break a}}lb=mb}var pb=lb,gb={};
function L(a){return fb(a,function(){for(var b=0,c=Ga(String(pb)).split("."),d=Ga(String(a)).split("."),e=Math.max(c.length,d.length),f=0;0==b&&f<e;f++){var k=c[f]||"",h=d[f]||"";do{k=/(\d*)(\D*)(.*)/.exec(k)||["","","",""];h=/(\d*)(\D*)(.*)/.exec(h)||["","","",""];if(0==k[0].length&&0==h[0].length)break;b=Pa(0==k[1].length?0:parseInt(k[1],10),0==h[1].length?0:parseInt(h[1],10))||Pa(0==k[2].length,0==h[2].length)||Pa(k[2],h[2]);k=k[3];h=h[3]}while(0==b)}return 0<=b})}var M;M=u.document&&H?kb():void 0;function qb(a){if(null!=a)switch(a.C){case 1:return 1;case -1:return-1;case 0:return 0}return null}var rb=function(a){function b(c){this.a=c}b.prototype=a.prototype;return function(c,d){c=new b(String(c));void 0!==d&&(c.C=d);return c}}(db);var sb=!/^\s*class\s*\{\s*\}\s*$/.test(function(){}.toString());/*

 Copyright (c) 2016 The Polymer Project Authors. All rights reserved.
 This code may only be used under the BSD style license found at http://polymer.github.io/LICENSE.txt
 The complete set of authors may be found at http://polymer.github.io/AUTHORS.txt
 The complete set of contributors may be found at http://polymer.github.io/CONTRIBUTORS.txt
 Code distributed by Google as part of the polymer project is also
 subject to an additional IP rights grant found at http://polymer.github.io/PATENTS.txt
*/
(function(){if(sb&&!HTMLElement.es5Shimmed&&void 0!==window.Reflect&&void 0!==window.customElements&&!window.customElements.polyfillWrapFlushCallback){var a=HTMLElement;window.HTMLElement=function(){return Reflect.construct(a,[],this.constructor)};HTMLElement.prototype=a.prototype;HTMLElement.prototype.constructor=HTMLElement;HTMLElement.es5Shimmed=!0;Object.setPrototypeOf(HTMLElement,a)}})();function N(a){var b=HTMLElement.call(this)||this;a&&tb(a);return b}ja(N,HTMLElement);N.prototype.u=function(){console.warn(this.tagName,"has not implemented update")};N.prototype.j=function(a){a=void 0===a?"":a;return document.createRange().createContextualFragment(a||"")};
N.prototype.s=function(a,b,c){a&&b?a.parentNode.replaceChild(document.importNode(b,!0),a):!b&&a?a.parentNode.removeChild(a):!a&&b&&(c?(a=document.importNode(b,!0),c.parentElement.insertBefore(a,c.nextSibling)):this.appendChild(document.importNode(b,!0)))};function tb(a){"string"===typeof a&&(a=[a]);document.body.dispatchEvent(new CustomEvent("devsite-load-custom-elements",{bubbles:!0,detail:a}))};var O=new Map;function P(a){var b=N.call(this)||this;a&&tb(a);return b}ja(P,N);P.prototype.connectedCallback=function(){var a=this.constructor,b=O.get(a);b?console.error("can't add duplicate element to page: "+b.tagName):O.set(a,this)};P.prototype.disconnectedCallback=function(){var a=this.constructor;O.get(a)===this&&O.delete(a)};P.prototype.disconnectedCallback=P.prototype.disconnectedCallback;P.prototype.connectedCallback=P.prototype.connectedCallback;var ub=!H||9<=Number(M),vb=!J&&!H||H&&9<=Number(M)||J&&L("1.9.1"),wb=H&&!L("9"),xb=H||hb||K;function Q(a,b){this.x=void 0!==a?a:0;this.a=void 0!==b?b:0}g=Q.prototype;g.$a=function(){return new Q(this.x,this.a)};g.aa=function(a){return a instanceof Q&&(this==a?!0:this&&a?this.x==a.x&&this.a==a.a:!1)};g.ceil=function(){this.x=Math.ceil(this.x);this.a=Math.ceil(this.a);return this};g.floor=function(){this.x=Math.floor(this.x);this.a=Math.floor(this.a);return this};g.round=function(){this.x=Math.round(this.x);this.a=Math.round(this.a);return this};
g.bb=function(a,b){a instanceof Q?(this.x+=a.x,this.a+=a.a):(this.x+=Number(a),"number"===typeof b&&(this.a+=b));return this};g.ab=function(a,b){this.x*=a;this.a*="number"===typeof b?b:a;return this};g.wb=function(a,b){a=a*Math.PI/180;b=b||new Q(0,0);var c=this.x,d=this.a,e=Math.cos(a);a=Math.sin(a);this.x=(c-b.x)*e-(d-b.a)*a+b.x;this.a=(c-b.x)*a+(d-b.a)*e+b.a};function R(a,b){this.width=a;this.height=b}g=R.prototype;g.cb=function(){return new R(this.width,this.height)};g.ya=function(){return Math.max(this.width,this.height)};g.La=function(){return Math.min(this.width,this.height)};g.sb=function(){return 2*(this.width+this.height)};g.aspectRatio=function(){return this.width/this.height};g.ib=function(){return!(this.width*this.height)};g.ceil=function(){this.width=Math.ceil(this.width);this.height=Math.ceil(this.height);return this};
g.ea=function(a){return this.width<=a.width&&this.height<=a.height};g.floor=function(){this.width=Math.floor(this.width);this.height=Math.floor(this.height);return this};g.round=function(){this.width=Math.round(this.width);this.height=Math.round(this.height);return this};function yb(a,b){a.width*=b;a.height*=b;return a}g.yb=function(a){a=this.aspectRatio()<=a.aspectRatio()?a.width/this.width:a.height/this.height;return yb(this,a)};
g.zb=function(a){a=this.aspectRatio()>a.aspectRatio()?a.width/this.width:a.height/this.height;return yb(this,a)};function S(a){return a?new T(U(a)):ya||(ya=new T)}function zb(a,b){var c=b||document,d=null;c.getElementsByClassName?d=c.getElementsByClassName(a)[0]:d=Ab(document,"*",a,b);return d||null}
function Bb(a,b,c,d){a=d||a;var e=b&&"*"!=b?String(b).toUpperCase():"";if(a.querySelectorAll&&a.querySelector&&(e||c))return a.querySelectorAll(e+(c?"."+c:""));if(c&&a.getElementsByClassName){b=a.getElementsByClassName(c);if(e){a={};for(var f=d=0,k;k=b[f];f++)e==k.nodeName&&(a[d++]=k);a.length=d;return a}return b}b=a.getElementsByTagName(e||"*");if(c){a={};for(f=d=0;k=b[f];f++){e=k.className;var h;if(h="function"==typeof e.split)h=0<=za(e.split(/\s+/),c);h&&(a[d++]=k)}a.length=d;return a}return b}
function Ab(a,b,c,d){var e=d||a,f=b&&"*"!=b?String(b).toUpperCase():"";return e.querySelectorAll&&e.querySelector&&(f||c)?e.querySelector(f+(c?"."+c:"")):Bb(a,b,c,d)[0]||null}function Cb(a,b){Da(b,function(c,d){c&&"object"==typeof c&&c.G&&(c=c.F());"style"==d?a.style.cssText=c:"class"==d?a.className=c:"for"==d?a.htmlFor=c:Db.hasOwnProperty(d)?a.setAttribute(Db[d],c):0==d.lastIndexOf("aria-",0)||0==d.lastIndexOf("data-",0)?a.setAttribute(d,c):a[d]=c})}
var Db={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",frameborder:"frameBorder",height:"height",maxlength:"maxLength",nonce:"nonce",role:"role",rowspan:"rowSpan",type:"type",usemap:"useMap",valign:"vAlign",width:"width"};function Eb(a){a=a.document;a=Fb(a)?a.documentElement:a.body;return new R(a.clientWidth,a.clientHeight)}function Gb(a){return a.scrollingElement?a.scrollingElement:!K&&Fb(a)?a.documentElement:a.body||a.documentElement}
function Hb(a){return a.parentWindow||a.defaultView}function Ib(a,b,c,d){function e(k){k&&b.appendChild("string"===typeof k?a.createTextNode(k):k)}for(;d<c.length;d++){var f=c[d];ta(f)&&!Jb(f)?Aa(Kb(f)?Ca(f):f,e):e(f)}}function V(a,b){b=String(b);"application/xhtml+xml"===a.contentType&&(b=b.toLowerCase());return a.createElement(b)}function Fb(a){return"CSS1Compat"==a.compatMode}function Lb(a){for(var b;b=a.firstChild;)a.removeChild(b)}
function W(a){return a&&a.parentNode?a.parentNode.removeChild(a):null}function Mb(a,b){for(;a&&1!=a.nodeType;)a=b?a.nextSibling:a.previousSibling;return a}function Jb(a){return x(a)&&0<a.nodeType}function Nb(a){return x(a)&&1==a.nodeType}function Ob(a,b){if(!a||!b)return!1;if(a.contains&&1==b.nodeType)return a==b||a.contains(b);if("undefined"!=typeof a.compareDocumentPosition)return a==b||!!(a.compareDocumentPosition(b)&16);for(;b&&a!=b;)b=b.parentNode;return b==a}
function Pb(a,b){var c=a.parentNode;if(c==b)return-1;for(;b.parentNode!=c;)b=b.parentNode;return Qb(b,a)}function Qb(a,b){for(;b=b.previousSibling;)if(b==a)return-1;return 1}function U(a){return 9==a.nodeType?a:a.ownerDocument||a.document}
function Rb(a,b){if("textContent"in a)a.textContent=b;else if(3==a.nodeType)a.data=String(b);else if(a.firstChild&&3==a.firstChild.nodeType){for(;a.lastChild!=a.firstChild;)a.removeChild(a.lastChild);a.firstChild.data=String(b)}else Lb(a),a.appendChild(U(a).createTextNode(String(b)))}function Sb(a,b,c,d){if(null!=a)for(a=a.firstChild;a;){if(b(a)&&(c.push(a),d)||Sb(a,b,c,d))return!0;a=a.nextSibling}return!1}var Tb={SCRIPT:1,STYLE:1,HEAD:1,IFRAME:1,OBJECT:1},Ub={IMG:" ",BR:"\n"};
function Vb(a){return Wb(a)&&Xb(a)}function Wb(a){return H&&!L("9")?(a=a.getAttributeNode("tabindex"),null!=a&&a.specified):a.hasAttribute("tabindex")}function Xb(a){a=a.tabIndex;return"number"===typeof a&&0<=a&&32768>a}function Yb(a){if(wb&&null!==a&&"innerText"in a)a=a.innerText.replace(/(\r\n|\r|\n)/g,"\n");else{var b=[];Zb(a,b,!0);a=b.join("")}a=a.replace(/ \xAD /g," ").replace(/\xAD/g,"");a=a.replace(/\u200B/g,"");wb||(a=a.replace(/ +/g," "));" "!=a&&(a=a.replace(/^\s*/,""));return a}
function Zb(a,b,c){if(!(a.nodeName in Tb))if(3==a.nodeType)c?b.push(String(a.nodeValue).replace(/(\r\n|\r|\n)/g,"")):b.push(a.nodeValue);else if(a.nodeName in Ub)b.push(Ub[a.nodeName]);else for(a=a.firstChild;a;)Zb(a,b,c),a=a.nextSibling}function Kb(a){if(a&&"number"==typeof a.length){if(x(a))return"function"==typeof a.item||"string"==typeof a.item;if(w(a))return"function"==typeof a.item}return!1}
function $b(a,b,c,d){if(!b&&!c)return null;var e=b?String(b).toUpperCase():null;return ac(a,function(f){var k;(k=!e||f.nodeName==e)&&!(k=!c)&&(k="string"===typeof f.className)&&(k=0<=za(f.className.split(/\s+/),c));return k},!0,d)}function ac(a,b,c,d){a&&!c&&(a=a.parentNode);for(c=0;a&&(null==d||c<=d);){if(b(a))return a;a=a.parentNode;c++}return null}function T(a){this.a=a||u.document||document}g=T.prototype;g.qa=S;g.Ab=function(a){this.a=a};g.na=function(){return this.a};
g.N=function(a){return"string"===typeof a?this.a.getElementById(a):a};g.Ja=function(a){return"string"===typeof a?this.a.getElementById(a):a};g.V=T.prototype.N;g.Va=function(a,b){return(b||this.a).getElementsByTagName(String(a))};g.O=function(a,b,c){return Bb(this.a,a,b,c)};g.sa=function(a,b,c){return Ab(this.a,a,b,c)};g.ta=function(a,b){var c=(b=b||this.a)||document;return c.querySelectorAll&&c.querySelector?c.querySelectorAll("."+a):Bb(document,"*",a,b)};g.ra=function(a,b){return zb(a,b||this.a)};
g.Ka=function(a,b){return zb(a,b||this.a)};g.W=T.prototype.O;g.Cb=Cb;g.Na=function(a){return Eb(a||Hb(this.a)||window)};g.oa=function(){var a=Hb(this.a),b=a.document;var c=0;if(b){c=b.body;var d=b.documentElement;if(d&&c)if(a=Eb(a).height,Fb(b)&&d.scrollHeight)c=d.scrollHeight!=a?d.scrollHeight:d.offsetHeight;else{b=d.scrollHeight;var e=d.offsetHeight;d.clientHeight!=e&&(b=c.scrollHeight,e=c.offsetHeight);c=b>a?b>e?b:e:b<e?b:e}else c=0}return c};
g.M=function(a,b,c){var d=this.a,e=arguments,f=String(e[0]),k=e[1];if(!ub&&k&&(k.name||k.type)){f=["<",f];k.name&&f.push(' name="',ab(k.name),'"');if(k.type){f.push(' type="',ab(k.type),'"');var h={};Fa(h,k);delete h.type;k=h}f.push(">");f=f.join("")}f=V(d,f);k&&("string"===typeof k?f.className=k:v(k)?f.className=k.join(" "):Cb(f,k));2<e.length&&Ib(d,f,e,2);return f};g.X=T.prototype.M;g.Ua=function(a){return this.a.createTextNode(String(a))};
g.$=function(a,b,c){var d=this.a;c=!!c;for(var e=V(d,"TABLE"),f=e.appendChild(V(d,"TBODY")),k=0;k<a;k++){for(var h=V(d,"TR"),l=0;l<b;l++){var m=V(d,"TD");c&&Rb(m,"\u00a0");h.appendChild(m)}f.appendChild(h)}return e};g.xb=function(a){var b=this.a;var c=V(b,"DIV");H?(a=Xa(Ya,a),$a(c,a),c.removeChild(c.firstChild)):$a(c,a);if(1==c.childNodes.length)c=c.removeChild(c.firstChild);else{for(b=b.createDocumentFragment();c.firstChild;)b.appendChild(c.firstChild);c=b}return c};g.pa=function(){return Gb(this.a)};
g.ga=function(a){a=a||this.a;try{var b=a&&a.activeElement;var c=b&&b.nodeName?b:null}catch(d){c=null}return c};g.Ra=function(a,b){a.appendChild(b)};g.Qa=function(a,b){Ib(U(a),a,arguments,1)};g.Sa=function(a){if(1!=a.nodeType)return!1;switch(a.tagName){case "APPLET":case "AREA":case "BASE":case "BR":case "COL":case "COMMAND":case "EMBED":case "FRAME":case "HR":case "IMG":case "INPUT":case "IFRAME":case "ISINDEX":case "KEYGEN":case "LINK":case "NOFRAMES":case "NOSCRIPT":case "META":case "OBJECT":case "PARAM":case "SCRIPT":case "SOURCE":case "STYLE":case "TRACK":case "WBR":return!1}return!0};
g.vb=Lb;g.gb=function(a,b){b.parentNode&&b.parentNode.insertBefore(a,b)};g.fb=function(a,b){b.parentNode&&b.parentNode.insertBefore(a,b.nextSibling)};g.eb=function(a,b,c){a.insertBefore(b,a.childNodes[c]||null)};g.Wa=W;g.Xa=function(a,b){var c=b.parentNode;c&&c.replaceChild(a,b)};g.fa=function(a){var b,c=a.parentNode;if(c&&11!=c.nodeType){if(a.removeNode)return a.removeNode(!1);for(;b=a.firstChild;)c.insertBefore(b,a);return W(a)}};
g.la=function(a){return vb&&void 0!=a.children?a.children:Ba(a.childNodes,function(b){return 1==b.nodeType})};g.ua=function(a){return void 0!==a.firstElementChild?a.firstElementChild:Mb(a.firstChild,!0)};g.xa=function(a){return void 0!==a.lastElementChild?a.lastElementChild:Mb(a.lastChild,!1)};g.za=function(a){return void 0!==a.nextElementSibling?a.nextElementSibling:Mb(a.nextSibling,!0)};g.Ha=function(a){return void 0!==a.previousElementSibling?a.previousElementSibling:Mb(a.previousSibling,!1)};
g.Aa=function(a){if(!a)return null;if(a.firstChild)return a.firstChild;for(;a&&!a.nextSibling;)a=a.parentNode;return a?a.nextSibling:null};g.Ia=function(a){if(!a)return null;if(!a.previousSibling)return a.parentNode;for(a=a.previousSibling;a&&a.lastChild;)a=a.lastChild;return a};g.lb=Jb;g.hb=Nb;g.nb=function(a){return x(a)&&a.window==a};g.Ga=function(a){var b;if(xb&&!(H&&L("9")&&!L("10")&&u.SVGElement&&a instanceof u.SVGElement)&&(b=a.parentElement))return b;b=a.parentNode;return Nb(b)?b:null};
g.Ta=Ob;
g.Z=function(a,b){if(a==b)return 0;if(a.compareDocumentPosition)return a.compareDocumentPosition(b)&2?1:-1;if(H&&!(9<=Number(M))){if(9==a.nodeType)return-1;if(9==b.nodeType)return 1}if("sourceIndex"in a||a.parentNode&&"sourceIndex"in a.parentNode){var c=1==a.nodeType,d=1==b.nodeType;if(c&&d)return a.sourceIndex-b.sourceIndex;var e=a.parentNode,f=b.parentNode;return e==f?Qb(a,b):!c&&Ob(e,b)?-1*Pb(a,b):!d&&Ob(f,a)?Pb(b,a):(c?a.sourceIndex:e.sourceIndex)-(d?b.sourceIndex:f.sourceIndex)}d=U(a);c=d.createRange();
c.selectNode(a);c.collapse(!0);a=d.createRange();a.selectNode(b);a.collapse(!0);return c.compareBoundaryPoints(u.Range.START_TO_END,a)};g.ba=function(a){var b,c=arguments.length;if(!c)return null;if(1==c)return arguments[0];var d=[],e=Infinity;for(b=0;b<c;b++){for(var f=[],k=arguments[b];k;)f.unshift(k),k=k.parentNode;d.push(f);e=Math.min(e,f.length)}f=null;for(b=0;b<e;b++){k=d[0][b];for(var h=1;h<c;h++)if(k!=d[h][b])return f;f=k}return f};g.Fa=U;g.va=function(a){return a.contentDocument||a.contentWindow.document};
g.wa=function(a){try{var b;if(!(b=a.contentWindow)){if(a.contentDocument){var c=a.contentDocument;var d=c?Hb(c):window}else d=null;b=d}return b}catch(e){}return null};g.Db=Rb;g.Ea=function(a){if("outerHTML"in a)return a.outerHTML;var b=V(U(a),"DIV");b.appendChild(a.cloneNode(!0));return b.innerHTML};g.ca=function(a,b){var c=[];return Sb(a,b,c,!0)?c[0]:void 0};g.da=function(a,b){var c=[];Sb(a,b,c,!1);return c};g.kb=Vb;g.Bb=function(a,b){b?a.tabIndex=0:(a.tabIndex=-1,a.removeAttribute("tabIndex"))};
g.jb=function(a){var b;if((b="A"==a.tagName&&a.hasAttribute("href")||"INPUT"==a.tagName||"TEXTAREA"==a.tagName||"SELECT"==a.tagName||"BUTTON"==a.tagName?!a.disabled&&(!Wb(a)||Xb(a)):Vb(a))&&H){var c;!w(a.getBoundingClientRect)||H&&null==a.parentElement?c={height:a.offsetHeight,width:a.offsetWidth}:c=a.getBoundingClientRect();a=null!=c&&0<c.height&&0<c.width}else a=b;return a};g.Ma=Yb;g.Ca=function(a){return Yb(a).length};
g.Da=function(a,b){b=b||U(a).body;for(var c=[];a&&a!=b;){for(var d=a;d=d.previousSibling;)c.unshift(Yb(d));a=a.parentNode}return c.join("").replace(/^[\s\xa0]+/,"").replace(/ +/g," ").length};
g.Ba=function(a,b,c){a=[a];for(var d=0,e=null;0<a.length&&d<b;)if(e=a.pop(),!(e.nodeName in Tb))if(3==e.nodeType){var f=e.nodeValue.replace(/(\r\n|\r|\n)/g,"").replace(/ +/g," ");d+=f.length}else if(e.nodeName in Ub)d+=Ub[e.nodeName].length;else for(f=e.childNodes.length-1;0<=f;f--)a.push(e.childNodes[f]);x(c)&&(c.ub=e?e.nodeValue.length+b-d-1:0,c.node=e);return e};g.mb=Kb;g.ja=$b;g.ia=function(a,b,c){return $b(a,null,b,c)};g.ha=ac;g.ka=function(a){return a.getContext("2d")};var bc=!H||9<=Number(M),cc=!H||9<=Number(M),dc=H&&!L("9"),ec=function(){if(!u.addEventListener||!Object.defineProperty)return!1;var a=!1,b=Object.defineProperty({},"passive",{get:function(){a=!0}});try{u.addEventListener("test",ra,b),u.removeEventListener("test",ra,b)}catch(c){}return a}();function X(){this.l=this.l;this.b=this.b}g=X.prototype;g.l=!1;g.P=function(){return this.l};g.ma=X.prototype.P;g.H=function(){this.l||(this.l=!0,this.o())};g.tb=function(a){a=wa(fc,a);this.l?a():(this.b||(this.b=[]),this.b.push(a))};g.o=function(){if(this.b)for(;this.b.length;)this.b.shift()()};function fc(a){a&&"function"==typeof a.H&&a.H()};function gc(a,b){this.type=a;this.b=this.target=b;this.defaultPrevented=this.g=!1}gc.prototype.h=function(){this.g=!0};gc.prototype.c=function(){this.defaultPrevented=!0};var hc;hc=K?"webkitTransitionEnd":hb?"otransitionend":"transitionend";function Y(a,b){gc.call(this,a?a.type:"");this.relatedTarget=this.b=this.target=null;this.button=this.screenY=this.screenX=this.clientY=this.clientX=this.A=this.u=0;this.key="";this.j=this.s=0;this.metaKey=this.shiftKey=this.altKey=this.ctrlKey=!1;this.R=null;this.T=!1;this.pointerId=0;this.pointerType="";this.a=null;if(a){var c=this.type=a.type,d=a.changedTouches&&a.changedTouches.length?a.changedTouches[0]:null;this.target=a.target||a.srcElement;this.b=b;if(b=a.relatedTarget){if(J){a:{try{eb(b.nodeName);
var e=!0;break a}catch(f){}e=!1}e||(b=null)}}else"mouseover"==c?b=a.fromElement:"mouseout"==c&&(b=a.toElement);this.relatedTarget=b;d?(this.clientX=void 0!==d.clientX?d.clientX:d.pageX,this.clientY=void 0!==d.clientY?d.clientY:d.pageY,this.screenX=d.screenX||0,this.screenY=d.screenY||0):(this.u=K||void 0!==a.offsetX?a.offsetX:a.layerX,this.A=K||void 0!==a.offsetY?a.offsetY:a.layerY,this.clientX=void 0!==a.clientX?a.clientX:a.pageX,this.clientY=void 0!==a.clientY?a.clientY:a.pageY,this.screenX=a.screenX||
0,this.screenY=a.screenY||0);this.button=a.button;this.s=a.keyCode||0;this.key=a.key||"";this.j=a.charCode||("keypress"==c?a.keyCode:0);this.ctrlKey=a.ctrlKey;this.altKey=a.altKey;this.shiftKey=a.shiftKey;this.metaKey=a.metaKey;this.T=jb?a.metaKey:a.ctrlKey;this.pointerId=a.pointerId||0;this.pointerType="string"===typeof a.pointerType?a.pointerType:ic[a.pointerType]||"";this.R=a.state;this.a=a;a.defaultPrevented&&this.c()}}z(Y,gc);var jc=[1,4,2],ic={2:"touch",3:"pen",4:"mouse"};
Y.prototype.Gb=function(){return(bc?0==this.a.button:"click"==this.type?!0:!!(this.a.button&jc[0]))&&!(K&&jb&&this.ctrlKey)};Y.prototype.h=function(){Y.w.h.call(this);this.a.stopPropagation?this.a.stopPropagation():this.a.cancelBubble=!0};Y.prototype.c=function(){Y.w.c.call(this);var a=this.a;if(a.preventDefault)a.preventDefault();else if(a.returnValue=!1,dc)try{if(a.ctrlKey||112<=a.keyCode&&123>=a.keyCode)a.keyCode=-1}catch(b){}};Y.prototype.Eb=function(){return this.a};var kc="closure_listenable_"+(1E6*Math.random()|0),lc=0;function mc(a,b,c,d,e){this.listener=a;this.a=null;this.src=b;this.type=c;this.capture=!!d;this.b=e;this.key=++lc;this.v=this.B=!1}function nc(a){a.v=!0;a.listener=null;a.a=null;a.src=null;a.b=null};function oc(a){this.src=a;this.a={};this.b=0}oc.prototype.c=function(){var a=0,b;for(b in this.a)a+=this.a[b].length;return a};oc.prototype.add=function(a,b,c,d,e){var f=a.toString();a=this.a[f];a||(a=this.a[f]=[],this.b++);var k=pc(a,b,d,e);-1<k?(b=a[k],c||(b.B=!1)):(b=new mc(b,this.src,f,!!d,e),b.B=c,a.push(b));return b};function qc(a,b){var c=b.type;if(c in a.a){var d=a.a[c],e=za(d,b),f;(f=0<=e)&&Array.prototype.splice.call(d,e,1);f&&(nc(b),0==a.a[c].length&&(delete a.a[c],a.b--))}}
function rc(a,b,c,d,e){a=a.a[b.toString()];b=-1;a&&(b=pc(a,c,d,e));return-1<b?a[b]:null}function pc(a,b,c,d){for(var e=0;e<a.length;++e){var f=a[e];if(!f.v&&f.listener==b&&f.capture==!!c&&f.b==d)return e}return-1};var sc="closure_lm_"+(1E6*Math.random()|0),tc={},uc=0;function vc(a,b,c,d,e){if(d&&d.once)return wc(a,b,c,d,e);if(v(b)){for(var f=0;f<b.length;f++)vc(a,b[f],c,d,e);return null}c=xc(c);return a&&a[kc]?a.m(b,c,x(d)?!!d.capture:!!d,e):yc(a,b,c,!1,d,e)}
function yc(a,b,c,d,e,f){if(!b)throw Error("Invalid event type");var k=x(e)?!!e.capture:!!e,h=zc(a);h||(a[sc]=h=new oc(a));c=h.add(b,c,d,k,f);if(c.a)return c;d=Ac();c.a=d;d.src=a;d.listener=c;if(a.addEventListener)ec||(e=k),void 0===e&&(e=!1),a.addEventListener(b.toString(),d,e);else if(a.attachEvent)a.attachEvent(Bc(b.toString()),d);else if(a.addListener&&a.removeListener)a.addListener(d);else throw Error("addEventListener and attachEvent are unavailable.");uc++;return c}
function Ac(){var a=Cc,b=cc?function(c){return a.call(b.src,b.listener,c)}:function(c){c=a.call(b.src,b.listener,c);if(!c)return c};return b}function wc(a,b,c,d,e){if(v(b)){for(var f=0;f<b.length;f++)wc(a,b[f],c,d,e);return null}c=xc(c);return a&&a[kc]?a.g.add(String(b),c,!0,x(d)?!!d.capture:!!d,e):yc(a,b,c,!0,d,e)}
function Dc(a){if("number"!==typeof a&&a&&!a.v){var b=a.src;if(b&&b[kc])qc(b.g,a);else{var c=a.type,d=a.a;b.removeEventListener?b.removeEventListener(c,d,a.capture):b.detachEvent?b.detachEvent(Bc(c),d):b.addListener&&b.removeListener&&b.removeListener(d);uc--;(c=zc(b))?(qc(c,a),0==c.b&&(c.src=null,b[sc]=null)):nc(a)}}}function Bc(a){return a in tc?tc[a]:tc[a]="on"+a}
function Ec(a,b,c,d){var e=!0;if(a=zc(a))if(b=a.a[b.toString()])for(b=b.concat(),a=0;a<b.length;a++){var f=b[a];f&&f.capture==c&&!f.v&&(f=Fc(f,d),e=e&&!1!==f)}return e}function Fc(a,b){var c=a.listener,d=a.b||a.src;a.B&&Dc(a);return c.call(d,b)}
function Cc(a,b){if(a.v)return!0;if(!cc){if(!b)a:{b=["window","event"];for(var c=u,d=0;d<b.length;d++)if(c=c[b[d]],null==c){b=null;break a}b=c}d=b;b=new Y(d,this);c=!0;if(!(0>d.keyCode||void 0!=d.returnValue)){a:{var e=!1;if(0==d.keyCode)try{d.keyCode=-1;break a}catch(k){e=!0}if(e||void 0==d.returnValue)d.returnValue=!0}d=[];for(e=b.b;e;e=e.parentNode)d.push(e);a=a.type;for(e=d.length-1;!b.g&&0<=e;e--){b.b=d[e];var f=Ec(d[e],a,!0,b);c=c&&f}for(e=0;!b.g&&e<d.length;e++)b.b=d[e],f=Ec(d[e],a,!1,b),c=
c&&f}return c}return Fc(a,new Y(b,this))}function zc(a){a=a[sc];return a instanceof oc?a:null}var Gc="__closure_events_fn_"+(1E9*Math.random()>>>0);function xc(a){if(w(a))return a;a[Gc]||(a[Gc]=function(b){return a.handleEvent(b)});return a[Gc]};function Hc(a){X.call(this);this.c=a;this.a={}}z(Hc,X);var Ic=[];g=Hc.prototype;g.m=function(a,b,c,d){return Jc(this,a,b,c,d)};g.pb=function(a,b,c,d,e){return Jc(this,a,b,c,d,e)};function Jc(a,b,c,d,e,f){v(c)||(c&&(Ic[0]=c.toString()),c=Ic);for(var k=0;k<c.length;k++){var h=vc(b,c[k],d||a.handleEvent,e||!1,f||a.c||a);if(!h)break;a.a[h.key]=h}return a}g.Za=function(a,b,c,d){return Kc(this,a,b,c,d)};g.ob=function(a,b,c,d,e){return Kc(this,a,b,c,d,e)};
function Kc(a,b,c,d,e,f){if(v(c))for(var k=0;k<c.length;k++)Kc(a,b,c[k],d,e,f);else{b=wc(b,c,d||a.handleEvent,e,f||a.c||a);if(!b)return a;a.a[b.key]=b}return a}g.qb=function(a,b,c,d){b.m(a,c,d,this.c||this);return this};g.rb=function(a,b,c,d,e){b.m(a,c,d,e||this.c||this);return this};g.Ya=function(){var a=0,b;for(b in this.a)Object.prototype.hasOwnProperty.call(this.a,b)&&a++;return a};
g.K=function(a,b,c,d,e){if(v(b))for(var f=0;f<b.length;f++)this.K(a,b[f],c,d,e);else c=c||this.handleEvent,d=x(d)?!!d.capture:!!d,e=e||this.c||this,c=xc(c),d=!!d,b=a&&a[kc]?rc(a.g,String(b),c,d,e):a?(a=zc(a))?rc(a,b,c,d,e):null:null,b&&(Dc(b),delete this.a[b.key])};g.Fb=function(a,b,c,d,e){b.K(a,c,d,e||this.c||this,this);return this};function Lc(a){Da(a.a,function(b,c){this.a.hasOwnProperty(c)&&Dc(b)},a);a.a={}}g.o=function(){Hc.w.o.call(this);Lc(this)};
g.handleEvent=function(){throw Error("EventHandler.handleEvent not implemented");};function Mc(a){try{var b=a.getBoundingClientRect()}catch(c){return{left:0,top:0,right:0,bottom:0}}H&&a.ownerDocument.body&&(a=a.ownerDocument,b.left-=a.documentElement.clientLeft+a.body.clientLeft,b.top-=a.documentElement.clientTop+a.body.clientTop);return b}
function Nc(a){var b=U(a),c=new Q(0,0);var d=b?U(b):document;d=!H||9<=Number(M)||Fb(S(d).a)?d.documentElement:d.body;if(a==d)return c;a=Mc(a);d=S(b).a;b=Gb(d);d=Hb(d);b=H&&L("10")&&d.pageYOffset!=b.scrollTop?new Q(b.scrollLeft,b.scrollTop):new Q(d.pageXOffset||b.scrollLeft,d.pageYOffset||b.scrollTop);c.x=a.left+b.x;c.a=a.top+b.a;return c}
function Oc(a){var b=Pc;a:{var c=U(a);if(c.defaultView&&c.defaultView.getComputedStyle&&(c=c.defaultView.getComputedStyle(a,null))){c=c.display||c.getPropertyValue("display")||"";break a}c=""}c||(c=a.currentStyle?a.currentStyle.display:null);if("none"!=(c||a.style&&a.style.display))return b(a);c=a.style;var d=c.display,e=c.visibility,f=c.position;c.visibility="hidden";c.position="absolute";c.display="inline";a=b(a);c.display=d;c.position=f;c.visibility=e;return a}
function Pc(a){var b=a.offsetWidth,c=a.offsetHeight,d=K&&!b&&!c;return(void 0===b||d)&&a.getBoundingClientRect?(a=Mc(a),new R(a.right-a.left,a.bottom-a.top)):new R(b,c)};function Qc(a,b){if(!w(a))if(a&&"function"==typeof a.handleEvent)a=y(a.handleEvent,a);else throw Error("Invalid listener argument");return 2147483647<Number(b)?-1:u.setTimeout(a,b||0)};function Rc(a,b,c){X.call(this);this.A=null!=c?y(a,c):a;this.u=b;this.s=y(this.S,this);this.c=!1;this.g=0;this.h=this.a=null;this.j=[]}z(Rc,X);g=Rc.prototype;g.I=function(a){this.j=arguments;this.c=!1;this.a?this.h=xa()+this.u:this.a=Qc(this.s,this.u)};g.Oa=function(){++this.g};g.Pa=function(){this.g&&(--this.g,!this.g&&this.c&&(this.c=!1,this.A.apply(null,this.j)))};g.o=function(){this.a&&(u.clearTimeout(this.a),this.a=null);this.h=null;this.c=!1;this.j=[];Rc.w.o.call(this)};
g.S=function(){this.h?(this.a=Qc(this.s,this.h-xa()),this.h=null):(this.a=null,this.g?this.c=!0:(this.c=!1,this.A.apply(null,this.j)))};function Sc(a){a=(a||Tc).U;a=null!=a&&a.D===bb?a:a instanceof C?rb(D(a).toString(),a.a()):rb(ab(String(String(a))),qb(a));var b=rb('<span class="devsite-tooltip-msg">'+a+"</span>");a=S();a=V(a.a,"DIV");if(x(b))if(b instanceof G){if(b.D!==bb)throw Error("Sanitized content was not of kind HTML.");b=F(b.toString(),b.C||null)}else b=E("zSoyz");else b=E(String(b));$a(a,b);1==a.childNodes.length&&(b=a.firstChild,1==b.nodeType&&(a=b));return a}var Tc={};var Uc=["dl.google.com"],Vc="abc.xyz admob.com android.com blogger.com blogspot.com chrome.com chromium.org domains.google doubleclick.com feedburner.com g.co ggpht.com gmail.com gmodules.com goo.gl google.com google.org googleapis.com googleapps.com googlecode.com googledrive.com googlemail.com googlesource.com googlesyndication.com googletagmanager.com googleusercontent.com gv.com keyhole.com madewithcode.com panoramio.com urchin.com withgoogle.com youtu.be youtube.com ytimg.com".split(" ");
function Z(){var a=P.call(this)||this;a.b=new Hc;a.a=null;a.c=null;a.h=new Rc(function(){return Wc(a)},250);return a}ja(Z,P);Z.prototype.connectedCallback=function(){document.body.hasAttribute("touch")?W(this):(Xc(this),this.h.I())};Z.prototype.disconnectedCallback=function(){P.prototype.disconnectedCallback.call(this);Lc(this.b)};
function Xc(a){a.b.m(document.body,"devsite-content-updated",function(){return a.h.I()});a.b.m(document.body,"onpointermove"in window?"pointermove":"mousemove",function(b){b=b.target;for(var c=!1;b;){b.hasAttribute&&(c=b.hasAttribute("tooltip")&&b.clientWidth<b.scrollWidth||b.hasAttribute("data-title")||b.hasAttribute("data-tooltip"));if(c)break;b=b.parentNode}b&&!b.hasAttribute("no-tooltip")?Yc(a,b):Zc(a)});a.b.m(document.body,["devsite-sticky-scroll","devsite-sticky-resize"],function(){return Zc(a)})}
function Yc(a,b){if(a.a!==b){Zc(a);var c=b.getAttribute("data-tooltip")||b.getAttribute("data-title")||b.textContent.trim(),d=Sc({U:c});d.style.opacity=0;document.body.appendChild(d);var e=Eb(window),f=Oc(b),k=Oc(d),h=Nc(b);c=h.a+f.height;f=h.x+f.width/2-k.width/2;k.width>e.width?f=0:(f=Math.max(f,8),e=e.width-(f+k.width+8),0>e&&(f=f+e-8));d.style.top=c+"px";d.style.left=f+"px";a.a=b;a.c=d;window.requestAnimationFrame(function(){d.style.opacity=1})}}
function Zc(a){if(a.a){a.a=null;var b=a.c;a.c=null;wc(b,hc,function(){W(b);Lb(b)});window.setTimeout(function(){W(b);Lb(b)},1E3);b.style.opacity=0}}
function Wc(a){Array.from(document.querySelectorAll(".devsite-article-body [title]")).forEach(function(b){b.setAttribute("data-title",b.getAttribute("title"));b.removeAttribute("title")});a.hasAttribute("blocked-link")&&Array.from(document.getElementsByTagName("a")).forEach(function(b){if(b.hasAttribute("href")){for(var c=(new URL(b.getAttribute("href"),document.location.origin)).hostname.replace("www.",""),d=0;d<Uc.length;d++)if(-1!==c.indexOf(Uc[d]))return;for(d=0;d<Vc.length;d++)if(-1!==c.indexOf(Vc[d])){b.setAttribute("data-title",
"This link may not be accessible in your region.");b.removeAttribute("title");break}}})}Z.prototype.disconnectedCallback=Z.prototype.disconnectedCallback;Z.prototype.connectedCallback=Z.prototype.connectedCallback;try{window.customElements.define("devsite-tooltip",Z)}catch(a){console.warn("devsite.app.customElement.DevsiteTooltip",a)};}).call(this);
