(function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
'use strict';var g,aa="function"==typeof Object.create?Object.create:function(a){function b(){}b.prototype=a;return new b},ba;if("function"==typeof Object.setPrototypeOf)ba=Object.setPrototypeOf;else{var ca;a:{var da={M:!0},ea={};try{ea.__proto__=da;ca=ea.M;break a}catch(a){}ca=!1}ba=ca?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var fa=ba;
function ha(a,b){a.prototype=aa(b.prototype);a.prototype.constructor=a;if(fa)fa(a,b);else for(var c in b)if("prototype"!=c)if(Object.defineProperties){var d=Object.getOwnPropertyDescriptor(b,c);d&&Object.defineProperty(a,c,d)}else a[c]=b[c];a.u=b.prototype}function ia(a){a=["object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global,a];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}return globalThis}
var ja=ia(this),ka="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)};function l(a,b){if(b){var c=ja;a=a.split(".");for(var d=0;d<a.length-1;d++){var e=a[d];e in c||(c[e]={});c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&ka(c,a,{configurable:!0,writable:!0,value:b})}}l("globalThis",function(a){return a||ja});
function la(a,b,c){if(null==a)throw new TypeError("The 'this' value for String.prototype."+c+" must not be null or undefined");if(b instanceof RegExp)throw new TypeError("First argument to String.prototype."+c+" must not be a regular expression");return a+""}l("String.prototype.startsWith",function(a){return a?a:function(b,c){var d=la(this,b,"startsWith"),e=d.length,f=b.length;c=Math.max(0,Math.min(c|0,d.length));for(var h=0;h<f&&c<e;)if(d[c++]!=b[h++])return!1;return h>=f}});
var ma=function(){function a(){function c(){}new c;Reflect.construct(c,[],function(){});return new c instanceof c}if("undefined"!=typeof Reflect&&Reflect.construct){if(a())return Reflect.construct;var b=Reflect.construct;return function(c,d,e){c=b(c,d);e&&Reflect.setPrototypeOf(c,e.prototype);return c}}return function(c,d,e){void 0===e&&(e=c);e=aa(e.prototype||Object.prototype);return Function.prototype.apply.call(c,e,d)||e}}();l("Reflect.construct",function(){return ma});
l("Object.setPrototypeOf",function(a){return a||fa});l("String.prototype.includes",function(a){return a?a:function(b,c){return-1!==la(this,b,"includes").indexOf(b,c||0)}});var m=this||self;function na(){}
function n(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b}function p(a){return"array"==n(a)}function q(a){var b=n(a);return"array"==b||"object"==b&&"number"==typeof a.length}function r(a){var b=typeof a;return"object"==b&&null!=a||"function"==b}function oa(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var d=c.slice();d.push.apply(d,arguments);return a.apply(this,d)}}
function t(a,b){function c(){}c.prototype=b.prototype;a.u=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.$=function(d,e,f){for(var h=Array(arguments.length-2),k=2;k<arguments.length;k++)h[k-2]=arguments[k];return b.prototype[e].apply(d,h)}};var pa;var qa=Array.prototype.indexOf?function(a,b){return Array.prototype.indexOf.call(a,b,void 0)}:function(a,b){if("string"===typeof a)return"string"!==typeof b||1!=b.length?-1:a.indexOf(b,0);for(var c=0;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},u=Array.prototype.forEach?function(a,b,c){Array.prototype.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,e="string"===typeof a?a.split(""):a,f=0;f<d;f++)f in e&&b.call(c,e[f],f,a)},ra=Array.prototype.filter?function(a,b){return Array.prototype.filter.call(a,
b,void 0)}:function(a,b){for(var c=a.length,d=[],e=0,f="string"===typeof a?a.split(""):a,h=0;h<c;h++)if(h in f){var k=f[h];b.call(void 0,k,h,a)&&(d[e++]=k)}return d};function sa(a){var b=a.length;if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]};function ta(a,b,c){for(var d in a)b.call(c,a[d],d,a)}function ua(a,b){for(var c in a)if(b.call(void 0,a[c],c,a))return!0;return!1}var va="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" ");function wa(a,b){for(var c,d,e=1;e<arguments.length;e++){d=arguments[e];for(c in d)a[c]=d[c];for(var f=0;f<va.length;f++)c=va[f],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}};var xa=String.prototype.trim?function(a){return a.trim()}:function(a){return/^[\s\xa0]*([\s\S]*?)[\s\xa0]*$/.exec(a)[1]};
function ya(a,b){if(b)a=a.replace(za,"&amp;").replace(Aa,"&lt;").replace(Ba,"&gt;").replace(Ca,"&quot;").replace(Da,"&#39;").replace(Ea,"&#0;");else{if(!Fa.test(a))return a;-1!=a.indexOf("&")&&(a=a.replace(za,"&amp;"));-1!=a.indexOf("<")&&(a=a.replace(Aa,"&lt;"));-1!=a.indexOf(">")&&(a=a.replace(Ba,"&gt;"));-1!=a.indexOf('"')&&(a=a.replace(Ca,"&quot;"));-1!=a.indexOf("'")&&(a=a.replace(Da,"&#39;"));-1!=a.indexOf("\x00")&&(a=a.replace(Ea,"&#0;"))}return a}
var za=/&/g,Aa=/</g,Ba=/>/g,Ca=/"/g,Da=/'/g,Ea=/\x00/g,Fa=/[\x00&<>"']/;function Ga(a,b){return a<b?-1:a>b?1:0};var v;a:{var Ha=m.navigator;if(Ha){var Ia=Ha.userAgent;if(Ia){v=Ia;break a}}v=""};function w(a,b){this.a=a===Ja&&b||"";this.b=Ka}g=w.prototype;g.s=!0;g.m=function(){return this.a.toString()};g.C=!0;g.i=function(){return 1};g.aa=function(a,b){var c=La.exec(Ma(this).toString()),d=c[3]||"";return new w(Ja,c[1]+Na("?",c[2]||"",a)+Na("#",d,b))};function Ma(a){return a instanceof w&&a.constructor===w&&a.b===Ka?a.a:"type_error:TrustedResourceUrl"}var La=/^([^?#]*)(\?[^#]*)?(#[\s\S]*)?/,Ka={};
function Na(a,b,c){if(null==c)return b;if("string"===typeof c)return c?a+encodeURIComponent(c):"";for(var d in c){var e=c[d];e=p(e)?e:[e];for(var f=0;f<e.length;f++){var h=e[f];null!=h&&(b||(b=a),b+=(b.length>a.length?"&":"")+encodeURIComponent(d)+"="+encodeURIComponent(String(h)))}}return b}var Ja={};function x(a,b){this.a=a===Oa&&b||"";this.b=Pa}x.prototype.s=!0;x.prototype.m=function(){return this.a.toString()};x.prototype.C=!0;x.prototype.i=function(){return 1};var Pa={},Oa={};function y(){this.a="";this.c=Qa;this.b=null}y.prototype.C=!0;y.prototype.i=function(){return this.b};y.prototype.s=!0;y.prototype.m=function(){return this.a.toString()};function z(a){return a instanceof y&&a.constructor===y&&a.c===Qa?a.a:"type_error:SafeHtml"}function A(a){if(a instanceof y)return a;var b="object"==typeof a,c=null;b&&a.C&&(c=a.i());a=ya(b&&a.s?a.m():String(a));return B(a,c)}
function Ra(a){function b(f){p(f)?u(f,b):(f=A(f),e.push(z(f).toString()),f=f.i(),0==d?d=f:0!=f&&d!=f&&(d=null))}var c=A(Sa),d=c.i(),e=[];u(a,b);return B(e.join(z(c).toString()),d)}function Ta(a){return Ra(Array.prototype.slice.call(arguments))}var Qa={};function B(a,b){var c=new y;c.a=a;c.b=b;return c}B("<!DOCTYPE html>",0);var Sa=B("",0),Ua=B("<br>",0);var Va=function(a){var b=!1,c;return function(){b||(c=a(),b=!0);return c}}(function(){var a=document.createElement("div"),b=document.createElement("div");b.appendChild(document.createElement("div"));a.appendChild(b);b=a.firstChild.firstChild;a.innerHTML=z(Sa);return!b.parentElement});function Wa(a,b){if(Va())for(;a.lastChild;)a.removeChild(a.lastChild);a.innerHTML=z(b)};function C(a){return a=ya(a,void 0)};var D="StopIteration"in m?m.StopIteration:{message:"StopIteration",stack:""};function E(){}E.prototype.a=function(){throw D;};E.prototype.j=function(){return this};function Xa(a){if(a instanceof E)return a;if("function"==typeof a.j)return a.j(!1);if(q(a)){var b=0,c=new E;c.a=function(){for(;;){if(b>=a.length)throw D;if(b in a)return a[b++];b++}};return c}throw Error("Not implemented");}
function Ya(a,b){if(q(a))try{u(a,b,void 0)}catch(c){if(c!==D)throw c;}else{a=Xa(a);try{for(;;)b.call(void 0,a.a(),void 0,a)}catch(c){if(c!==D)throw c;}}}function Za(a){if(q(a))return sa(a);a=Xa(a);var b=[];Ya(a,function(c){b.push(c)});return b};var F={},$a={},ab={};function G(){throw Error("Do not instantiate directly");}G.prototype.w=null;G.prototype.toString=function(){return this.G};G.prototype.a=function(){if(this.f!==$a)throw Error("Sanitized content was not of kind URI.");return new x(Oa,this.toString())};function bb(){G.call(this)}t(bb,G);bb.prototype.f=F;function cb(a){cb[" "](a);return a}cb[" "]=na;function db(a,b){var c=eb;return Object.prototype.hasOwnProperty.call(c,a)?c[a]:c[a]=b(a)};var fb=-1!=v.indexOf("Opera"),H=-1!=v.indexOf("Trident")||-1!=v.indexOf("MSIE"),gb=-1!=v.indexOf("Edge"),hb=-1!=v.indexOf("Gecko")&&!(-1!=v.toLowerCase().indexOf("webkit")&&-1==v.indexOf("Edge"))&&!(-1!=v.indexOf("Trident")||-1!=v.indexOf("MSIE"))&&-1==v.indexOf("Edge"),I=-1!=v.toLowerCase().indexOf("webkit")&&-1==v.indexOf("Edge"),ib=-1!=v.indexOf("Macintosh");function jb(){var a=m.document;return a?a.documentMode:void 0}var kb;
a:{var lb="",mb=function(){var a=v;if(hb)return/rv:([^\);]+)(\)|;)/.exec(a);if(gb)return/Edge\/([\d\.]+)/.exec(a);if(H)return/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/.exec(a);if(I)return/WebKit\/(\S+)/.exec(a);if(fb)return/(?:Version)[ \/]?(\S+)/.exec(a)}();mb&&(lb=mb?mb[1]:"");if(H){var nb=jb();if(null!=nb&&nb>parseFloat(lb)){kb=String(nb);break a}}kb=lb}var ob=kb,eb={};
function J(a){return db(a,function(){for(var b=0,c=xa(String(ob)).split("."),d=xa(String(a)).split("."),e=Math.max(c.length,d.length),f=0;0==b&&f<e;f++){var h=c[f]||"",k=d[f]||"";do{h=/(\d*)(\D*)(.*)/.exec(h)||["","","",""];k=/(\d*)(\D*)(.*)/.exec(k)||["","","",""];if(0==h[0].length&&0==k[0].length)break;b=Ga(0==h[1].length?0:parseInt(h[1],10),0==k[1].length?0:parseInt(k[1],10))||Ga(0==h[2].length,0==k[2].length)||Ga(h[2],k[2]);h=h[3];k=k[3]}while(0==b)}return 0<=b})}var K;K=m.document&&H?jb():void 0;function pb(a){if(null!=a)switch(a.w){case 1:return 1;case -1:return-1;case 0:return 0}return null}function qb(a){return null!=a&&a.f===F?a:a instanceof y?L(z(a).toString(),a.i()):L(C(String(String(a))),pb(a))}var L=function(a){function b(c){this.G=c}b.prototype=a.prototype;return function(c,d){c=new b(String(c));void 0!==d&&(c.w=d);return c}}(bb);function rb(a){return null!=a&&a.f===F?String(String(a.G).replace(sb,"").replace(tb,"&lt;")).replace(ub,vb):C(String(a))}
function wb(a){null!=a&&a.f===$a||null!=a&&a.f===ab?a=String(a).replace(xb,yb):a instanceof x?a=String(a instanceof x&&a.constructor===x&&a.b===Pa?a.a:"type_error:SafeUrl").replace(xb,yb):a instanceof w?a=String(Ma(a).toString()).replace(xb,yb):(a=String(a),a=zb.test(a)?a.replace(xb,yb):"about:invalid#zSoyz");return a}
var Ab={"\x00":"&#0;","\t":"&#9;","\n":"&#10;","\x0B":"&#11;","\f":"&#12;","\r":"&#13;"," ":"&#32;",'"':"&quot;","&":"&amp;","'":"&#39;","-":"&#45;","/":"&#47;","<":"&lt;","=":"&#61;",">":"&gt;","`":"&#96;","\u0085":"&#133;","\u00a0":"&#160;","\u2028":"&#8232;","\u2029":"&#8233;"};function vb(a){return Ab[a]}
var Bb={"\x00":"%00","\u0001":"%01","\u0002":"%02","\u0003":"%03","\u0004":"%04","\u0005":"%05","\u0006":"%06","\u0007":"%07","\b":"%08","\t":"%09","\n":"%0A","\x0B":"%0B","\f":"%0C","\r":"%0D","\u000e":"%0E","\u000f":"%0F","\u0010":"%10","\u0011":"%11","\u0012":"%12","\u0013":"%13","\u0014":"%14","\u0015":"%15","\u0016":"%16","\u0017":"%17","\u0018":"%18","\u0019":"%19","\u001a":"%1A","\u001b":"%1B","\u001c":"%1C","\u001d":"%1D","\u001e":"%1E","\u001f":"%1F"," ":"%20",'"':"%22","'":"%27","(":"%28",
")":"%29","<":"%3C",">":"%3E","\\":"%5C","{":"%7B","}":"%7D","\u007f":"%7F","\u0085":"%C2%85","\u00a0":"%C2%A0","\u2028":"%E2%80%A8","\u2029":"%E2%80%A9","\uff01":"%EF%BC%81","\uff03":"%EF%BC%83","\uff04":"%EF%BC%84","\uff06":"%EF%BC%86","\uff07":"%EF%BC%87","\uff08":"%EF%BC%88","\uff09":"%EF%BC%89","\uff0a":"%EF%BC%8A","\uff0b":"%EF%BC%8B","\uff0c":"%EF%BC%8C","\uff0f":"%EF%BC%8F","\uff1a":"%EF%BC%9A","\uff1b":"%EF%BC%9B","\uff1d":"%EF%BC%9D","\uff1f":"%EF%BC%9F","\uff20":"%EF%BC%A0","\uff3b":"%EF%BC%BB",
"\uff3d":"%EF%BC%BD"};function yb(a){return Bb[a]}var ub=/[\x00\x22\x27\x3c\x3e]/g,xb=/[\x00- \x22\x27-\x29\x3c\x3e\\\x7b\x7d\x7f\x85\xa0\u2028\u2029\uff01\uff03\uff04\uff06-\uff0c\uff0f\uff1a\uff1b\uff1d\uff1f\uff20\uff3b\uff3d]/g,zb=/^(?![^#?]*\/(?:\.|%2E){2}(?:[\/?#]|$))(?:(?:https?|mailto):|[^&:\/?#]*(?:[\/?#]|$))/i,sb=/<(?:!|\/?([a-zA-Z][a-zA-Z0-9:\-]*))(?:[^>'"]|"[^"]*"|'[^']*')*>/g,tb=/</g;function Cb(){return L('<div class="devsite-snackbar-snack" type="loading"><div class="devsite-snackbar-inner"><div class="devsite-snackbar-message">Loading</div><div class="devsite-snackbar-action"><devsite-spinner single-color="#ffffff"></devsite-spinner></div></div></div>')}
function Db(){return L('<div class="devsite-snackbar-snack" type="refresh"><div class="devsite-snackbar-inner"><div class="devsite-snackbar-message">A new version is available</div><button class="devsite-snackbar-action">Refresh</button></div></div>')}
function Eb(){return L('<div class="devsite-snackbar-snack" type="error"><div class="devsite-snackbar-inner"><div class="devsite-snackbar-message">Something went wrong. Please try again.</div><button class="devsite-snackbar-action">Retry</button></div></div>')}function Fb(){return L('<div class="devsite-snackbar-snack" type="copied-to-clipboard"><div class="devsite-snackbar-inner"><div class="devsite-snackbar-message">Copied to clipboard</div></div></div>')}
function Gb(a){a=a||{};a=a.D;a='<div class="devsite-snackbar-snack" type="cookie-notification"><div class="devsite-snackbar-inner"><div class="devsite-snackbar-message">This site uses cookies from Google to deliver its services and to analyze traffic.</div><a href="'+((a?rb(wb(a)):"//policies.google.com/technologies/cookies")+'" class="devsite-snackbar-link button">');return L(a+'More details</a><button class="devsite-snackbar-action">OK</button></div></div>')}
function Hb(){return L('<div class="devsite-snackbar-snack" type="support-attachment-error"><div class="devsite-snackbar-inner"><div class="devsite-snackbar-message">Unsupported file type.</div><button class="devsite-snackbar-action">OK</button></div></div>')}
function Ib(a){var b=a.message,c=a.link,d=a.U;a='<div class="devsite-snackbar-snack" type="'+rb(a.W)+'"><div class="devsite-snackbar-inner"><div class="devsite-snackbar-message">'+qb(b)+'</div><button class="devsite-snackbar-action">';a=a+'No, thanks</button><a href="'+(rb(wb(c))+'" class="devsite-snackbar-link button" target="_blank">');a=d?a+qb(d):a+"OK";return L(a+"</a></div></div>")}
function Jb(a){var b=a.V;a='<div class="devsite-snackbar-snack" type="custom"><div class="devsite-snackbar-inner"><div class="devsite-snackbar-message">'+qb(a.message)+"</div>";b&&(a+='<button class="devsite-snackbar-action">OK</button>');return L(a+"</div></div>")};var Kb=!/^\s*class\s*\{\s*\}\s*$/.test(function(){}.toString());/*

 Copyright (c) 2016 The Polymer Project Authors. All rights reserved.
 This code may only be used under the BSD style license found at http://polymer.github.io/LICENSE.txt
 The complete set of authors may be found at http://polymer.github.io/AUTHORS.txt
 The complete set of contributors may be found at http://polymer.github.io/CONTRIBUTORS.txt
 Code distributed by Google as part of the polymer project is also
 subject to an additional IP rights grant found at http://polymer.github.io/PATENTS.txt
*/
(function(){if(Kb&&!HTMLElement.es5Shimmed&&void 0!==window.Reflect&&void 0!==window.customElements&&!window.customElements.polyfillWrapFlushCallback){var a=HTMLElement;window.HTMLElement=function(){return Reflect.construct(a,[],this.constructor)};HTMLElement.prototype=a.prototype;HTMLElement.prototype.constructor=HTMLElement;HTMLElement.es5Shimmed=!0;Object.setPrototypeOf(HTMLElement,a)}})();function N(a){var b=HTMLElement.call(this)||this;a&&("string"===typeof a&&(a=[a]),document.body.dispatchEvent(new CustomEvent("devsite-load-custom-elements",{bubbles:!0,detail:a})));return b}ha(N,HTMLElement);N.prototype.L=function(){console.warn(this.tagName,"has not implemented update")};N.prototype.H=function(a){a=void 0===a?"":a;return document.createRange().createContextualFragment(a||"")};
N.prototype.K=function(a,b,c){a&&b?a.parentNode.replaceChild(document.importNode(b,!0),a):!b&&a?a.parentNode.removeChild(a):!a&&b&&(c?(a=document.importNode(b,!0),c.parentElement.insertBefore(a,c.nextSibling)):this.appendChild(document.importNode(b,!0)))};var Lb=!H||9<=Number(K),Mb=!hb&&!H||H&&9<=Number(K)||hb&&J("1.9.1"),Nb=H&&!J("9"),Ob=H||fb||I;function O(a,b){this.a=void 0!==a?a:0;this.b=void 0!==b?b:0}g=O.prototype;g.gb=function(){return new O(this.a,this.b)};g.da=function(a){return a instanceof O&&(this==a?!0:this&&a?this.a==a.a&&this.b==a.b:!1)};g.ceil=function(){this.a=Math.ceil(this.a);this.b=Math.ceil(this.b);return this};g.floor=function(){this.a=Math.floor(this.a);this.b=Math.floor(this.b);return this};g.round=function(){this.a=Math.round(this.a);this.b=Math.round(this.b);return this};
g.ib=function(a,b){a instanceof O?(this.a+=a.a,this.b+=a.b):(this.a+=Number(a),"number"===typeof b&&(this.b+=b));return this};g.hb=function(a,b){this.a*=a;this.b*="number"===typeof b?b:a;return this};g.Eb=function(a,b){a=a*Math.PI/180;b=b||new O(0,0);var c=this.a,d=this.b,e=Math.cos(a);a=Math.sin(a);this.a=(c-b.a)*e-(d-b.b)*a+b.a;this.b=(c-b.a)*a+(d-b.b)*e+b.b};function Pb(a,b){this.width=a;this.height=b}g=Pb.prototype;g.jb=function(){return new Pb(this.width,this.height)};g.Da=function(){return Math.max(this.width,this.height)};g.Qa=function(){return Math.min(this.width,this.height)};g.Ab=function(){return 2*(this.width+this.height)};g.aspectRatio=function(){return this.width/this.height};g.qb=function(){return!(this.width*this.height)};g.ceil=function(){this.width=Math.ceil(this.width);this.height=Math.ceil(this.height);return this};
g.ha=function(a){return this.width<=a.width&&this.height<=a.height};g.floor=function(){this.width=Math.floor(this.width);this.height=Math.floor(this.height);return this};g.round=function(){this.width=Math.round(this.width);this.height=Math.round(this.height);return this};function Qb(a,b){a.width*=b;a.height*=b;return a}g.Gb=function(a){a=this.aspectRatio()<=a.aspectRatio()?a.width/this.width:a.height/this.height;return Qb(this,a)};
g.Hb=function(a){a=this.aspectRatio()>a.aspectRatio()?a.width/this.width:a.height/this.height;return Qb(this,a)};function Rb(a){return a?new P(Q(a)):pa||(pa=new P)}function Sb(a,b){var c=b||document,d=null;c.getElementsByClassName?d=c.getElementsByClassName(a)[0]:d=Tb(document,"*",a,b);return d||null}
function Ub(a,b,c,d){a=d||a;var e=b&&"*"!=b?String(b).toUpperCase():"";if(a.querySelectorAll&&a.querySelector&&(e||c))return a.querySelectorAll(e+(c?"."+c:""));if(c&&a.getElementsByClassName){b=a.getElementsByClassName(c);if(e){a={};for(var f=d=0,h;h=b[f];f++)e==h.nodeName&&(a[d++]=h);a.length=d;return a}return b}b=a.getElementsByTagName(e||"*");if(c){a={};for(f=d=0;h=b[f];f++){e=h.className;var k;if(k="function"==typeof e.split)k=0<=qa(e.split(/\s+/),c);k&&(a[d++]=h)}a.length=d;return a}return b}
function Tb(a,b,c,d){var e=d||a,f=b&&"*"!=b?String(b).toUpperCase():"";return e.querySelectorAll&&e.querySelector&&(f||c)?e.querySelector(f+(c?"."+c:"")):Ub(a,b,c,d)[0]||null}function Vb(a,b){ta(b,function(c,d){c&&"object"==typeof c&&c.s&&(c=c.m());"style"==d?a.style.cssText=c:"class"==d?a.className=c:"for"==d?a.htmlFor=c:Wb.hasOwnProperty(d)?a.setAttribute(Wb[d],c):0==d.lastIndexOf("aria-",0)||0==d.lastIndexOf("data-",0)?a.setAttribute(d,c):a[d]=c})}
var Wb={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",frameborder:"frameBorder",height:"height",maxlength:"maxLength",nonce:"nonce",role:"role",rowspan:"rowSpan",type:"type",usemap:"useMap",valign:"vAlign",width:"width"};function Xb(a){a=a.document;a=Yb(a)?a.documentElement:a.body;return new Pb(a.clientWidth,a.clientHeight)}function Zb(a){return a.scrollingElement?a.scrollingElement:!I&&Yb(a)?a.documentElement:a.body||a.documentElement}
function $b(a){return a.parentWindow||a.defaultView}function ac(a,b,c,d){function e(h){h&&b.appendChild("string"===typeof h?a.createTextNode(h):h)}for(;d<c.length;d++){var f=c[d];q(f)&&!cc(f)?u(dc(f)?sa(f):f,e):e(f)}}function R(a,b){b=String(b);"application/xhtml+xml"===a.contentType&&(b=b.toLowerCase());return a.createElement(b)}function Yb(a){return"CSS1Compat"==a.compatMode}function ec(a){for(var b;b=a.firstChild;)a.removeChild(b)}
function fc(a){return a&&a.parentNode?a.parentNode.removeChild(a):null}function gc(a,b){for(;a&&1!=a.nodeType;)a=b?a.nextSibling:a.previousSibling;return a}function cc(a){return r(a)&&0<a.nodeType}function hc(a){return r(a)&&1==a.nodeType}function ic(a,b){if(!a||!b)return!1;if(a.contains&&1==b.nodeType)return a==b||a.contains(b);if("undefined"!=typeof a.compareDocumentPosition)return a==b||!!(a.compareDocumentPosition(b)&16);for(;b&&a!=b;)b=b.parentNode;return b==a}
function jc(a,b){var c=a.parentNode;if(c==b)return-1;for(;b.parentNode!=c;)b=b.parentNode;return kc(b,a)}function kc(a,b){for(;b=b.previousSibling;)if(b==a)return-1;return 1}function Q(a){return 9==a.nodeType?a:a.ownerDocument||a.document}
function lc(a,b){if("textContent"in a)a.textContent=b;else if(3==a.nodeType)a.data=String(b);else if(a.firstChild&&3==a.firstChild.nodeType){for(;a.lastChild!=a.firstChild;)a.removeChild(a.lastChild);a.firstChild.data=String(b)}else ec(a),a.appendChild(Q(a).createTextNode(String(b)))}function mc(a,b,c,d){if(null!=a)for(a=a.firstChild;a;){if(b(a)&&(c.push(a),d)||mc(a,b,c,d))return!0;a=a.nextSibling}return!1}var nc={SCRIPT:1,STYLE:1,HEAD:1,IFRAME:1,OBJECT:1},oc={IMG:" ",BR:"\n"};
function pc(a){return qc(a)&&rc(a)}function qc(a){return H&&!J("9")?(a=a.getAttributeNode("tabindex"),null!=a&&a.specified):a.hasAttribute("tabindex")}function rc(a){a=a.tabIndex;return"number"===typeof a&&0<=a&&32768>a}function sc(a){if(Nb&&null!==a&&"innerText"in a)a=a.innerText.replace(/(\r\n|\r|\n)/g,"\n");else{var b=[];tc(a,b,!0);a=b.join("")}a=a.replace(/ \xAD /g," ").replace(/\xAD/g,"");a=a.replace(/\u200B/g,"");Nb||(a=a.replace(/ +/g," "));" "!=a&&(a=a.replace(/^\s*/,""));return a}
function tc(a,b,c){if(!(a.nodeName in nc))if(3==a.nodeType)c?b.push(String(a.nodeValue).replace(/(\r\n|\r|\n)/g,"")):b.push(a.nodeValue);else if(a.nodeName in oc)b.push(oc[a.nodeName]);else for(a=a.firstChild;a;)tc(a,b,c),a=a.nextSibling}function dc(a){if(a&&"number"==typeof a.length){if(r(a))return"function"==typeof a.item||"string"==typeof a.item;if("function"==n(a))return"function"==typeof a.item}return!1}
function uc(a,b,c,d){if(!b&&!c)return null;var e=b?String(b).toUpperCase():null;return vc(a,function(f){var h;(h=!e||f.nodeName==e)&&!(h=!c)&&(h="string"===typeof f.className)&&(h=0<=qa(f.className.split(/\s+/),c));return h},!0,d)}function vc(a,b,c,d){a&&!c&&(a=a.parentNode);for(c=0;a&&(null==d||c<=d);){if(b(a))return a;a=a.parentNode;c++}return null}function P(a){this.a=a||m.document||document}g=P.prototype;g.ua=Rb;g.Ib=function(a){this.a=a};g.qa=function(){return this.a};
g.P=function(a){return"string"===typeof a?this.a.getElementById(a):a};g.Oa=function(a){return"string"===typeof a?this.a.getElementById(a):a};g.X=P.prototype.P;g.Xa=function(a,b){return(b||this.a).getElementsByTagName(String(a))};g.R=function(a,b,c){return Ub(this.a,a,b,c)};g.wa=function(a,b,c){return Tb(this.a,a,b,c)};g.xa=function(a,b){var c=(b=b||this.a)||document;return c.querySelectorAll&&c.querySelector?c.querySelectorAll("."+a):Ub(document,"*",a,b)};g.va=function(a,b){return Sb(a,b||this.a)};
g.Pa=function(a,b){return Sb(a,b||this.a)};g.Y=P.prototype.R;g.Kb=Vb;g.Sa=function(a){return Xb(a||$b(this.a)||window)};g.ra=function(){var a=$b(this.a),b=a.document;var c=0;if(b){c=b.body;var d=b.documentElement;if(d&&c)if(a=Xb(a).height,Yb(b)&&d.scrollHeight)c=d.scrollHeight!=a?d.scrollHeight:d.offsetHeight;else{b=d.scrollHeight;var e=d.offsetHeight;d.clientHeight!=e&&(b=c.scrollHeight,e=c.offsetHeight);c=b>a?b>e?b:e:b<e?b:e}else c=0}return c};
g.N=function(a,b,c){var d=this.a,e=arguments,f=String(e[0]),h=e[1];if(!Lb&&h&&(h.name||h.type)){f=["<",f];h.name&&f.push(' name="',C(h.name),'"');if(h.type){f.push(' type="',C(h.type),'"');var k={};wa(k,h);delete k.type;h=k}f.push(">");f=f.join("")}f=R(d,f);h&&("string"===typeof h?f.className=h:p(h)?f.className=h.join(" "):Vb(f,h));2<e.length&&ac(d,f,e,2);return f};g.Z=P.prototype.N;g.Wa=function(a){return this.a.createTextNode(String(a))};
g.ca=function(a,b,c){var d=this.a;c=!!c;for(var e=R(d,"TABLE"),f=e.appendChild(R(d,"TBODY")),h=0;h<a;h++){for(var k=R(d,"TR"),M=0;M<b;M++){var bc=R(d,"TD");c&&lc(bc,"\u00a0");k.appendChild(bc)}f.appendChild(k)}return e};g.Fb=function(a){var b=this.a;var c=R(b,"DIV");H?(a=Ta(Ua,a),Wa(c,a),c.removeChild(c.firstChild)):Wa(c,a);if(1==c.childNodes.length)c=c.removeChild(c.firstChild);else{for(b=b.createDocumentFragment();c.firstChild;)b.appendChild(c.firstChild);c=b}return c};g.ob=function(){return Yb(this.a)};
g.ta=function(){return Zb(this.a)};g.sa=function(){var a=this.a,b=Zb(a);a=$b(a);return H&&J("10")&&a.pageYOffset!=b.scrollTop?new O(b.scrollLeft,b.scrollTop):new O(a.pageXOffset||b.scrollLeft,a.pageYOffset||b.scrollTop)};g.ja=function(a){a=a||this.a;try{var b=a&&a.activeElement;var c=b&&b.nodeName?b:null}catch(d){c=null}return c};g.Ua=function(a,b){a.appendChild(b)};g.Ta=function(a,b){ac(Q(a),a,arguments,1)};g.Va=function(a){if(1!=a.nodeType)return!1;switch(a.tagName){case "APPLET":case "AREA":case "BASE":case "BR":case "COL":case "COMMAND":case "EMBED":case "FRAME":case "HR":case "IMG":case "INPUT":case "IFRAME":case "ISINDEX":case "KEYGEN":case "LINK":case "NOFRAMES":case "NOSCRIPT":case "META":case "OBJECT":case "PARAM":case "SCRIPT":case "SOURCE":case "STYLE":case "TRACK":case "WBR":return!1}return!0};
g.Db=ec;g.mb=function(a,b){b.parentNode&&b.parentNode.insertBefore(a,b)};g.lb=function(a,b){b.parentNode&&b.parentNode.insertBefore(a,b.nextSibling)};g.kb=function(a,b,c){a.insertBefore(b,a.childNodes[c]||null)};g.Ya=fc;g.Za=function(a,b){var c=b.parentNode;c&&c.replaceChild(a,b)};g.ia=function(a){var b,c=a.parentNode;if(c&&11!=c.nodeType){if(a.removeNode)return a.removeNode(!1);for(;b=a.firstChild;)c.insertBefore(b,a);return fc(a)}};
g.oa=function(a){return Mb&&void 0!=a.children?a.children:ra(a.childNodes,function(b){return 1==b.nodeType})};g.ya=function(a){return void 0!==a.firstElementChild?a.firstElementChild:gc(a.firstChild,!0)};g.Ba=function(a){return void 0!==a.lastElementChild?a.lastElementChild:gc(a.lastChild,!1)};g.Ea=function(a){return void 0!==a.nextElementSibling?a.nextElementSibling:gc(a.nextSibling,!0)};g.Ma=function(a){return void 0!==a.previousElementSibling?a.previousElementSibling:gc(a.previousSibling,!1)};
g.Fa=function(a){if(!a)return null;if(a.firstChild)return a.firstChild;for(;a&&!a.nextSibling;)a=a.parentNode;return a?a.nextSibling:null};g.Na=function(a){if(!a)return null;if(!a.previousSibling)return a.parentNode;for(a=a.previousSibling;a&&a.lastChild;)a=a.lastChild;return a};g.tb=cc;g.pb=hc;g.vb=function(a){return r(a)&&a.window==a};g.La=function(a){var b;if(Ob&&!(H&&J("9")&&!J("10")&&m.SVGElement&&a instanceof m.SVGElement)&&(b=a.parentElement))return b;b=a.parentNode;return hc(b)?b:null};
g.contains=ic;
g.ba=function(a,b){if(a==b)return 0;if(a.compareDocumentPosition)return a.compareDocumentPosition(b)&2?1:-1;if(H&&!(9<=Number(K))){if(9==a.nodeType)return-1;if(9==b.nodeType)return 1}if("sourceIndex"in a||a.parentNode&&"sourceIndex"in a.parentNode){var c=1==a.nodeType,d=1==b.nodeType;if(c&&d)return a.sourceIndex-b.sourceIndex;var e=a.parentNode,f=b.parentNode;return e==f?kc(a,b):!c&&ic(e,b)?-1*jc(a,b):!d&&ic(f,a)?jc(b,a):(c?a.sourceIndex:e.sourceIndex)-(d?b.sourceIndex:f.sourceIndex)}d=Q(a);c=d.createRange();
c.selectNode(a);c.collapse(!0);a=d.createRange();a.selectNode(b);a.collapse(!0);return c.compareBoundaryPoints(m.Range.START_TO_END,a)};g.ea=function(a){var b,c=arguments.length;if(!c)return null;if(1==c)return arguments[0];var d=[],e=Infinity;for(b=0;b<c;b++){for(var f=[],h=arguments[b];h;)f.unshift(h),h=h.parentNode;d.push(f);e=Math.min(e,f.length)}f=null;for(b=0;b<e;b++){h=d[0][b];for(var k=1;k<c;k++)if(h!=d[k][b])return f;f=h}return f};g.Ka=Q;g.za=function(a){return a.contentDocument||a.contentWindow.document};
g.Aa=function(a){try{var b;if(!(b=a.contentWindow)){if(a.contentDocument){var c=a.contentDocument;var d=c?$b(c):window}else d=null;b=d}return b}catch(e){}return null};g.Lb=lc;g.Ja=function(a){if("outerHTML"in a)return a.outerHTML;var b=R(Q(a),"DIV");b.appendChild(a.cloneNode(!0));return b.innerHTML};g.fa=function(a,b){var c=[];return mc(a,b,c,!0)?c[0]:void 0};g.ga=function(a,b){var c=[];mc(a,b,c,!1);return c};g.sb=pc;g.Jb=function(a,b){b?a.tabIndex=0:(a.tabIndex=-1,a.removeAttribute("tabIndex"))};
g.rb=function(a){var b;if((b="A"==a.tagName&&a.hasAttribute("href")||"INPUT"==a.tagName||"TEXTAREA"==a.tagName||"SELECT"==a.tagName||"BUTTON"==a.tagName?!a.disabled&&(!qc(a)||rc(a)):pc(a))&&H){var c;"function"!=n(a.getBoundingClientRect)||H&&null==a.parentElement?c={height:a.offsetHeight,width:a.offsetWidth}:c=a.getBoundingClientRect();a=null!=c&&0<c.height&&0<c.width}else a=b;return a};g.Ra=sc;g.Ha=function(a){return sc(a).length};
g.Ia=function(a,b){b=b||Q(a).body;for(var c=[];a&&a!=b;){for(var d=a;d=d.previousSibling;)c.unshift(sc(d));a=a.parentNode}return c.join("").replace(/^[\s\xa0]+/,"").replace(/ +/g," ").length};
g.Ga=function(a,b,c){a=[a];for(var d=0,e=null;0<a.length&&d<b;)if(e=a.pop(),!(e.nodeName in nc))if(3==e.nodeType){var f=e.nodeValue.replace(/(\r\n|\r|\n)/g,"").replace(/ +/g," ");d+=f.length}else if(e.nodeName in oc)d+=oc[e.nodeName].length;else for(f=e.childNodes.length-1;0<=f;f--)a.push(e.childNodes[f]);r(c)&&(c.Cb=e?e.nodeValue.length+b-d-1:0,c.node=e);return e};g.ub=dc;g.ma=uc;g.la=function(a,b,c){return uc(a,null,b,c)};g.ka=vc;g.na=function(a){return a.getContext("2d")};var wc=!H||9<=Number(K),xc=!H||9<=Number(K),yc=H&&!J("9"),zc=function(){if(!m.addEventListener||!Object.defineProperty)return!1;var a=!1,b=Object.defineProperty({},"passive",{get:function(){a=!0}});try{m.addEventListener("test",na,b),m.removeEventListener("test",na,b)}catch(c){}return a}();function Ac(){this.g=this.g;this.b=this.b}g=Ac.prototype;g.g=!1;g.T=function(){return this.g};g.pa=Ac.prototype.T;g.F=function(){this.g||(this.g=!0,this.A())};g.Bb=function(a){a=oa(Bc,a);this.g?a():(this.b||(this.b=[]),this.b.push(a))};g.A=function(){if(this.b)for(;this.b.length;)this.b.shift()()};function Bc(a){a&&"function"==typeof a.F&&a.F()};function Cc(a,b){this.type=a;this.b=this.target=b;this.K=this.h=!1}Cc.prototype.stopPropagation=function(){this.h=!0};Cc.prototype.c=function(){this.K=!0};var Dc;Dc=I?"webkitTransitionEnd":fb?"otransitionend":"transitionend";function S(a,b){Cc.call(this,a?a.type:"");this.relatedTarget=this.b=this.target=null;this.button=this.screenY=this.screenX=this.clientY=this.clientX=this.I=this.H=0;this.key="";this.o=this.B=0;this.metaKey=this.shiftKey=this.altKey=this.ctrlKey=!1;this.J=null;this.L=!1;this.pointerId=0;this.pointerType="";this.a=null;if(a){var c=this.type=a.type,d=a.changedTouches&&a.changedTouches.length?a.changedTouches[0]:null;this.target=a.target||a.srcElement;this.b=b;if(b=a.relatedTarget){if(hb){a:{try{cb(b.nodeName);
var e=!0;break a}catch(f){}e=!1}e||(b=null)}}else"mouseover"==c?b=a.fromElement:"mouseout"==c&&(b=a.toElement);this.relatedTarget=b;d?(this.clientX=void 0!==d.clientX?d.clientX:d.pageX,this.clientY=void 0!==d.clientY?d.clientY:d.pageY,this.screenX=d.screenX||0,this.screenY=d.screenY||0):(this.H=I||void 0!==a.offsetX?a.offsetX:a.layerX,this.I=I||void 0!==a.offsetY?a.offsetY:a.layerY,this.clientX=void 0!==a.clientX?a.clientX:a.pageX,this.clientY=void 0!==a.clientY?a.clientY:a.pageY,this.screenX=a.screenX||
0,this.screenY=a.screenY||0);this.button=a.button;this.B=a.keyCode||0;this.key=a.key||"";this.o=a.charCode||("keypress"==c?a.keyCode:0);this.ctrlKey=a.ctrlKey;this.altKey=a.altKey;this.shiftKey=a.shiftKey;this.metaKey=a.metaKey;this.L=ib?a.metaKey:a.ctrlKey;this.pointerId=a.pointerId||0;this.pointerType="string"===typeof a.pointerType?a.pointerType:Ec[a.pointerType]||"";this.J=a.state;this.a=a;a.defaultPrevented&&this.c()}}t(S,Cc);var Fc=[1,4,2],Ec={2:"touch",3:"pen",4:"mouse"};
S.prototype.Mb=function(){return(wc?0==this.a.button:"click"==this.type?!0:!!(this.a.button&Fc[0]))&&!(I&&ib&&this.ctrlKey)};S.prototype.stopPropagation=function(){S.u.stopPropagation.call(this);this.a.stopPropagation?this.a.stopPropagation():this.a.cancelBubble=!0};S.prototype.c=function(){S.u.c.call(this);var a=this.a;if(a.preventDefault)a.preventDefault();else if(a.returnValue=!1,yc)try{if(a.ctrlKey||112<=a.keyCode&&123>=a.keyCode)a.keyCode=-1}catch(b){}};var Gc="closure_listenable_"+(1E6*Math.random()|0),Hc=0;function Ic(a,b,c,d,e){this.listener=a;this.a=null;this.src=b;this.type=c;this.capture=!!d;this.b=e;this.key=++Hc;this.l=this.v=!1}function Jc(a){a.l=!0;a.listener=null;a.a=null;a.src=null;a.b=null};function Kc(a){this.src=a;this.a={};this.b=0}g=Kc.prototype;g.bb=function(){var a=0,b;for(b in this.a)a+=this.a[b].length;return a};g.add=function(a,b,c,d,e){var f=a.toString();a=this.a[f];a||(a=this.a[f]=[],this.b++);var h=Lc(a,b,d,e);-1<h?(b=a[h],c||(b.v=!1)):(b=new Ic(b,this.src,f,!!d,e),b.v=c,a.push(b));return b};
g.eb=function(a,b,c,d){a=a.toString();if(!(a in this.a))return!1;var e=this.a[a];b=Lc(e,b,c,d);return-1<b?(Jc(e[b]),Array.prototype.splice.call(e,b,1),0==e.length&&(delete this.a[a],this.b--),!0):!1};g.fb=function(a){a=a&&a.toString();var b=0,c;for(c in this.a)if(!a||c==a){for(var d=this.a[c],e=0;e<d.length;e++)++b,Jc(d[e]);delete this.a[c];this.b--}return b};g.Ca=function(a,b){a=this.a[a.toString()];var c=[];if(a)for(var d=0;d<a.length;++d){var e=a[d];e.capture==b&&c.push(e)}return c};
g.cb=function(a,b){var c=void 0!==a,d=c?a.toString():"",e=void 0!==b;return ua(this.a,function(f){for(var h=0;h<f.length;++h)if(!(c&&f[h].type!=d||e&&f[h].capture!=b))return!0;return!1})};function Lc(a,b,c,d){for(var e=0;e<a.length;++e){var f=a[e];if(!f.l&&f.listener==b&&f.capture==!!c&&f.b==d)return e}return-1};var Mc="closure_lm_"+(1E6*Math.random()|0),Nc={},Oc=0;function Pc(a,b,c,d,e){if(d&&d.once)return T(a,b,c,d,e);if(p(b)){for(var f=0;f<b.length;f++)Pc(a,b[f],c,d,e);return null}c=Qc(c);return a&&a[Gc]?U(a,b,c,r(d)?!!d.capture:!!d,e):Rc(a,b,c,!1,d,e)}
function Rc(a,b,c,d,e,f){if(!b)throw Error("Invalid event type");var h=r(e)?!!e.capture:!!e,k=Sc(a);k||(a[Mc]=k=new Kc(a));c=k.add(b,c,d,h,f);if(c.a)return c;d=Tc();c.a=d;d.src=a;d.listener=c;if(a.addEventListener)zc||(e=h),void 0===e&&(e=!1),a.addEventListener(b.toString(),d,e);else if(a.attachEvent)a.attachEvent(Uc(b.toString()),d);else if(a.addListener&&a.removeListener)a.addListener(d);else throw Error("addEventListener and attachEvent are unavailable.");Oc++;return c}
function Tc(){var a=Vc,b=xc?function(c){return a.call(b.src,b.listener,c)}:function(c){c=a.call(b.src,b.listener,c);if(!c)return c};return b}function T(a,b,c,d,e){if(p(b)){for(var f=0;f<b.length;f++)T(a,b[f],c,d,e);return null}c=Qc(c);return a&&a[Gc]?a.J(b,c,r(d)?!!d.capture:!!d,e):Rc(a,b,c,!0,d,e)}
function Wc(a){if("number"!==typeof a&&a&&!a.l){var b=a.src;if(b&&b[Gc])b.a(a);else{var c=a.type,d=a.a;b.removeEventListener?b.removeEventListener(c,d,a.capture):b.detachEvent?b.detachEvent(Uc(c),d):b.addListener&&b.removeListener&&b.removeListener(d);Oc--;if(c=Sc(b)){d=a.type;if(d in c.a){var e=c.a[d],f=qa(e,a),h;(h=0<=f)&&Array.prototype.splice.call(e,f,1);h&&(Jc(a),0==c.a[d].length&&(delete c.a[d],c.b--))}0==c.b&&(c.src=null,b[Mc]=null)}else Jc(a)}}}
function Uc(a){return a in Nc?Nc[a]:Nc[a]="on"+a}function Xc(a,b,c,d){var e=!0;if(a=Sc(a))if(b=a.a[b.toString()])for(b=b.concat(),a=0;a<b.length;a++){var f=b[a];f&&f.capture==c&&!f.l&&(f=Yc(f,d),e=e&&!1!==f)}return e}function Yc(a,b){var c=a.listener,d=a.b||a.src;a.v&&Wc(a);return c.call(d,b)}
function Vc(a,b){if(a.l)return!0;if(!xc){if(!b)a:{b=["window","event"];for(var c=m,d=0;d<b.length;d++)if(c=c[b[d]],null==c){b=null;break a}b=c}d=b;b=new S(d,this);c=!0;if(!(0>d.keyCode||void 0!=d.returnValue)){a:{var e=!1;if(0==d.keyCode)try{d.keyCode=-1;break a}catch(h){e=!0}if(e||void 0==d.returnValue)d.returnValue=!0}d=[];for(e=b.b;e;e=e.parentNode)d.push(e);a=a.type;for(e=d.length-1;!b.h&&0<=e;e--){b.b=d[e];var f=Xc(d[e],a,!0,b);c=c&&f}for(e=0;!b.h&&e<d.length;e++)b.b=d[e],f=Xc(d[e],a,!1,b),c=
c&&f}return c}return Yc(a,new S(b,this))}function Sc(a){a=a[Mc];return a instanceof Kc?a:null}var Zc="__closure_events_fn_"+(1E9*Math.random()>>>0);function Qc(a){if("function"==n(a))return a;a[Zc]||(a[Zc]=function(b){return a.handleEvent(b)});return a[Zc]};function V(a){Ac.call(this);this.c=a;this.a={}}t(V,Ac);var $c=[];function ad(a,b,c){U(a,b,"click",c,void 0)}g=V.prototype;g.xb=function(a,b,c,d,e){return U(this,a,b,c,d,e)};function U(a,b,c,d,e,f){p(c)||(c&&($c[0]=c.toString()),c=$c);for(var h=0;h<c.length;h++){var k=Pc(b,c[h],d||a.handleEvent,e||!1,f||a.c||a);if(!k)break;a.a[k.key]=k}return a}g.ab=function(a,b,c,d){return bd(this,a,b,c,d)};g.wb=function(a,b,c,d,e){return bd(this,a,b,c,d,e)};
function bd(a,b,c,d,e,f){if(p(c))for(var h=0;h<c.length;h++)bd(a,b,c[h],d,e,f);else{b=T(b,c,d||a.handleEvent,e,f||a.c||a);if(!b)return a;a.a[b.key]=b}return a}g.yb=function(a,b,c,d){U(b,a,c,d,this.c||this);return this};g.zb=function(a,b,c,d,e){U(b,a,c,d,e||this.c||this);return this};g.$a=function(){var a=0,b;for(b in this.a)Object.prototype.hasOwnProperty.call(this.a,b)&&a++;return a};
function cd(a,b,c,d,e,f){if(p(c))for(var h=0;h<c.length;h++)cd(a,b,c[h],d,e,f);else d=d||a.handleEvent,e=r(e)?!!e.capture:!!e,f=f||a.c||a,d=Qc(d),e=!!e,b&&b[Gc]?c=b.I(c,d,e,f):b?(b=Sc(b))?(c=b.a[c.toString()],b=-1,c&&(b=Lc(c,d,e,f)),c=-1<b?c[b]:null):c=null:c=null,c&&(Wc(c),delete a.a[c.key])}g.Nb=function(a,b,c,d,e){cd(b,a,c,d,e||this.c||this,this);return this};function dd(a){ta(a.a,function(b,c){this.a.hasOwnProperty(c)&&Wc(b)},a);a.a={}}g.A=function(){V.u.A.call(this);dd(this)};
g.handleEvent=function(){throw Error("EventHandler.handleEvent not implemented");};function W(a,b){b=a(b||ed,void 0,void 0);a=Rb();a=R(a.a,"DIV");if(r(b))if(b instanceof G){if(b.f!==F)throw Error("Sanitized content was not of kind HTML.");b=B(b.toString(),b.w||null)}else b=A("zSoyz");else b=A(String(b));Wa(a,b);1==a.childNodes.length&&(b=a.firstChild,1==b.nodeType&&(a=b));return a}var ed={};function fd(){};function gd(){}t(gd,fd);gd.prototype.O=function(){var a=0;Ya(this.j(!0),function(){a++});return a};gd.prototype.S=function(){var a=Za(this.j(!0)),b=this;u(a,function(c){b.a.removeItem(c)})};function hd(a){this.a=a}t(hd,gd);g=hd.prototype;g.nb=function(){if(!this.a)return!1;try{return this.a.setItem("__sak","1"),this.a.removeItem("__sak"),!0}catch(a){return!1}};g.set=function(a,b){try{this.a.setItem(a,b)}catch(c){if(0==this.a.length)throw"Storage mechanism: Storage disabled";throw"Storage mechanism: Quota exceeded";}};g.get=function(a){a=this.a.getItem(a);if("string"!==typeof a&&null!==a)throw"Storage mechanism: Invalid value was encountered";return a};g.O=function(){return this.a.length};
g.j=function(a){var b=0,c=this.a,d=new E;d.a=function(){if(b>=c.length)throw D;var e=c.key(b++);if(a)return e;e=c.getItem(e);if("string"!==typeof e)throw"Storage mechanism: Invalid value was encountered";return e};return d};g.S=function(){this.a.clear()};g.key=function(a){return this.a.key(a)};function id(){var a=null;try{a=window.localStorage||null}catch(b){}this.a=a}t(id,hd);var jd={},kd=(jd[0]=Gb,jd[1]=Gb,jd[2]=function(a){a=a||{};a=a.D;a='<div class="devsite-snackbar-snack" type="cookie-notification"><div class="devsite-snackbar-inner"><div class="devsite-snackbar-message">Google uses cookies to deliver its services, to personalize ads, and to analyze traffic. You can adjust your privacy controls anytime in your <a href="//myaccount.google.com/intro/data-and-personalization">Google settings</a>.</div><a href="'+((a?rb(wb(a)):"//policies.google.com/technologies/cookies")+
'" class="devsite-snackbar-link button">');return L(a+'More details</a><button class="devsite-snackbar-action">OK</button></div></div>')},jd);function X(){var a=N.call(this)||this;a.h=-1;a.o=new V(a);a.b=new id;a.a=[];return a}ha(X,N);X.prototype.connectedCallback=function(){U(this.o,document.body,"devsite-show-custom-snackbar-msg",this.B,void 0)};X.prototype.disconnectedCallback=function(){dd(this.o)};
X.prototype.B=function(a){var b=this;this.setAttribute("type","custom");if(a=a.a.detail){var c=!!a.showClose,d=W(Jb,{message:a.msg,V:c});c&&T(d.querySelector(".devsite-snackbar-action"),"click",function(){Y(b,d)});Z(this,d,!c)}};
X.prototype.attributeChangedCallback=function(a,b,c){if("type"==a){switch(b){case "loading":Y(this,this.querySelector('*[type^="loading"]'));break;case "refresh":Y(this,this.querySelector('*[type^="refresh"]'));break;case "error":Y(this,this.querySelector('*[type^="error"]'));break;case "copied-to-clipboard":Y(this,this.querySelector('*[type^="copied-to-clipboard"]'));break;case "cookie-notification":ld(this);break;case "support-attachment-error":md(this);break;case "custom":Y(this,this.querySelector('*[type^="custom"]'))}null!=
b&&b.startsWith("notification-")&&nd(this);c&&(c.includes(",")&&(this.a=c.split(","),c=this.a.shift()),od(this,c))}};function od(a,b){switch(b){case "loading":if(!a.querySelector('*[type^="loading"]')){var c=W(Cb);Z(a,c)}break;case "refresh":pd(a);break;case "error":qd(a);break;case "copied-to-clipboard":c=W(Fb);Z(a,c,!0);break;case "cookie-notification":rd(a);break;case "support-attachment-error":sd(a)}b.startsWith("notification-")&&td(a,b)}
function Z(a,b,c){c=void 0===c?!1:c;a.appendChild(b);window.requestAnimationFrame(function(){ud(a,b,c)})}function ud(a,b,c){c=void 0===c?!1:c;window.clearTimeout(a.h);a.c?Y(a,a.c,b,c):(a.c=b,window.requestAnimationFrame(function(){b.setAttribute("show","")}),c&&(a.h=window.setTimeout(function(){a.removeAttribute("type");Y(a,b)},5E3)))}function pd(a){var b=W(Db);Pc(b.querySelector(".devsite-snackbar-action"),"click",function(){window.location.reload()});Z(a,b)}
function qd(a){var b=W(Eb);Pc(b.querySelector(".devsite-snackbar-action"),"click",function(){window.location.reload()});Z(a,b)}function Y(a,b,c,d){c=void 0===c?null:c;d=void 0===d?!1:d;b&&(T(b,Dc,function(){fc(b);a.c=null;if(c)ud(a,c,d);else{var e=a.a.length?a.a.shift():null;null!==e&&od(a,e)}}),b.removeAttribute("show"))}
function rd(a){if(a.b.get("devsite-eu-cookie")){var b=a.a.length?a.a.shift():null;null!==b&&od(a,b)}else{b=Gb;a.hasAttribute("data-cookie-notice")&&(b=parseInt(a.getAttribute("data-cookie-notice"),10),b=kd[b]);if(a.hasAttribute("data-cookie-policy")){var c=a.getAttribute("data-cookie-policy");b=W(b,{D:c})}else b=W(b);T(b.querySelector(".devsite-snackbar-action"),"click",function(){a.b.set("devsite-eu-cookie","1");ld(a)});Z(a,b)}}
function ld(a){Y(a,a.querySelector('*[type^="cookie-notification"]'))}function sd(a){var b=W(Hb);Z(a,b);T(b.querySelector(".devsite-snackbar-action"),"click",function(){md(a)})}function md(a){Y(a,a.querySelector('*[type^="support-attachment-error"]'))}
function td(a,b){var c=a.getAttribute(b+"-message"),d=a.getAttribute(b+"-link"),e=a.getAttribute(b+"-link-txt"),f=a.hasAttribute(b+"-store-key");if(c&&d){var h="devsite-notification"+d;if(!f||!a.b.get(h)){b=W(Ib,{W:b,message:c,link:d,U:e});Z(a,b);var k=new V(b);ad(k,b,function(M){M.stopPropagation();if(M.target.classList.contains("devsite-snackbar-link")||M.target.classList.contains("devsite-snackbar-action"))f&&a.b.set(h,"1"),nd(a),dd(k)})}}}
function nd(a){Y(a,a.querySelector('*[type^="notification"]'))}ja.Object.defineProperties(X,{observedAttributes:{configurable:!0,enumerable:!0,get:function(){return["type"]}}});X.prototype.attributeChangedCallback=X.prototype.attributeChangedCallback;X.prototype.disconnectedCallback=X.prototype.disconnectedCallback;X.prototype.connectedCallback=X.prototype.connectedCallback;try{window.customElements.define("devsite-snackbar",X)}catch(a){console.warn("devsite.app.customElement.DevsiteSnackBar",a)};}).call(this);
