(function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
'use strict';var g;function aa(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}}function ba(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return b?b.call(a):{next:aa(a)}}var ca="function"==typeof Object.create?Object.create:function(a){function b(){}b.prototype=a;return new b},da;
if("function"==typeof Object.setPrototypeOf)da=Object.setPrototypeOf;else{var ea;a:{var fa={J:!0},ha={};try{ha.__proto__=fa;ea=ha.J;break a}catch(a){}ea=!1}da=ea?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var ia=da;
function ja(a,b){a.prototype=ca(b.prototype);a.prototype.constructor=a;if(ia)ia(a,b);else for(var c in b)if("prototype"!=c)if(Object.defineProperties){var d=Object.getOwnPropertyDescriptor(b,c);d&&Object.defineProperty(a,c,d)}else a[c]=b[c];a.m=b.prototype}function ka(a){a=["object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global,a];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}return globalThis}
var p=ka(this),q="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)};function r(a,b){if(b){var c=p;a=a.split(".");for(var d=0;d<a.length-1;d++){var e=a[d];e in c||(c[e]={});c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&q(c,a,{configurable:!0,writable:!0,value:b})}}function la(){la=function(){};p.Symbol||(p.Symbol=ma)}function na(a,b){this.a=a;q(this,"description",{configurable:!0,writable:!0,value:b})}
na.prototype.toString=function(){return this.a};var ma=function(){function a(c){if(this instanceof a)throw new TypeError("Symbol is not a constructor");return new na("jscomp_symbol_"+(c||"")+"_"+b++,c)}var b=0;return a}();function oa(){la();var a=p.Symbol.iterator;a||(a=p.Symbol.iterator=p.Symbol("Symbol.iterator"));"function"!=typeof Array.prototype[a]&&q(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return pa(aa(this))}});oa=function(){}}
function pa(a){oa();a={next:a};a[p.Symbol.iterator]=function(){return this};return a}r("globalThis",function(a){return a||p});
var qa=function(){function a(){function c(){}new c;Reflect.construct(c,[],function(){});return new c instanceof c}if("undefined"!=typeof Reflect&&Reflect.construct){if(a())return Reflect.construct;var b=Reflect.construct;return function(c,d,e){c=b(c,d);e&&Reflect.setPrototypeOf(c,e.prototype);return c}}return function(c,d,e){void 0===e&&(e=c);e=ca(e.prototype||Object.prototype);return Function.prototype.apply.call(c,e,d)||e}}();r("Reflect.construct",function(){return qa});
r("Object.setPrototypeOf",function(a){return a||ia});function t(a,b){return Object.prototype.hasOwnProperty.call(a,b)}
r("WeakMap",function(a){function b(l){this.a=(k+=Math.random()+1).toString();if(l){l=ba(l);for(var m;!(m=l.next()).done;)m=m.value,this.set(m[0],m[1])}}function c(){}function d(l){var m=typeof l;return"object"===m&&null!==l||"function"===m}function e(l){if(!t(l,h)){var m=new c;q(l,h,{value:m})}}function f(l){var m=Object[l];m&&(Object[l]=function(n){if(n instanceof c)return n;e(n);return m(n)})}if(function(){if(!a||!Object.seal)return!1;try{var l=Object.seal({}),m=Object.seal({}),n=new a([[l,2],[m,
3]]);if(2!=n.get(l)||3!=n.get(m))return!1;n.delete(l);n.set(m,4);return!n.has(l)&&4==n.get(m)}catch(H){return!1}}())return a;var h="$jscomp_hidden_"+Math.random();f("freeze");f("preventExtensions");f("seal");var k=0;b.prototype.set=function(l,m){if(!d(l))throw Error("Invalid WeakMap key");e(l);if(!t(l,h))throw Error("WeakMap key fail: "+l);l[h][this.a]=m;return this};b.prototype.get=function(l){return d(l)&&t(l,h)?l[h][this.a]:void 0};b.prototype.has=function(l){return d(l)&&t(l,h)&&t(l[h],this.a)};
b.prototype.delete=function(l){return d(l)&&t(l,h)&&t(l[h],this.a)?delete l[h][this.a]:!1};return b});
r("Map",function(a){function b(){var k={};return k.g=k.next=k.head=k}function c(k,l){var m=k.a;return pa(function(){if(m){for(;m.head!=k.a;)m=m.g;for(;m.next!=m.head;)return m=m.next,{done:!1,value:l(m)};m=null}return{done:!0,value:void 0}})}function d(k,l){var m=l&&typeof l;"object"==m||"function"==m?f.has(l)?m=f.get(l):(m=""+ ++h,f.set(l,m)):m="p_"+l;var n=k.b[m];if(n&&t(k.b,m))for(k=0;k<n.length;k++){var H=n[k];if(l!==l&&H.key!==H.key||l===H.key)return{id:m,list:n,index:k,f:H}}return{id:m,list:n,
index:-1,f:void 0}}function e(k){this.b={};this.a=b();this.size=0;if(k){k=ba(k);for(var l;!(l=k.next()).done;)l=l.value,this.set(l[0],l[1])}}if(function(){if(!a||"function"!=typeof a||!a.prototype.entries||"function"!=typeof Object.seal)return!1;try{var k=Object.seal({x:4}),l=new a(ba([[k,"s"]]));if("s"!=l.get(k)||1!=l.size||l.get({x:4})||l.set({x:4},"t")!=l||2!=l.size)return!1;var m=l.entries(),n=m.next();if(n.done||n.value[0]!=k||"s"!=n.value[1])return!1;n=m.next();return n.done||4!=n.value[0].x||
"t"!=n.value[1]||!m.next().done?!1:!0}catch(H){return!1}}())return a;oa();var f=new WeakMap;e.prototype.set=function(k,l){k=0===k?0:k;var m=d(this,k);m.list||(m.list=this.b[m.id]=[]);m.f?m.f.value=l:(m.f={next:this.a,g:this.a.g,head:this.a,key:k,value:l},m.list.push(m.f),this.a.g.next=m.f,this.a.g=m.f,this.size++);return this};e.prototype.delete=function(k){k=d(this,k);return k.f&&k.list?(k.list.splice(k.index,1),k.list.length||delete this.b[k.id],k.f.g.next=k.f.next,k.f.next.g=k.f.g,k.f.head=null,
this.size--,!0):!1};e.prototype.clear=function(){this.b={};this.a=this.a.g=b();this.size=0};e.prototype.has=function(k){return!!d(this,k).f};e.prototype.get=function(k){return(k=d(this,k).f)&&k.value};e.prototype.entries=function(){return c(this,function(k){return[k.key,k.value]})};e.prototype.keys=function(){return c(this,function(k){return k.key})};e.prototype.values=function(){return c(this,function(k){return k.value})};e.prototype.forEach=function(k,l){for(var m=this.entries(),n;!(n=m.next()).done;)n=
n.value,k.call(l,n[1],n[0],this)};e.prototype[Symbol.iterator]=e.prototype.entries;var h=0;return e});r("Array.from",function(a){return a?a:function(b,c,d){c=null!=c?c:function(k){return k};var e=[],f="undefined"!=typeof Symbol&&Symbol.iterator&&b[Symbol.iterator];if("function"==typeof f){b=f.call(b);for(var h=0;!(f=b.next()).done;)e.push(c.call(d,f.value,h++))}else for(f=b.length,h=0;h<f;h++)e.push(c.call(d,b[h],h));return e}});var u=this||self;function ra(){}
function v(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b}function w(a){return"array"==v(a)}function sa(a){var b=v(a);return"array"==b||"object"==b&&"number"==typeof a.length}function x(a){var b=typeof a;return"object"==b&&null!=a||"function"==b}function ta(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var d=c.slice();d.push.apply(d,arguments);return a.apply(this,d)}}
function ua(a,b){function c(){}c.prototype=b.prototype;a.m=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.U=function(d,e,f){for(var h=Array(arguments.length-2),k=2;k<arguments.length;k++)h[k-2]=arguments[k];return b.prototype[e].apply(d,h)}};var va;var wa=Array.prototype.indexOf?function(a,b){return Array.prototype.indexOf.call(a,b,void 0)}:function(a,b){if("string"===typeof a)return"string"!==typeof b||1!=b.length?-1:a.indexOf(b,0);for(var c=0;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},xa=Array.prototype.forEach?function(a,b){Array.prototype.forEach.call(a,b,void 0)}:function(a,b){for(var c=a.length,d="string"===typeof a?a.split(""):a,e=0;e<c;e++)e in d&&b.call(void 0,d[e],e,a)},ya=Array.prototype.filter?function(a,b){return Array.prototype.filter.call(a,
b,void 0)}:function(a,b){for(var c=a.length,d=[],e=0,f="string"===typeof a?a.split(""):a,h=0;h<c;h++)if(h in f){var k=f[h];b.call(void 0,k,h,a)&&(d[e++]=k)}return d};function za(a){var b=a.length;if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]};var Aa=String.prototype.trim?function(a){return a.trim()}:function(a){return/^[\s\xa0]*([\s\S]*?)[\s\xa0]*$/.exec(a)[1]};
function Ba(a,b){if(b)a=a.replace(Ca,"&amp;").replace(Da,"&lt;").replace(Ea,"&gt;").replace(Fa,"&quot;").replace(Ga,"&#39;").replace(Ha,"&#0;");else{if(!Ia.test(a))return a;-1!=a.indexOf("&")&&(a=a.replace(Ca,"&amp;"));-1!=a.indexOf("<")&&(a=a.replace(Da,"&lt;"));-1!=a.indexOf(">")&&(a=a.replace(Ea,"&gt;"));-1!=a.indexOf('"')&&(a=a.replace(Fa,"&quot;"));-1!=a.indexOf("'")&&(a=a.replace(Ga,"&#39;"));-1!=a.indexOf("\x00")&&(a=a.replace(Ha,"&#0;"))}return a}
var Ca=/&/g,Da=/</g,Ea=/>/g,Fa=/"/g,Ga=/'/g,Ha=/\x00/g,Ia=/[\x00&<>"']/;function Ja(a,b){return a<b?-1:a>b?1:0};var y;a:{var Ka=u.navigator;if(Ka){var La=Ka.userAgent;if(La){y=La;break a}}y=""};function Ma(a,b,c){for(var d in a)b.call(c,a[d],d,a)}function Na(a,b){for(var c in a)if(b.call(void 0,a[c],c,a))return!0;return!1}var Oa="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" ");function Pa(a,b){for(var c,d,e=1;e<arguments.length;e++){d=arguments[e];for(c in d)a[c]=d[c];for(var f=0;f<Oa.length;f++)c=Oa[f],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}};function z(a){this.b=Qa===Qa&&a||"";this.c=Ra}z.prototype.w=!0;z.prototype.u=function(){return this.b.toString()};z.prototype.G=!0;z.prototype.a=function(){return 1};var Ra={},Qa={};function A(){this.b="";this.j=Sa;this.c=null}A.prototype.G=!0;A.prototype.a=function(){return this.c};A.prototype.w=!0;A.prototype.u=function(){return this.b.toString()};function B(a){return a instanceof A&&a.constructor===A&&a.j===Sa?a.b:"type_error:SafeHtml"}function C(a){if(a instanceof A)return a;var b="object"==typeof a,c=null;b&&a.G&&(c=a.a());a=Ba(b&&a.w?a.u():String(a));return D(a,c)}
function Ta(a){function b(f){w(f)?xa(f,b):(f=C(f),e.push(B(f).toString()),f=f.a(),0==d?d=f:0!=f&&d!=f&&(d=null))}var c=C(Ua),d=c.a(),e=[];xa(a,b);return D(e.join(B(c).toString()),d)}function Va(a){return Ta(Array.prototype.slice.call(arguments))}var Sa={};function D(a,b){var c=new A;c.b=a;c.c=b;return c}D("<!DOCTYPE html>",0);var Ua=D("",0),Wa=D("<br>",0);var Xa=function(a){var b=!1,c;return function(){b||(c=a(),b=!0);return c}}(function(){var a=document.createElement("div"),b=document.createElement("div");b.appendChild(document.createElement("div"));a.appendChild(b);b=a.firstChild.firstChild;a.innerHTML=B(Ua);return!b.parentElement});function Ya(a,b){if(Xa())for(;a.lastChild;)a.removeChild(a.lastChild);a.innerHTML=B(b)};function Za(a){return a=Ba(a,void 0)};function $a(a){$a[" "](a);return a}$a[" "]=ra;function ab(a,b){var c=bb;return Object.prototype.hasOwnProperty.call(c,a)?c[a]:c[a]=b(a)};var cb=-1!=y.indexOf("Opera"),E=-1!=y.indexOf("Trident")||-1!=y.indexOf("MSIE"),db=-1!=y.indexOf("Edge"),F=-1!=y.indexOf("Gecko")&&!(-1!=y.toLowerCase().indexOf("webkit")&&-1==y.indexOf("Edge"))&&!(-1!=y.indexOf("Trident")||-1!=y.indexOf("MSIE"))&&-1==y.indexOf("Edge"),G=-1!=y.toLowerCase().indexOf("webkit")&&-1==y.indexOf("Edge"),eb=-1!=y.indexOf("Macintosh");function fb(){var a=u.document;return a?a.documentMode:void 0}var gb;
a:{var hb="",ib=function(){var a=y;if(F)return/rv:([^\);]+)(\)|;)/.exec(a);if(db)return/Edge\/([\d\.]+)/.exec(a);if(E)return/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/.exec(a);if(G)return/WebKit\/(\S+)/.exec(a);if(cb)return/(?:Version)[ \/]?(\S+)/.exec(a)}();ib&&(hb=ib?ib[1]:"");if(E){var jb=fb();if(null!=jb&&jb>parseFloat(hb)){gb=String(jb);break a}}gb=hb}var kb=gb,bb={};
function I(a){return ab(a,function(){for(var b=0,c=Aa(String(kb)).split("."),d=Aa(String(a)).split("."),e=Math.max(c.length,d.length),f=0;0==b&&f<e;f++){var h=c[f]||"",k=d[f]||"";do{h=/(\d*)(\D*)(.*)/.exec(h)||["","","",""];k=/(\d*)(\D*)(.*)/.exec(k)||["","","",""];if(0==h[0].length&&0==k[0].length)break;b=Ja(0==h[1].length?0:parseInt(h[1],10),0==k[1].length?0:parseInt(k[1],10))||Ja(0==h[2].length,0==k[2].length)||Ja(h[2],k[2]);h=h[3];k=k[3]}while(0==b)}return 0<=b})}var J;J=u.document&&E?fb():void 0;var lb=!E||9<=Number(J),mb=!E||9<=Number(J),nb=E&&!I("9"),ob=function(){if(!u.addEventListener||!Object.defineProperty)return!1;var a=!1,b=Object.defineProperty({},"passive",{get:function(){a=!0}});try{u.addEventListener("test",ra,b),u.removeEventListener("test",ra,b)}catch(c){}return a}();function K(){this.h=this.h;this.b=this.b}g=K.prototype;g.h=!1;g.N=function(){return this.h};g.ia=K.prototype.N;g.C=function(){this.h||(this.h=!0,this.s())};g.tb=function(a){a=ta(pb,a);this.h?a():(this.b||(this.b=[]),this.b.push(a))};g.s=function(){if(this.b)for(;this.b.length;)this.b.shift()()};function pb(a){a&&"function"==typeof a.C&&a.C()};function L(a,b){this.type=a;this.b=this.target=b;this.O=this.c=!1}L.prototype.v=function(){this.c=!0};L.prototype.l=function(){this.O=!0};function M(a,b){L.call(this,a?a.type:"");this.relatedTarget=this.b=this.target=null;this.button=this.screenY=this.screenX=this.clientY=this.clientX=this.H=this.F=0;this.key="";this.j=this.D=0;this.metaKey=this.shiftKey=this.altKey=this.ctrlKey=!1;this.I=null;this.P=!1;this.pointerId=0;this.pointerType="";this.a=null;if(a){var c=this.type=a.type,d=a.changedTouches&&a.changedTouches.length?a.changedTouches[0]:null;this.target=a.target||a.srcElement;this.b=b;if(b=a.relatedTarget){if(F){a:{try{$a(b.nodeName);
var e=!0;break a}catch(f){}e=!1}e||(b=null)}}else"mouseover"==c?b=a.fromElement:"mouseout"==c&&(b=a.toElement);this.relatedTarget=b;d?(this.clientX=void 0!==d.clientX?d.clientX:d.pageX,this.clientY=void 0!==d.clientY?d.clientY:d.pageY,this.screenX=d.screenX||0,this.screenY=d.screenY||0):(this.F=G||void 0!==a.offsetX?a.offsetX:a.layerX,this.H=G||void 0!==a.offsetY?a.offsetY:a.layerY,this.clientX=void 0!==a.clientX?a.clientX:a.pageX,this.clientY=void 0!==a.clientY?a.clientY:a.pageY,this.screenX=a.screenX||
0,this.screenY=a.screenY||0);this.button=a.button;this.D=a.keyCode||0;this.key=a.key||"";this.j=a.charCode||("keypress"==c?a.keyCode:0);this.ctrlKey=a.ctrlKey;this.altKey=a.altKey;this.shiftKey=a.shiftKey;this.metaKey=a.metaKey;this.P=eb?a.metaKey:a.ctrlKey;this.pointerId=a.pointerId||0;this.pointerType="string"===typeof a.pointerType?a.pointerType:qb[a.pointerType]||"";this.I=a.state;this.a=a;a.defaultPrevented&&this.l()}}ua(M,L);var rb=[1,4,2],qb={2:"touch",3:"pen",4:"mouse"};
M.prototype.Fb=function(){return(lb?0==this.a.button:"click"==this.type?!0:!!(this.a.button&rb[0]))&&!(G&&eb&&this.ctrlKey)};M.prototype.v=function(){M.m.v.call(this);this.a.stopPropagation?this.a.stopPropagation():this.a.cancelBubble=!0};M.prototype.l=function(){M.m.l.call(this);var a=this.a;if(a.preventDefault)a.preventDefault();else if(a.returnValue=!1,nb)try{if(a.ctrlKey||112<=a.keyCode&&123>=a.keyCode)a.keyCode=-1}catch(b){}};M.prototype.xb=function(){return this.a};var N="closure_listenable_"+(1E6*Math.random()|0),sb=0;function tb(a,b,c,d,e){this.listener=a;this.a=null;this.src=b;this.type=c;this.capture=!!d;this.b=e;this.key=++sb;this.i=this.o=!1}function O(a){a.i=!0;a.listener=null;a.a=null;a.src=null;a.b=null};function ub(a){this.src=a;this.a={};this.b=0}g=ub.prototype;g.Va=function(){var a=0,b;for(b in this.a)a+=this.a[b].length;return a};g.add=function(a,b,c,d,e){var f=a.toString();a=this.a[f];a||(a=this.a[f]=[],this.b++);var h=vb(a,b,d,e);-1<h?(b=a[h],c||(b.o=!1)):(b=new tb(b,this.src,f,!!d,e),b.o=c,a.push(b));return b};
g.Xa=function(a,b,c,d){a=a.toString();if(!(a in this.a))return!1;var e=this.a[a];b=vb(e,b,c,d);return-1<b?(O(e[b]),Array.prototype.splice.call(e,b,1),0==e.length&&(delete this.a[a],this.b--),!0):!1};g.Ya=function(a){a=a&&a.toString();var b=0,c;for(c in this.a)if(!a||c==a){for(var d=this.a[c],e=0;e<d.length;e++)++b,O(d[e]);delete this.a[c];this.b--}return b};g.va=function(a,b){a=this.a[a.toString()];var c=[];if(a)for(var d=0;d<a.length;++d){var e=a[d];e.capture==b&&c.push(e)}return c};
g.Wa=function(a,b){var c=void 0!==a,d=c?a.toString():"",e=void 0!==b;return Na(this.a,function(f){for(var h=0;h<f.length;++h)if(!(c&&f[h].type!=d||e&&f[h].capture!=b))return!0;return!1})};function vb(a,b,c,d){for(var e=0;e<a.length;++e){var f=a[e];if(!f.i&&f.listener==b&&f.capture==!!c&&f.b==d)return e}return-1};var wb="closure_lm_"+(1E6*Math.random()|0),xb={},yb=0;function zb(a,b,c,d,e){if(d&&d.once)return Ab(a,b,c,d,e);if(w(b)){for(var f=0;f<b.length;f++)zb(a,b[f],c,d,e);return null}c=Bb(c);return a&&a[N]?P(a,b,c,x(d)?!!d.capture:!!d,e):Cb(a,b,c,!1,d,e)}
function Cb(a,b,c,d,e,f){if(!b)throw Error("Invalid event type");var h=x(e)?!!e.capture:!!e,k=Q(a);k||(a[wb]=k=new ub(a));c=k.add(b,c,d,h,f);if(c.a)return c;d=Db();c.a=d;d.src=a;d.listener=c;if(a.addEventListener)ob||(e=h),void 0===e&&(e=!1),a.addEventListener(b.toString(),d,e);else if(a.attachEvent)a.attachEvent(Eb(b.toString()),d);else if(a.addListener&&a.removeListener)a.addListener(d);else throw Error("addEventListener and attachEvent are unavailable.");yb++;return c}
function Db(){var a=Fb,b=mb?function(c){return a.call(b.src,b.listener,c)}:function(c){c=a.call(b.src,b.listener,c);if(!c)return c};return b}function Ab(a,b,c,d,e){if(w(b)){for(var f=0;f<b.length;f++)Ab(a,b[f],c,d,e);return null}c=Bb(c);return a&&a[N]?a.F(b,c,x(d)?!!d.capture:!!d,e):Cb(a,b,c,!0,d,e)}
function Gb(a){if("number"!==typeof a&&a&&!a.i){var b=a.src;if(b&&b[N])b.a(a);else{var c=a.type,d=a.a;b.removeEventListener?b.removeEventListener(c,d,a.capture):b.detachEvent?b.detachEvent(Eb(c),d):b.addListener&&b.removeListener&&b.removeListener(d);yb--;if(c=Q(b)){d=a.type;if(d in c.a){var e=c.a[d],f=wa(e,a),h;(h=0<=f)&&Array.prototype.splice.call(e,f,1);h&&(O(a),0==c.a[d].length&&(delete c.a[d],c.b--))}0==c.b&&(c.src=null,b[wb]=null)}else O(a)}}}
function Eb(a){return a in xb?xb[a]:xb[a]="on"+a}function Hb(a,b,c,d){var e=!0;if(a=Q(a))if(b=a.a[b.toString()])for(b=b.concat(),a=0;a<b.length;a++){var f=b[a];f&&f.capture==c&&!f.i&&(f=Ib(f,d),e=e&&!1!==f)}return e}function Ib(a,b){var c=a.listener,d=a.b||a.src;a.o&&Gb(a);return c.call(d,b)}
function Fb(a,b){if(a.i)return!0;if(!mb){if(!b)a:{b=["window","event"];for(var c=u,d=0;d<b.length;d++)if(c=c[b[d]],null==c){b=null;break a}b=c}d=b;b=new M(d,this);c=!0;if(!(0>d.keyCode||void 0!=d.returnValue)){a:{var e=!1;if(0==d.keyCode)try{d.keyCode=-1;break a}catch(h){e=!0}if(e||void 0==d.returnValue)d.returnValue=!0}d=[];for(e=b.b;e;e=e.parentNode)d.push(e);a=a.type;for(e=d.length-1;!b.c&&0<=e;e--){b.b=d[e];var f=Hb(d[e],a,!0,b);c=c&&f}for(e=0;!b.c&&e<d.length;e++)b.b=d[e],f=Hb(d[e],a,!1,b),c=
c&&f}return c}return Ib(a,new M(b,this))}function Q(a){a=a[wb];return a instanceof ub?a:null}var Jb="__closure_events_fn_"+(1E9*Math.random()>>>0);function Bb(a){if("function"==v(a))return a;a[Jb]||(a[Jb]=function(b){return a.handleEvent(b)});return a[Jb]};var Kb={},Lb={};function R(){throw Error("Do not instantiate directly");}R.prototype.A=null;R.prototype.b=function(){return this.a};R.prototype.toString=function(){return this.a};R.prototype.c=function(){if(this.B!==Lb)throw Error("Sanitized content was not of kind URI.");return new z(this.toString())};function Mb(){R.call(this)}ua(Mb,R);Mb.prototype.B=Kb;var Nb=function(a){function b(c){this.a=c}b.prototype=a.prototype;return function(c,d){c=new b(String(c));void 0!==d&&(c.A=d);return c}}(Mb),Ob={"\x00":"&#0;","\t":"&#9;","\n":"&#10;","\x0B":"&#11;","\f":"&#12;","\r":"&#13;"," ":"&#32;",'"':"&quot;","&":"&amp;","'":"&#39;","-":"&#45;","/":"&#47;","<":"&lt;","=":"&#61;",">":"&gt;","`":"&#96;","\u0085":"&#133;","\u00a0":"&#160;","\u2028":"&#8232;","\u2029":"&#8233;"};function Pb(a){return Ob[a]}var Qb=/[\x00\x22\x27\x3c\x3e]/g;var Rb=!E||9<=Number(J),Sb=!F&&!E||E&&9<=Number(J)||F&&I("1.9.1"),Tb=E&&!I("9"),Ub=E||cb||G;function S(a,b){this.x=void 0!==a?a:0;this.a=void 0!==b?b:0}g=S.prototype;g.Za=function(){return new S(this.x,this.a)};g.X=function(a){return a instanceof S&&(this==a?!0:this&&a?this.x==a.x&&this.a==a.a:!1)};g.ceil=function(){this.x=Math.ceil(this.x);this.a=Math.ceil(this.a);return this};g.floor=function(){this.x=Math.floor(this.x);this.a=Math.floor(this.a);return this};g.round=function(){this.x=Math.round(this.x);this.a=Math.round(this.a);return this};
g.ab=function(a,b){a instanceof S?(this.x+=a.x,this.a+=a.a):(this.x+=Number(a),"number"===typeof b&&(this.a+=b));return this};g.$a=function(a,b){this.x*=a;this.a*="number"===typeof b?b:a;return this};g.wb=function(a,b){a=a*Math.PI/180;b=b||new S(0,0);var c=this.x,d=this.a,e=Math.cos(a);a=Math.sin(a);this.x=(c-b.x)*e-(d-b.a)*a+b.x;this.a=(c-b.x)*a+(d-b.a)*e+b.a};function Vb(a,b){this.width=a;this.height=b}g=Vb.prototype;g.bb=function(){return new Vb(this.width,this.height)};g.wa=function(){return Math.max(this.width,this.height)};g.Ja=function(){return Math.min(this.width,this.height)};g.sb=function(){return 2*(this.width+this.height)};g.aspectRatio=function(){return this.width/this.height};g.ib=function(){return!(this.width*this.height)};g.ceil=function(){this.width=Math.ceil(this.width);this.height=Math.ceil(this.height);return this};
g.aa=function(a){return this.width<=a.width&&this.height<=a.height};g.floor=function(){this.width=Math.floor(this.width);this.height=Math.floor(this.height);return this};g.round=function(){this.width=Math.round(this.width);this.height=Math.round(this.height);return this};function Wb(a,b){a.width*=b;a.height*=b;return a}g.zb=function(a){a=this.aspectRatio()<=a.aspectRatio()?a.width/this.width:a.height/this.height;return Wb(this,a)};
g.Ab=function(a){a=this.aspectRatio()>a.aspectRatio()?a.width/this.width:a.height/this.height;return Wb(this,a)};function Xb(a){return a?new T(U(a)):va||(va=new T)}function Yb(a,b){var c=b||document,d=null;c.getElementsByClassName?d=c.getElementsByClassName(a)[0]:d=Zb(document,"*",a,b);return d||null}
function $b(a,b,c,d){a=d||a;var e=b&&"*"!=b?String(b).toUpperCase():"";if(a.querySelectorAll&&a.querySelector&&(e||c))return a.querySelectorAll(e+(c?"."+c:""));if(c&&a.getElementsByClassName){b=a.getElementsByClassName(c);if(e){a={};for(var f=d=0,h;h=b[f];f++)e==h.nodeName&&(a[d++]=h);a.length=d;return a}return b}b=a.getElementsByTagName(e||"*");if(c){a={};for(f=d=0;h=b[f];f++){e=h.className;var k;if(k="function"==typeof e.split)k=0<=wa(e.split(/\s+/),c);k&&(a[d++]=h)}a.length=d;return a}return b}
function Zb(a,b,c,d){var e=d||a,f=b&&"*"!=b?String(b).toUpperCase():"";return e.querySelectorAll&&e.querySelector&&(f||c)?e.querySelector(f+(c?"."+c:"")):$b(a,b,c,d)[0]||null}function ac(a,b){Ma(b,function(c,d){c&&"object"==typeof c&&c.w&&(c=c.u());"style"==d?a.style.cssText=c:"class"==d?a.className=c:"for"==d?a.htmlFor=c:bc.hasOwnProperty(d)?a.setAttribute(bc[d],c):0==d.lastIndexOf("aria-",0)||0==d.lastIndexOf("data-",0)?a.setAttribute(d,c):a[d]=c})}
var bc={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",frameborder:"frameBorder",height:"height",maxlength:"maxLength",nonce:"nonce",role:"role",rowspan:"rowSpan",type:"type",usemap:"useMap",valign:"vAlign",width:"width"};function cc(a){a=a.document;a=dc(a)?a.documentElement:a.body;return new Vb(a.clientWidth,a.clientHeight)}function ec(a){return a.scrollingElement?a.scrollingElement:!G&&dc(a)?a.documentElement:a.body||a.documentElement}
function fc(a){return a.parentWindow||a.defaultView}function gc(a,b,c,d){function e(h){h&&b.appendChild("string"===typeof h?a.createTextNode(h):h)}for(;d<c.length;d++){var f=c[d];sa(f)&&!hc(f)?xa(ic(f)?za(f):f,e):e(f)}}function V(a,b){b=String(b);"application/xhtml+xml"===a.contentType&&(b=b.toLowerCase());return a.createElement(b)}function dc(a){return"CSS1Compat"==a.compatMode}function jc(a){for(var b;b=a.firstChild;)a.removeChild(b)}
function W(a){return a&&a.parentNode?a.parentNode.removeChild(a):null}function kc(a,b){for(;a&&1!=a.nodeType;)a=b?a.nextSibling:a.previousSibling;return a}function hc(a){return x(a)&&0<a.nodeType}function lc(a){return x(a)&&1==a.nodeType}function mc(a,b){if(!a||!b)return!1;if(a.contains&&1==b.nodeType)return a==b||a.contains(b);if("undefined"!=typeof a.compareDocumentPosition)return a==b||!!(a.compareDocumentPosition(b)&16);for(;b&&a!=b;)b=b.parentNode;return b==a}
function nc(a,b){var c=a.parentNode;if(c==b)return-1;for(;b.parentNode!=c;)b=b.parentNode;return oc(b,a)}function oc(a,b){for(;b=b.previousSibling;)if(b==a)return-1;return 1}function U(a){return 9==a.nodeType?a:a.ownerDocument||a.document}
function pc(a,b){if("textContent"in a)a.textContent=b;else if(3==a.nodeType)a.data=String(b);else if(a.firstChild&&3==a.firstChild.nodeType){for(;a.lastChild!=a.firstChild;)a.removeChild(a.lastChild);a.firstChild.data=String(b)}else jc(a),a.appendChild(U(a).createTextNode(String(b)))}function qc(a,b,c,d){if(null!=a)for(a=a.firstChild;a;){if(b(a)&&(c.push(a),d)||qc(a,b,c,d))return!0;a=a.nextSibling}return!1}var rc={SCRIPT:1,STYLE:1,HEAD:1,IFRAME:1,OBJECT:1},sc={IMG:" ",BR:"\n"};
function tc(a){return uc(a)&&vc(a)}function uc(a){return E&&!I("9")?(a=a.getAttributeNode("tabindex"),null!=a&&a.specified):a.hasAttribute("tabindex")}function vc(a){a=a.tabIndex;return"number"===typeof a&&0<=a&&32768>a}function wc(a){if(Tb&&null!==a&&"innerText"in a)a=a.innerText.replace(/(\r\n|\r|\n)/g,"\n");else{var b=[];xc(a,b,!0);a=b.join("")}a=a.replace(/ \xAD /g," ").replace(/\xAD/g,"");a=a.replace(/\u200B/g,"");Tb||(a=a.replace(/ +/g," "));" "!=a&&(a=a.replace(/^\s*/,""));return a}
function xc(a,b,c){if(!(a.nodeName in rc))if(3==a.nodeType)c?b.push(String(a.nodeValue).replace(/(\r\n|\r|\n)/g,"")):b.push(a.nodeValue);else if(a.nodeName in sc)b.push(sc[a.nodeName]);else for(a=a.firstChild;a;)xc(a,b,c),a=a.nextSibling}function ic(a){if(a&&"number"==typeof a.length){if(x(a))return"function"==typeof a.item||"string"==typeof a.item;if("function"==v(a))return"function"==typeof a.item}return!1}
function yc(a,b,c,d){if(!b&&!c)return null;var e=b?String(b).toUpperCase():null;return zc(a,function(f){var h;(h=!e||f.nodeName==e)&&!(h=!c)&&(h="string"===typeof f.className)&&(h=0<=wa(f.className.split(/\s+/),c));return h},!0,d)}function zc(a,b,c,d){a&&!c&&(a=a.parentNode);for(c=0;a&&(null==d||c<=d);){if(b(a))return a;a=a.parentNode;c++}return null}function T(a){this.a=a||u.document||document}g=T.prototype;g.na=Xb;g.Bb=function(a){this.a=a};g.ja=function(){return this.a};
g.L=function(a){return"string"===typeof a?this.a.getElementById(a):a};g.Ha=function(a){return"string"===typeof a?this.a.getElementById(a):a};g.R=T.prototype.L;g.Qa=function(a,b){return(b||this.a).getElementsByTagName(String(a))};g.M=function(a,b,c){return $b(this.a,a,b,c)};g.pa=function(a,b,c){return Zb(this.a,a,b,c)};g.qa=function(a,b){var c=(b=b||this.a)||document;return c.querySelectorAll&&c.querySelector?c.querySelectorAll("."+a):$b(document,"*",a,b)};g.oa=function(a,b){return Yb(a,b||this.a)};
g.Ia=function(a,b){return Yb(a,b||this.a)};g.S=T.prototype.M;g.Db=ac;g.La=function(a){return cc(a||fc(this.a)||window)};g.ka=function(){var a=fc(this.a),b=a.document;var c=0;if(b){c=b.body;var d=b.documentElement;if(d&&c)if(a=cc(a).height,dc(b)&&d.scrollHeight)c=d.scrollHeight!=a?d.scrollHeight:d.offsetHeight;else{b=d.scrollHeight;var e=d.offsetHeight;d.clientHeight!=e&&(b=c.scrollHeight,e=c.offsetHeight);c=b>a?b>e?b:e:b<e?b:e}else c=0}return c};
g.K=function(a,b,c){var d=this.a,e=arguments,f=String(e[0]),h=e[1];if(!Rb&&h&&(h.name||h.type)){f=["<",f];h.name&&f.push(' name="',Za(h.name),'"');if(h.type){f.push(' type="',Za(h.type),'"');var k={};Pa(k,h);delete k.type;h=k}f.push(">");f=f.join("")}f=V(d,f);h&&("string"===typeof h?f.className=h:w(h)?f.className=h.join(" "):ac(f,h));2<e.length&&gc(d,f,e,2);return f};g.T=T.prototype.K;g.Pa=function(a){return this.a.createTextNode(String(a))};
g.W=function(a,b,c){var d=this.a;c=!!c;for(var e=V(d,"TABLE"),f=e.appendChild(V(d,"TBODY")),h=0;h<a;h++){for(var k=V(d,"TR"),l=0;l<b;l++){var m=V(d,"TD");c&&pc(m,"\u00a0");k.appendChild(m)}f.appendChild(k)}return e};g.yb=function(a){var b=this.a;var c=V(b,"DIV");E?(a=Va(Wa,a),Ya(c,a),c.removeChild(c.firstChild)):Ya(c,a);if(1==c.childNodes.length)c=c.removeChild(c.firstChild);else{for(b=b.createDocumentFragment();c.firstChild;)b.appendChild(c.firstChild);c=b}return c};g.gb=function(){return dc(this.a)};
g.ma=function(){return ec(this.a)};g.la=function(){var a=this.a,b=ec(a);a=fc(a);return E&&I("10")&&a.pageYOffset!=b.scrollTop?new S(b.scrollLeft,b.scrollTop):new S(a.pageXOffset||b.scrollLeft,a.pageYOffset||b.scrollTop)};g.ca=function(a){a=a||this.a;try{var b=a&&a.activeElement;var c=b&&b.nodeName?b:null}catch(d){c=null}return c};g.Na=function(a,b){a.appendChild(b)};g.Ma=function(a,b){gc(U(a),a,arguments,1)};g.Oa=function(a){if(1!=a.nodeType)return!1;switch(a.tagName){case "APPLET":case "AREA":case "BASE":case "BR":case "COL":case "COMMAND":case "EMBED":case "FRAME":case "HR":case "IMG":case "INPUT":case "IFRAME":case "ISINDEX":case "KEYGEN":case "LINK":case "NOFRAMES":case "NOSCRIPT":case "META":case "OBJECT":case "PARAM":case "SCRIPT":case "SOURCE":case "STYLE":case "TRACK":case "WBR":return!1}return!0};
g.vb=jc;g.fb=function(a,b){b.parentNode&&b.parentNode.insertBefore(a,b)};g.eb=function(a,b){b.parentNode&&b.parentNode.insertBefore(a,b.nextSibling)};g.cb=function(a,b,c){a.insertBefore(b,a.childNodes[c]||null)};g.Ra=W;g.Sa=function(a,b){var c=b.parentNode;c&&c.replaceChild(a,b)};g.ba=function(a){var b,c=a.parentNode;if(c&&11!=c.nodeType){if(a.removeNode)return a.removeNode(!1);for(;b=a.firstChild;)c.insertBefore(b,a);return W(a)}};
g.ha=function(a){return Sb&&void 0!=a.children?a.children:ya(a.childNodes,function(b){return 1==b.nodeType})};g.ra=function(a){return void 0!==a.firstElementChild?a.firstElementChild:kc(a.firstChild,!0)};g.ua=function(a){return void 0!==a.lastElementChild?a.lastElementChild:kc(a.lastChild,!1)};g.xa=function(a){return void 0!==a.nextElementSibling?a.nextElementSibling:kc(a.nextSibling,!0)};g.Fa=function(a){return void 0!==a.previousElementSibling?a.previousElementSibling:kc(a.previousSibling,!1)};
g.ya=function(a){if(!a)return null;if(a.firstChild)return a.firstChild;for(;a&&!a.nextSibling;)a=a.parentNode;return a?a.nextSibling:null};g.Ga=function(a){if(!a)return null;if(!a.previousSibling)return a.parentNode;for(a=a.previousSibling;a&&a.lastChild;)a=a.lastChild;return a};g.lb=hc;g.hb=lc;g.nb=function(a){return x(a)&&a.window==a};g.Ea=function(a){var b;if(Ub&&!(E&&I("9")&&!I("10")&&u.SVGElement&&a instanceof u.SVGElement)&&(b=a.parentElement))return b;b=a.parentNode;return lc(b)?b:null};
g.contains=mc;
g.V=function(a,b){if(a==b)return 0;if(a.compareDocumentPosition)return a.compareDocumentPosition(b)&2?1:-1;if(E&&!(9<=Number(J))){if(9==a.nodeType)return-1;if(9==b.nodeType)return 1}if("sourceIndex"in a||a.parentNode&&"sourceIndex"in a.parentNode){var c=1==a.nodeType,d=1==b.nodeType;if(c&&d)return a.sourceIndex-b.sourceIndex;var e=a.parentNode,f=b.parentNode;return e==f?oc(a,b):!c&&mc(e,b)?-1*nc(a,b):!d&&mc(f,a)?nc(b,a):(c?a.sourceIndex:e.sourceIndex)-(d?b.sourceIndex:f.sourceIndex)}d=U(a);c=d.createRange();
c.selectNode(a);c.collapse(!0);a=d.createRange();a.selectNode(b);a.collapse(!0);return c.compareBoundaryPoints(u.Range.START_TO_END,a)};g.Y=function(a){var b,c=arguments.length;if(!c)return null;if(1==c)return arguments[0];var d=[],e=Infinity;for(b=0;b<c;b++){for(var f=[],h=arguments[b];h;)f.unshift(h),h=h.parentNode;d.push(f);e=Math.min(e,f.length)}f=null;for(b=0;b<e;b++){h=d[0][b];for(var k=1;k<c;k++)if(h!=d[k][b])return f;f=h}return f};g.Da=U;g.sa=function(a){return a.contentDocument||a.contentWindow.document};
g.ta=function(a){try{var b;if(!(b=a.contentWindow)){if(a.contentDocument){var c=a.contentDocument;var d=c?fc(c):window}else d=null;b=d}return b}catch(e){}return null};g.Eb=pc;g.Ca=function(a){if("outerHTML"in a)return a.outerHTML;var b=V(U(a),"DIV");b.appendChild(a.cloneNode(!0));return b.innerHTML};g.Z=function(a,b){var c=[];return qc(a,b,c,!0)?c[0]:void 0};g.$=function(a,b){var c=[];qc(a,b,c,!1);return c};g.kb=tc;g.Cb=function(a,b){b?a.tabIndex=0:(a.tabIndex=-1,a.removeAttribute("tabIndex"))};
g.jb=function(a){var b;if((b="A"==a.tagName&&a.hasAttribute("href")||"INPUT"==a.tagName||"TEXTAREA"==a.tagName||"SELECT"==a.tagName||"BUTTON"==a.tagName?!a.disabled&&(!uc(a)||vc(a)):tc(a))&&E){var c;"function"!=v(a.getBoundingClientRect)||E&&null==a.parentElement?c={height:a.offsetHeight,width:a.offsetWidth}:c=a.getBoundingClientRect();a=null!=c&&0<c.height&&0<c.width}else a=b;return a};g.Ka=wc;g.Aa=function(a){return wc(a).length};
g.Ba=function(a,b){b=b||U(a).body;for(var c=[];a&&a!=b;){for(var d=a;d=d.previousSibling;)c.unshift(wc(d));a=a.parentNode}return c.join("").replace(/^[\s\xa0]+/,"").replace(/ +/g," ").length};
g.za=function(a,b,c){a=[a];for(var d=0,e=null;0<a.length&&d<b;)if(e=a.pop(),!(e.nodeName in rc))if(3==e.nodeType){var f=e.nodeValue.replace(/(\r\n|\r|\n)/g,"").replace(/ +/g," ");d+=f.length}else if(e.nodeName in sc)d+=sc[e.nodeName].length;else for(f=e.childNodes.length-1;0<=f;f--)a.push(e.childNodes[f]);x(c)&&(c.ub=e?e.nodeValue.length+b-d-1:0,c.node=e);return e};g.mb=ic;g.fa=yc;g.ea=function(a,b,c){return yc(a,null,b,c)};g.da=zc;g.ga=function(a){return a.getContext("2d")};var Ac=!/^\s*class\s*\{\s*\}\s*$/.test(function(){}.toString());/*

 Copyright (c) 2016 The Polymer Project Authors. All rights reserved.
 This code may only be used under the BSD style license found at http://polymer.github.io/LICENSE.txt
 The complete set of authors may be found at http://polymer.github.io/AUTHORS.txt
 The complete set of contributors may be found at http://polymer.github.io/CONTRIBUTORS.txt
 Code distributed by Google as part of the polymer project is also
 subject to an additional IP rights grant found at http://polymer.github.io/PATENTS.txt
*/
(function(){if(Ac&&!HTMLElement.es5Shimmed&&void 0!==window.Reflect&&void 0!==window.customElements&&!window.customElements.polyfillWrapFlushCallback){var a=HTMLElement;window.HTMLElement=function(){return Reflect.construct(a,[],this.constructor)};HTMLElement.prototype=a.prototype;HTMLElement.prototype.constructor=HTMLElement;HTMLElement.es5Shimmed=!0;Object.setPrototypeOf(HTMLElement,a)}})();function X(a){var b=HTMLElement.call(this)||this;a&&Bc(a);return b}ja(X,HTMLElement);X.prototype.I=function(){console.warn(this.tagName,"has not implemented update")};X.prototype.j=function(a){a=void 0===a?"":a;return document.createRange().createContextualFragment(a||"")};
X.prototype.H=function(a,b,c){a&&b?a.parentNode.replaceChild(document.importNode(b,!0),a):!b&&a?a.parentNode.removeChild(a):!a&&b&&(c?(a=document.importNode(b,!0),c.parentElement.insertBefore(a,c.nextSibling)):this.appendChild(document.importNode(b,!0)))};function Bc(a){"string"===typeof a&&(a=[a]);document.body.dispatchEvent(new CustomEvent("devsite-load-custom-elements",{bubbles:!0,detail:a}))};var Cc=new Map;function Y(a){var b=X.call(this)||this;a&&Bc(a);return b}ja(Y,X);Y.prototype.connectedCallback=function(){var a=this.constructor,b=Cc.get(a);b?console.error("can't add duplicate element to page: "+b.tagName):Cc.set(a,this)};Y.prototype.disconnectedCallback=function(){var a=this.constructor;Cc.get(a)===this&&Cc.delete(a)};Y.prototype.disconnectedCallback=Y.prototype.disconnectedCallback;Y.prototype.connectedCallback=Y.prototype.connectedCallback;function Dc(a,b){window.getSelection().removeAllRanges();var c=document.createElement("pre");c.setAttribute("is-upgraded","");c.style.position="absolute";c.style.top="-99999px";c.style.left="-99999px";c.classList.add("clear-for-copy");Array.from(b.childNodes).forEach(function(d){d.classList&&d.classList.contains("no-select")||c.appendChild(d.cloneNode(!0))});a.appendChild(c);return c}
function Ec(a,b){a=Dc(a,b);b=!1;window.getSelection().selectAllChildren(a);window.getSelection().toString()&&document.queryCommandSupported("copy")&&(document.execCommand("copy"),b=!0);window.getSelection().removeAllRanges();W(a);return b}function Fc(a,b){var c=document.createElement("pre");c.setAttribute("is-upgraded","");b.forEach(function(d){c.appendChild(d.cloneNode(!0))});b=document.querySelector("devsite-snackbar");Ec(a,c)&&b&&b.setAttribute("type","copied-to-clipboard");W(c)};function Gc(a){K.call(this);this.c=a;this.a={}}ua(Gc,K);var Hc=[];function Ic(a,b,c,d){P(a,b,c,d,void 0)}g=Gc.prototype;g.pb=function(a,b,c,d,e){return P(this,a,b,c,d,e)};function P(a,b,c,d,e,f){w(c)||(c&&(Hc[0]=c.toString()),c=Hc);for(var h=0;h<c.length;h++){var k=zb(b,c[h],d||a.handleEvent,e||!1,f||a.c||a);if(!k)break;a.a[k.key]=k}return a}g.Ua=function(a,b,c,d){return Jc(this,a,b,c,d)};g.ob=function(a,b,c,d,e){return Jc(this,a,b,c,d,e)};
function Jc(a,b,c,d,e,f){if(w(c))for(var h=0;h<c.length;h++)Jc(a,b,c[h],d,e,f);else{b=Ab(b,c,d||a.handleEvent,e,f||a.c||a);if(!b)return a;a.a[b.key]=b}return a}g.qb=function(a,b,c,d){P(b,a,c,d,this.c||this);return this};g.rb=function(a,b,c,d,e){P(b,a,c,d,e||this.c||this);return this};g.Ta=function(){var a=0,b;for(b in this.a)Object.prototype.hasOwnProperty.call(this.a,b)&&a++;return a};
function Kc(a,b,c,d,e,f){if(w(c))for(var h=0;h<c.length;h++)Kc(a,b,c[h],d,e,f);else d=d||a.handleEvent,e=x(e)?!!e.capture:!!e,f=f||a.c||a,d=Bb(d),e=!!e,b&&b[N]?c=b.D(c,d,e,f):b?(b=Q(b))?(c=b.a[c.toString()],b=-1,c&&(b=vb(c,d,e,f)),c=-1<b?c[b]:null):c=null:c=null,c&&(Gb(c),delete a.a[c.key])}g.Gb=function(a,b,c,d,e){Kc(b,a,c,d,e||this.c||this,this);return this};function Lc(a){Ma(a.a,function(b,c){this.a.hasOwnProperty(c)&&Gb(b)},a);a.a={}}g.s=function(){Gc.m.s.call(this);Lc(this)};
g.handleEvent=function(){throw Error("EventHandler.handleEvent not implemented");};var Mc="onpointermove"in window?"pointermove":"mousemove";
function Z(){var a=Y.call(this)||this;a.b=new Gc;a.a=null;var b="Copy link to this section".replace(Qb,Pb);var c=Nb('<button role="button" class="devsite-heading-link button-flat material-icons" title="'+b+'"></button>');b=Xb();b=V(b.a,"DIV");if(x(c))if(c instanceof R){if(c.B!==Kb)throw Error("Sanitized content was not of kind HTML.");c=D(c.toString(),c.A||null)}else c=C("zSoyz");else c=C(String(c));Ya(b,c);1==b.childNodes.length&&(c=b.firstChild,1==c.nodeType&&(b=c));a.c=b;return a}ja(Z,Y);
Z.prototype.connectedCallback=function(){Y.prototype.connectedCallback.call(this);Nc(this)};Z.prototype.disconnectedCallback=function(){Y.prototype.disconnectedCallback.call(this);Lc(this.b)};
function Nc(a){Ic(a.b,document.body,Mc,function(b){return void Oc(a,b)});Ic(a.b,a.c,"click",function(b){b.l();b.v();b=a.a.querySelector("h1, h2, h3, h4, h5, h6");var c=b.id||b.getAttribute("name");c&&(b=new URL(document.location.toString()),b.hash=c,c=document.createElement("div"),c.innerText=b.href,Fc(a,[c]),W(c))})}
function Oc(a,b){b=b.target;b.matches&&b.matches("devsite-heading[link]")||(b=zc(b,function(c){return c instanceof Element?c.matches("devsite-heading[link]"):!1},!1,8));b?Pc(a,b):Qc(a)}function Pc(a,b){a.a||(a.a=b,a.a.querySelector("h1, h2, h3, h4, h5, h6").appendChild(a.c))}function Qc(a){a.a&&(a.c.remove(),a.a=null)}Z.prototype.disconnectedCallback=Z.prototype.disconnectedCallback;Z.prototype.connectedCallback=Z.prototype.connectedCallback;try{window.customElements.define("devsite-heading-link",Z)}catch(a){console.warn("devsite.app.customElement.DevsiteHeadingLink",a)};}).call(this);
