(function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
'use strict';var m;function aa(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}}function p(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return b?b.call(a):{next:aa(a)}}var ba="function"==typeof Object.create?Object.create:function(a){function b(){}b.prototype=a;return new b},q;
if("function"==typeof Object.setPrototypeOf)q=Object.setPrototypeOf;else{var u;a:{var ca={A:!0},da={};try{da.__proto__=ca;u=da.A;break a}catch(a){}u=!1}q=u?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var v=q;
function w(a,b){a.prototype=ba(b.prototype);a.prototype.constructor=a;if(v)v(a,b);else for(var c in b)if("prototype"!=c)if(Object.defineProperties){var d=Object.getOwnPropertyDescriptor(b,c);d&&Object.defineProperty(a,c,d)}else a[c]=b[c];a.da=b.prototype}var x="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)};
function ea(a){a=["object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global,a];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}return globalThis}var y=ea(this);function A(a,b){if(b){var c=y;a=a.split(".");for(var d=0;d<a.length-1;d++){var h=a[d];h in c||(c[h]={});c=c[h]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&x(c,a,{configurable:!0,writable:!0,value:b})}}
A("Promise",function(a){function b(g){this.b=0;this.h=void 0;this.a=[];var e=this.c();try{g(e.resolve,e.reject)}catch(f){e.reject(f)}}function c(){this.a=null}function d(g){return g instanceof b?g:new b(function(e){e(g)})}if(a)return a;c.prototype.b=function(g){if(null==this.a){this.a=[];var e=this;this.c(function(){e.h()})}this.a.push(g)};var h=y.setTimeout;c.prototype.c=function(g){h(g,0)};c.prototype.h=function(){for(;this.a&&this.a.length;){var g=this.a;this.a=[];for(var e=0;e<g.length;++e){var f=
g[e];g[e]=null;try{f()}catch(k){this.f(k)}}}this.a=null};c.prototype.f=function(g){this.c(function(){throw g;})};b.prototype.c=function(){function g(k){return function(n){f||(f=!0,k.call(e,n))}}var e=this,f=!1;return{resolve:g(this.B),reject:g(this.f)}};b.prototype.B=function(g){if(g===this)this.f(new TypeError("A Promise cannot resolve to itself"));else if(g instanceof b)this.C(g);else{a:switch(typeof g){case "object":var e=null!=g;break a;case "function":e=!0;break a;default:e=!1}e?this.u(g):this.j(g)}};
b.prototype.u=function(g){var e=void 0;try{e=g.then}catch(f){this.f(f);return}"function"==typeof e?this.D(e,g):this.j(g)};b.prototype.f=function(g){this.l(2,g)};b.prototype.j=function(g){this.l(1,g)};b.prototype.l=function(g,e){if(0!=this.b)throw Error("Cannot settle("+g+", "+e+"): Promise already settled in state"+this.b);this.b=g;this.h=e;this.m()};b.prototype.m=function(){if(null!=this.a){for(var g=0;g<this.a.length;++g)l.b(this.a[g]);this.a=null}};var l=new c;b.prototype.C=function(g){var e=this.c();
g.v(e.resolve,e.reject)};b.prototype.D=function(g,e){var f=this.c();try{g.call(e,f.resolve,f.reject)}catch(k){f.reject(k)}};b.prototype.then=function(g,e){function f(t,z){return"function"==typeof t?function(S){try{k(t(S))}catch(T){n(T)}}:z}var k,n,r=new b(function(t,z){k=t;n=z});this.v(f(g,k),f(e,n));return r};b.prototype.catch=function(g){return this.then(void 0,g)};b.prototype.v=function(g,e){function f(){switch(k.b){case 1:g(k.h);break;case 2:e(k.h);break;default:throw Error("Unexpected state: "+
k.b);}}var k=this;null==this.a?l.b(f):this.a.push(f)};b.resolve=d;b.reject=function(g){return new b(function(e,f){f(g)})};b.race=function(g){return new b(function(e,f){for(var k=p(g),n=k.next();!n.done;n=k.next())d(n.value).v(e,f)})};b.all=function(g){var e=p(g),f=e.next();return f.done?d([]):new b(function(k,n){function r(S){return function(T){t[S]=T;z--;0==z&&k(t)}}var t=[],z=0;do t.push(void 0),z++,d(f.value).v(r(t.length-1),n),f=e.next();while(!f.done)})};return b});
var fa=function(){function a(){function c(){}new c;Reflect.construct(c,[],function(){});return new c instanceof c}if("undefined"!=typeof Reflect&&Reflect.construct){if(a())return Reflect.construct;var b=Reflect.construct;return function(c,d,h){c=b(c,d);h&&Reflect.setPrototypeOf(c,h.prototype);return c}}return function(c,d,h){void 0===h&&(h=c);h=ba(h.prototype||Object.prototype);return Function.prototype.apply.call(c,h,d)||h}}();A("Reflect.construct",function(){return fa});
A("Object.setPrototypeOf",function(a){return a||v});function ha(){ha=function(){};y.Symbol||(y.Symbol=ia)}function ja(a,b){this.a=a;x(this,"description",{configurable:!0,writable:!0,value:b})}ja.prototype.toString=function(){return this.a};var ia=function(){function a(c){if(this instanceof a)throw new TypeError("Symbol is not a constructor");return new ja("jscomp_symbol_"+(c||"")+"_"+b++,c)}var b=0;return a}();
function B(){ha();var a=y.Symbol.iterator;a||(a=y.Symbol.iterator=y.Symbol("Symbol.iterator"));"function"!=typeof Array.prototype[a]&&x(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return ka(aa(this))}});B=function(){}}function ka(a){B();a={next:a};a[y.Symbol.iterator]=function(){return this};return a}function C(a,b){return Object.prototype.hasOwnProperty.call(a,b)}
A("WeakMap",function(a){function b(f){this.a=(e+=Math.random()+1).toString();if(f){f=p(f);for(var k;!(k=f.next()).done;)k=k.value,this.set(k[0],k[1])}}function c(){}function d(f){var k=typeof f;return"object"===k&&null!==f||"function"===k}function h(f){if(!C(f,g)){var k=new c;x(f,g,{value:k})}}function l(f){var k=Object[f];k&&(Object[f]=function(n){if(n instanceof c)return n;h(n);return k(n)})}if(function(){if(!a||!Object.seal)return!1;try{var f=Object.seal({}),k=Object.seal({}),n=new a([[f,2],[k,
3]]);if(2!=n.get(f)||3!=n.get(k))return!1;n.delete(f);n.set(k,4);return!n.has(f)&&4==n.get(k)}catch(r){return!1}}())return a;var g="$jscomp_hidden_"+Math.random();l("freeze");l("preventExtensions");l("seal");var e=0;b.prototype.set=function(f,k){if(!d(f))throw Error("Invalid WeakMap key");h(f);if(!C(f,g))throw Error("WeakMap key fail: "+f);f[g][this.a]=k;return this};b.prototype.get=function(f){return d(f)&&C(f,g)?f[g][this.a]:void 0};b.prototype.has=function(f){return d(f)&&C(f,g)&&C(f[g],this.a)};
b.prototype.delete=function(f){return d(f)&&C(f,g)&&C(f[g],this.a)?delete f[g][this.a]:!1};return b});
A("Map",function(a){function b(){var e={};return e.o=e.next=e.head=e}function c(e,f){var k=e.a;return ka(function(){if(k){for(;k.head!=e.a;)k=k.o;for(;k.next!=k.head;)return k=k.next,{done:!1,value:f(k)};k=null}return{done:!0,value:void 0}})}function d(e,f){var k=f&&typeof f;"object"==k||"function"==k?l.has(f)?k=l.get(f):(k=""+ ++g,l.set(f,k)):k="p_"+f;var n=e.b[k];if(n&&C(e.b,k))for(e=0;e<n.length;e++){var r=n[e];if(f!==f&&r.key!==r.key||f===r.key)return{id:k,list:n,index:e,g:r}}return{id:k,list:n,
index:-1,g:void 0}}function h(e){this.b={};this.a=b();this.size=0;if(e){e=p(e);for(var f;!(f=e.next()).done;)f=f.value,this.set(f[0],f[1])}}if(function(){if(!a||"function"!=typeof a||!a.prototype.entries||"function"!=typeof Object.seal)return!1;try{var e=Object.seal({x:4}),f=new a(p([[e,"s"]]));if("s"!=f.get(e)||1!=f.size||f.get({x:4})||f.set({x:4},"t")!=f||2!=f.size)return!1;var k=f.entries(),n=k.next();if(n.done||n.value[0]!=e||"s"!=n.value[1])return!1;n=k.next();return n.done||4!=n.value[0].x||
"t"!=n.value[1]||!k.next().done?!1:!0}catch(r){return!1}}())return a;B();var l=new WeakMap;h.prototype.set=function(e,f){e=0===e?0:e;var k=d(this,e);k.list||(k.list=this.b[k.id]=[]);k.g?k.g.value=f:(k.g={next:this.a,o:this.a.o,head:this.a,key:e,value:f},k.list.push(k.g),this.a.o.next=k.g,this.a.o=k.g,this.size++);return this};h.prototype.delete=function(e){e=d(this,e);return e.g&&e.list?(e.list.splice(e.index,1),e.list.length||delete this.b[e.id],e.g.o.next=e.g.next,e.g.next.o=e.g.o,e.g.head=null,
this.size--,!0):!1};h.prototype.clear=function(){this.b={};this.a=this.a.o=b();this.size=0};h.prototype.has=function(e){return!!d(this,e).g};h.prototype.get=function(e){return(e=d(this,e).g)&&e.value};h.prototype.entries=function(){return c(this,function(e){return[e.key,e.value]})};h.prototype.keys=function(){return c(this,function(e){return e.key})};h.prototype.values=function(){return c(this,function(e){return e.value})};h.prototype.forEach=function(e,f){for(var k=this.entries(),n;!(n=k.next()).done;)n=
n.value,e.call(f,n[1],n[0],this)};h.prototype[Symbol.iterator]=h.prototype.entries;var g=0;return h});var la=this||self;
function ma(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b}function D(a){var b=ma(a);return"array"==b||"object"==b&&"number"==typeof a.length}var na=Date.now||function(){return+new Date};var oa=Array.prototype.indexOf?function(a,b){return Array.prototype.indexOf.call(a,b,void 0)}:function(a,b){if("string"===typeof a)return"string"!==typeof b||1!=b.length?-1:a.indexOf(b,0);for(var c=0;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},pa=Array.prototype.forEach?function(a,b,c){Array.prototype.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,h="string"===typeof a?a.split(""):a,l=0;l<d;l++)l in h&&b.call(c,h[l],l,a)};
function qa(a){return Array.prototype.concat.apply([],arguments)}function ra(a){var b=a.length;if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]};var sa="StopIteration"in la?la.StopIteration:{message:"StopIteration",stack:""};function E(){}E.prototype.next=function(){throw sa;};E.prototype.a=function(){return this};function F(a,b){this.b={};this.a=[];this.f=this.c=0;var c=arguments.length;if(1<c){if(c%2)throw Error("Uneven number of arguments");for(var d=0;d<c;d+=2)this.set(arguments[d],arguments[d+1])}else if(a)if(a instanceof F)for(c=a.s(),d=0;d<c.length;d++)this.set(c[d],a.get(c[d]));else for(d in a)this.set(d,a[d])}m=F.prototype;m.i=function(){G(this);for(var a=[],b=0;b<this.a.length;b++)a.push(this.b[this.a[b]]);return a};m.s=function(){G(this);return this.a.concat()};
m.W=function(a){for(var b=0;b<this.a.length;b++){var c=this.a[b];if(H(this.b,c)&&this.b[c]==a)return!0}return!1};m.F=function(a,b){if(this===a)return!0;if(this.c!=a.c)return!1;b=b||ta;G(this);for(var c,d=0;c=this.a[d];d++)if(!b(this.get(c),a.get(c)))return!1;return!0};function ta(a,b){return a===b}m.X=function(){return 0==this.c};m.V=function(){this.b={};this.f=this.c=this.a.length=0};
function G(a){if(a.c!=a.a.length){for(var b=0,c=0;b<a.a.length;){var d=a.a[b];H(a.b,d)&&(a.a[c++]=d);b++}a.a.length=c}if(a.c!=a.a.length){var h={};for(c=b=0;b<a.a.length;)d=a.a[b],H(h,d)||(a.a[c++]=d,h[d]=1),b++;a.a.length=c}}m.get=function(a,b){return H(this.b,a)?this.b[a]:b};m.set=function(a,b){H(this.b,a)||(this.c++,this.a.push(a),this.f++);this.b[a]=b};m.forEach=function(a,b){for(var c=this.s(),d=0;d<c.length;d++){var h=c[d],l=this.get(h);a.call(b,l,h,this)}};
m.fa=function(){for(var a=new F,b=0;b<this.a.length;b++){var c=this.a[b];a.set(this.b[c],c)}return a};m.ea=function(){G(this);for(var a={},b=0;b<this.a.length;b++){var c=this.a[b];a[c]=this.b[c]}return a};m.I=function(){return ua(this,!0)};m.L=function(){return ua(this,!1)};function ua(a,b){G(a);var c=0,d=a.f,h=new E;h.next=function(){if(d!=a.f)throw Error("The map has changed since the iterator was created");if(c>=a.a.length)throw sa;var l=a.a[c++];return b?l:a.b[l]};return h}
function H(a,b){return Object.prototype.hasOwnProperty.call(a,b)};function va(a){if(a.i&&"function"==typeof a.i)return a.i();if("string"===typeof a)return a.split("");if(D(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}b=[];c=0;for(d in a)b[c++]=a[d];return b}
function wa(a,b,c){if(a.forEach&&"function"==typeof a.forEach)a.forEach(b,c);else if(D(a)||"string"===typeof a)pa(a,b,c);else{if(a.s&&"function"==typeof a.s)var d=a.s();else if(a.i&&"function"==typeof a.i)d=void 0;else if(D(a)||"string"===typeof a){d=[];for(var h=a.length,l=0;l<h;l++)d.push(l)}else for(l in d=[],h=0,a)d[h++]=l;h=va(a);l=h.length;for(var g=0;g<l;g++)b.call(c,h[g],d&&d[g],a)}};var xa=/^(?:([^:/?#.]+):)?(?:\/\/(?:([^/?#]*)@)?([^/#?]*?)(?::([0-9]+))?(?=[/\\#?]|$))?([^?#]+)?(?:\?([^#]*))?(?:#([\s\S]*))?$/;function ya(a,b){if(a){a=a.split("&");for(var c=0;c<a.length;c++){var d=a[c].indexOf("="),h=null;if(0<=d){var l=a[c].substring(0,d);h=a[c].substring(d+1)}else l=a[c];b(l,h?decodeURIComponent(h.replace(/\+/g," ")):"")}}};function I(a,b){this.b=this.m=this.j="";this.f=null;this.l=this.c="";this.h=this.u=!1;if(a instanceof I){this.h=void 0!==b?b:a.h;J(this,a.j);var c=a.m;K(this);this.m=c;c=a.b;K(this);this.b=c;L(this,a.f);c=a.c;K(this);this.c=c;M(this,za(a.a));a=a.l;K(this);this.l=a}else a&&(c=String(a).match(xa))?(this.h=!!b,J(this,c[1]||"",!0),a=c[2]||"",K(this),this.m=N(a),a=c[3]||"",K(this),this.b=N(a,!0),L(this,c[4]),a=c[5]||"",K(this),this.c=N(a,!0),M(this,c[6]||"",!0),a=c[7]||"",K(this),this.l=N(a)):(this.h=
!!b,this.a=new O(null,this.h))}m=I.prototype;m.toString=function(){var a=[],b=this.j;b&&a.push(P(b,Aa,!0),":");var c=this.b;if(c||"file"==b)a.push("//"),(b=this.m)&&a.push(P(b,Aa,!0),"@"),a.push(encodeURIComponent(String(c)).replace(/%25([0-9a-fA-F]{2})/g,"%$1")),c=this.f,null!=c&&a.push(":",String(c));if(c=this.c)this.b&&"/"!=c.charAt(0)&&a.push("/"),a.push(P(c,"/"==c.charAt(0)?Ba:Ca,!0));(c=this.a.toString())&&a.push("?",c);(c=this.l)&&a.push("#",P(c,Da));return a.join("")};
m.resolve=function(a){var b=new I(this),c=!!a.j;c?J(b,a.j):c=!!a.m;if(c){var d=a.m;K(b);b.m=d}else c=!!a.b;c?(d=a.b,K(b),b.b=d):c=null!=a.f;d=a.c;if(c)L(b,a.f);else if(c=!!a.c){if("/"!=d.charAt(0))if(this.b&&!this.c)d="/"+d;else{var h=b.c.lastIndexOf("/");-1!=h&&(d=b.c.substr(0,h+1)+d)}h=d;if(".."==h||"."==h)d="";else if(-1!=h.indexOf("./")||-1!=h.indexOf("/.")){d=0==h.lastIndexOf("/",0);h=h.split("/");for(var l=[],g=0;g<h.length;){var e=h[g++];"."==e?d&&g==h.length&&l.push(""):".."==e?((1<l.length||
1==l.length&&""!=l[0])&&l.pop(),d&&g==h.length&&l.push("")):(l.push(e),d=!0)}d=l.join("/")}else d=h}c?(K(b),b.c=d):c=""!==a.a.toString();c?M(b,za(a.a)):c=!!a.l;c&&(a=a.l,K(b),b.l=a);return b};function J(a,b,c){K(a);a.j=c?N(b,!0):b;a.j&&(a.j=a.j.replace(/:$/,""))}function L(a,b){K(a);if(b){b=Number(b);if(isNaN(b)||0>b)throw Error("Bad port number "+b);a.f=b}else a.f=null}function M(a,b,c){K(a);b instanceof O?(a.a=b,Ea(a.a,a.h)):(c||(b=P(b,Fa)),a.a=new O(b,a.h));return a}
m.ba=function(a,b){return M(this,a,b)};m.H=function(){return N(this.a.toString())};m.S=function(){return this.a.toString()};m.aa=function(a,b){K(this);"array"==ma(b)||(b=[String(b)]);Ga(this.a,a,b);return this};m.K=function(a){return this.a.i(a)};m.J=function(a){return this.a.get(a)};m.Y=function(a){return(!this.b&&!a.b||this.b==a.b)&&(null==this.f&&null==a.f||this.f==a.f)};
m.$=function(){K(this);var a=Math.floor(2147483648*Math.random()).toString(36)+Math.abs(Math.floor(2147483648*Math.random())^na()).toString(36);K(this);this.a.set("zx",a);return this};m.T=function(a){K(this);Q(this.a,a);return this};m.ca=function(a){this.u=a;return this};m.Z=function(){return this.u};function K(a){if(a.u)throw Error("Tried to modify a read-only Uri");}m.U=function(a){this.h=a;this.a&&Ea(this.a,a);return this};
function N(a,b){return a?b?decodeURI(a.replace(/%25/g,"%2525")):decodeURIComponent(a):""}function P(a,b,c){return"string"===typeof a?(a=encodeURI(a).replace(b,Ha),c&&(a=a.replace(/%25([0-9a-fA-F]{2})/g,"%$1")),a):null}function Ha(a){a=a.charCodeAt(0);return"%"+(a>>4&15).toString(16)+(a&15).toString(16)}var Aa=/[#\/\?@]/g,Ca=/[#\?:]/g,Ba=/[#\?]/g,Fa=/[#\?@]/g,Da=/#/g;function O(a,b){this.b=this.a=null;this.c=a||null;this.f=!!b}
function R(a){a.a||(a.a=new F,a.b=0,a.c&&ya(a.c,function(b,c){a.add(decodeURIComponent(b.replace(/\+/g," ")),c)}))}m=O.prototype;m.P=function(){R(this);return this.b};m.add=function(a,b){R(this);this.c=null;a=U(this,a);var c=this.a.get(a);c||this.a.set(a,c=[]);c.push(b);this.b+=1;return this};function Q(a,b){R(a);b=U(a,b);H(a.a.b,b)&&(a.c=null,a.b-=a.a.get(b).length,a=a.a,H(a.b,b)&&(delete a.b[b],a.c--,a.f++,a.a.length>2*a.c&&G(a)))}m.M=function(){this.a=this.c=null;this.b=0};
m.R=function(){R(this);return 0==this.b};function Ia(a,b){R(a);b=U(a,b);return H(a.a.b,b)}m.N=function(a){var b=this.i();return 0<=oa(b,a)};m.forEach=function(a,b){R(this);this.a.forEach(function(c,d){pa(c,function(h){a.call(b,h,d,this)},this)},this)};m.s=function(){R(this);for(var a=this.a.i(),b=this.a.s(),c=[],d=0;d<b.length;d++)for(var h=a[d],l=0;l<h.length;l++)c.push(b[d]);return c};
m.i=function(a){R(this);var b=[];if("string"===typeof a)Ia(this,a)&&(b=qa(b,this.a.get(U(this,a))));else{a=this.a.i();for(var c=0;c<a.length;c++)b=qa(b,a[c])}return b};m.set=function(a,b){R(this);this.c=null;a=U(this,a);Ia(this,a)&&(this.b-=this.a.get(a).length);this.a.set(a,[b]);this.b+=1;return this};m.get=function(a,b){if(!a)return b;a=this.i(a);return 0<a.length?String(a[0]):b};function Ga(a,b,c){Q(a,b);0<c.length&&(a.c=null,a.a.set(U(a,b),ra(c)),a.b+=c.length)}
m.toString=function(){if(this.c)return this.c;if(!this.a)return"";for(var a=[],b=this.a.s(),c=0;c<b.length;c++){var d=b[c],h=encodeURIComponent(String(d));d=this.i(d);for(var l=0;l<d.length;l++){var g=h;""!==d[l]&&(g+="="+encodeURIComponent(String(d[l])));a.push(g)}}return this.c=a.join("&")};m.G=function(a){R(this);this.a.forEach(function(b,c){0<=oa(a,c)||Q(this,c)},this);return this};function za(a){var b=new O;b.c=a.c;a.a&&(b.a=new F(a.a),b.b=a.b);return b}
function U(a,b){b=String(b);a.f&&(b=b.toLowerCase());return b}function Ea(a,b){b&&!a.f&&(R(a),a.c=null,a.a.forEach(function(c,d){var h=d.toLowerCase();d!=h&&(Q(this,d),Ga(this,h,c))},a));a.f=b}m.O=function(a){for(var b=0;b<arguments.length;b++)wa(arguments[b],function(c,d){this.add(d,c)},this)};var Ja={};function Ka(a,b){var c=Ja[a];if(void 0===c||c.w&&!(Date.now()<=c.w+3E5)){c=new Promise(function(h,l){b.onload=function(){return h(b)};b.onerror=function(g){b.parentNode&&b.parentNode.removeChild(b);l(g)};document.head.appendChild(b)});var d={w:0,p:c};c.catch(function(){return d.w=+new Date});Ja[a]=d}};var La=!/^\s*class\s*\{\s*\}\s*$/.test(function(){}.toString());/*

 Copyright (c) 2016 The Polymer Project Authors. All rights reserved.
 This code may only be used under the BSD style license found at http://polymer.github.io/LICENSE.txt
 The complete set of authors may be found at http://polymer.github.io/AUTHORS.txt
 The complete set of contributors may be found at http://polymer.github.io/CONTRIBUTORS.txt
 Code distributed by Google as part of the polymer project is also
 subject to an additional IP rights grant found at http://polymer.github.io/PATENTS.txt
*/
(function(){if(La&&!HTMLElement.es5Shimmed&&void 0!==window.Reflect&&void 0!==window.customElements&&!window.customElements.polyfillWrapFlushCallback){var a=HTMLElement;window.HTMLElement=function(){return Reflect.construct(a,[],this.constructor)};HTMLElement.prototype=a.prototype;HTMLElement.prototype.constructor=HTMLElement;HTMLElement.es5Shimmed=!0;Object.setPrototypeOf(HTMLElement,a)}})();function V(a){var b=HTMLElement.call(this)||this;a&&Ma(a);return b}w(V,HTMLElement);V.prototype.h=function(){console.warn(this.tagName,"has not implemented update")};V.prototype.c=function(a){a=void 0===a?"":a;return document.createRange().createContextualFragment(a||"")};
V.prototype.f=function(a,b,c){a&&b?a.parentNode.replaceChild(document.importNode(b,!0),a):!b&&a?a.parentNode.removeChild(a):!a&&b&&(c?(a=document.importNode(b,!0),c.parentElement.insertBefore(a,c.nextSibling)):this.appendChild(document.importNode(b,!0)))};function Ma(a){"string"===typeof a&&(a=[a]);document.body.dispatchEvent(new CustomEvent("devsite-load-custom-elements",{bubbles:!0,detail:a}))};var W=new Map;function X(a){var b=V.call(this)||this;a&&Ma(a);return b}w(X,V);X.prototype.connectedCallback=function(){var a=this.constructor,b=W.get(a);b?console.error("can't add duplicate element to page: "+b.tagName):W.set(a,this)};X.prototype.disconnectedCallback=function(){var a=this.constructor;W.get(a)===this&&W.delete(a)};X.prototype.disconnectedCallback=X.prototype.disconnectedCallback;X.prototype.connectedCallback=X.prototype.connectedCallback;var Y={},Na=(Y.gcs="//survey.g.doubleclick.net/async_survey?site=",Y.hats="//www.google.com/insights/consumersurveys/async_survey?site=",Y),Oa={},Pa=(Oa.gcs=["#contain-402",'script[src*="survey.g.doubleclick.net/gk/prompt"]','script[src*="survey.g.doubleclick.net"][src$="prompt_embed_static.js"]','script[src*="survey.g.doubleclick.net/async_survey?site="]'],Oa.hats='#contain-402 script[src*="www.google.com/insights/consumersurveys/async_survey?site="] script[src*="www.google.com/insights/consumersurveys/gk/static/hats-integration-release"] script[src*="adservice.google.com/adsid/integrator.js"] link[href*="adservice.google.com/adsid/integrator.js"] form[action*="www.google.com/insights/consumersurveys/gk/answer"] iframe[name*="closure_frame"][id*="closure_frame"]'.split(" "),
Oa);function Z(){var a=X.call(this)||this;a.a="";a.b="";return a}w(Z,X);function Qa(){return"devsite-google-survey"}Z.prototype.connectedCallback=function(){this.b=this.getAttribute("type");if(this.a=this.getAttribute("site-id")){var a=void 0===a?null:a;var b=Na[this.b]+this.a;b=b instanceof I?new I(b):new I(b,void 0);var c=document.createElement("script");c.src=b.toString();a&&(c.type=a);Ka(b.toString(),c)}};
Z.prototype.disconnectedCallback=function(){Pa[this.b].forEach(function(a){(a=document.querySelector(a))&&a&&a.parentNode&&a.parentNode.removeChild(a)});window._402&&delete window._402};Z.prototype.disconnectedCallback=Z.prototype.disconnectedCallback;Z.prototype.connectedCallback=Z.prototype.connectedCallback;Z.getTagName=Qa;try{window.customElements.define(Qa(),Z)}catch(a){console.warn("devsite.app.customElement.DevsiteGoogleSurvey",a)};}).call(this);
